### ISSUE TITLE
Use with Curl 

### ISSUE THREAD

**Issue by harinderbachhal** [smalot/pdfparser#101]
Hi,
Nice library, i am getting one error of over size file , some of my files are of 250 mb, so i am trying to ue curl to check size of file and then pass it through.
but i am getting error 
Warning: file_get_contents() expects parameter 1 to be a valid path, string given in /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 72,
Here is my code

$url = 'mysite.com/dfu_fra.pdf';

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout );
    curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie);
    curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
    $result = curl_exec($ch);
    curl_close($ch);

   // echo $result;

    /// PDF 2 Text
    $parser = new \Smalot\PdfParser\Parser();
    $pdf = $parser->parseFile($result);

    $pages = $pdf->getPages();

i know you can check size and then again put that file through again this will put load on php ... doing same thing 2 time, so is there way i can use curl to pass pdf.
or can i incress size of input file?
Thx

**Comment by smalot** [comment]
Hi,

I thing you should use the 'parseContent' method instead of the 'parseFile', because `$result` is not a filename, but the PDF File content itself:

````php
// PDF 2 Text
$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseContent($result);

$pages = $pdf->getPages();
````

BR

**Comment by harinderbachhal** [comment]
Thanks Bro, it worked ;) . one more thing is there any file limit on this , if so how can i increase  it ?

**Comment by smalot** [comment]
Don't know any limit.
Depend on your PDF file and your environment.
BR
