### ISSUE TITLE
Fatal error thrown in /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php on line 167

### ISSUE THREAD

**Issue by harinderbachhal** [smalot/pdfparser#102]
I am getting this error

Fatal error: Uncaught exception 'Exception' with message 'Missing object reference #461_0.' in /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php:167 Stack trace: #0 /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php(146): Smalot\PdfParser\Header->resolveXRef('Info') #1 /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(122): Smalot\PdfParser\Header->get('Info') #2 /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(86): Smalot\PdfParser\Document->buildDetails() #3 /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(152): Smalot\PdfParser\Document->init() #4 /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php(111): Smalot\PdfParser\Document->setObjects(Array) #5 /usr/share/nginx/html/test.php(52): Smalot\PdfParser\Parser->parseContent('%PDF-1.5?%?????...') #6 {main} thrown in /home/ubuntu/vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php on line 167

source file 
http://download.p4c.philips.com/files/2/241p4qpykeb_75/241p4qpykeb_75_dfu_fra.pdf

**Comment by chezinut** [comment]
there are some crap in file...  i used  www.ilovepdf.com to optimize/compress file after that...  error is gone

**Comment by k00ni** [comment]
Hey, if you are still using this library it would be great if you could try again with our latest release and get back to us. Thank you.
