### ISSUE TITLE
getText error behind percent sign (%)

### ISSUE THREAD

**Issue by juislip** [smalot/pdfparser#110]
I found error getText behide percent sign (%).

This's my code
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('uploads/C-160804022081.pdf');
$text = $pdf->getText();
$pdfText = nl2br($text); 
return $pdfText;

This's my pdf.
http://advanc.listedcompany.com/newsroom/C-160804022081.pdf

![untitled-1](https://cloud.githubusercontent.com/assets/4834589/17364098/771804aa-59a8-11e6-90f7-c6962b5e1aba.jpg)

Please advice, Thanks

**Comment by GreyWyvern** [comment]
This is working now, likely fixed by #597.
