### ISSUE TITLE
How to retrieve text annotations?

### ISSUE THREAD

**Issue by leopucci** [smalot/pdfparser#111]
I did not found a way to get the text annotations, is there any?

Thanks

Pucci

**Comment by capriele** [comment]
Dear Pucci,
I use the code below to get the Annotations:
`
$parser = new \Smalot\PdfParser\Parser();
$pdf_parsed = $parser->parseFile('filename.pdf'); 
$objects = $pdf_parsed->getDictionary();
if(array_key_exists('Annot', $objects) && !empty($objects['Annot']) ){
$annotations = $objects['Annot'];
}
`

**Comment by leopucci** [comment]
Thanks! @capriele
