### ISSUE TITLE
Code block is not visible - Documentation

### ISSUE THREAD

**Issue by anam-hossain** [smalot/pdfparser#112]
<img width="1225" alt="screen shot 2016-08-18 at 12 14 18 pm" src="https://cloud.githubusercontent.com/assets/5017268/17759747/8061b5a6-653d-11e6-9c41-5d378460b894.png">

**Comment by rubenvanerk** [comment]
This seems to have been fixed [in November 2016](https://web.archive.org/web/20161120095526/http://www.pdfparser.org:80/documentation), although the whole website is down now (#504).

**Comment by k00ni** [comment]
Closed because website is down. Please reopen if it comes back and problems still exists.
