### ISSUE TITLE
Is there a way to exclude common text?

### ISSUE THREAD

**Issue by wabsa** [smalot/pdfparser#113]
Is there a way to exclude common text like 'a', 'the', etc... In my case i would like to use it those extracted text for searching. Thanks

**Comment by rubenvanerk** [comment]
This is not something pdfparser should handle, but you could do something like this:
```php
$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile('path/to/file');
$text = $pdf->getText();
$commonWords = array('a', 'the');
$text = preg_replace('/\b(' . implode('|', $commonWords) . ')\b/', '', $text);
```
From the gist you already seem to have found: https://gist.github.com/keithmorris/4155220

**Comment by k00ni** [comment]
I agree with @rubenvanerk.
