### ISSUE TITLE
Licence bug

### ISSUE THREAD

**Issue by sirfragalot** [smalot/pdfparser#115]
Hi Sebastien,

Not really a bug in the software sense but this is something that will stop your software being used by many others including myself.

The problem is the GPL 3 licence that is too restrictive for many purposes. There are two issues the GPL licence has -- 1. incompatibility of GPL with some countries' laws of intellectual property and 2. the fact that it is a 'viral licence.'

Both case mean that I can't use your software. I program WIKINDX (https://sourceforge.net/projects/wikindx/). It's currently under GPL but I am shifting to CeCILL http://www.cecill.info/licences.fr.html because of the two points above.
1. GPL is incompatible with e.g French intellectual copyright laws. I have a French collaborator on WIKINDX who is uneasy about contributing to WIKINDX because of the GPL.
2. GPL requires any software using GPL'ed software to also be released under the GPL licence. Clearly, if I shift to CeCILL to a) satisfy my collaborator in France and b) allow others to package and use WIKINDX without themselves being forced to use GPL.

I hope it will be possible for you to release a version of your software with a less restrictive licence.

Regards,

Mark

**Comment by smalot** [comment]
Hi,

This library is mainly based on "tecnickcom/tcpdf" library which is licenced under GNU-LGPL v3.
I'm not very aware about licencing rules, but I put my work under this licence too.
About French intellectual copyright laws, I'm the author even if I use a wrong licence.

BR

**Comment by sirfragalot** [comment]
Many thanks for the quick response Sebastien.

The GNU-LGPL likewise requires the use of GNU-GPL for the 'host' software (i.e. WIKINDX in this case)  it's a licence that's too restrictive for the free use GPL intends. However, as you use the tcpdf library, then you can't shift to another licence.

We need to find another solution unfortunately.

Regards,

Mark

**Comment by sirfragalot** [comment]
Hi Sebastien,

Just to clarify, when you say your code is **Lesser GHPL**, your code actually states **GPL**. If the code were actually Lesser GPL, then we could use it. Your licence is:
'GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
....'

We can't use your code with that restrictive, viral licence.
Regards,

Mark

**Comment by johnvandeweghe** [comment]
This appears to be complete as of today @smalot
