### ISSUE TITLE
Using PdfParser without Composer

### ISSUE THREAD

**Issue by apmuthu** [smalot/pdfparser#117]
**Last checked in** 2020

**Updated file:**  [vendor-autoload.zip](https://github.com/smalot/pdfparser/files/5068588/vendor-autoload.zip) - See https://github.com/smalot/pdfparser/issues/117#issuecomment-673408008

The `../vendor/autoload.php` gets generated when we use composer and we include it in our scripts for PdfParser access. If we wish to freeze our install and manage it without using Composer, this said file can be created to have the following:

```php
<?php
/**
 * this file acts as vendor/autoload.php
 */

/*
Using PDFParser without Composer
Folder structure
================
webroot
  pdfdemos
    INV001.pdf # test PDF file to extract text from for demo
    test.php # our operational demo file
  vendor
    autoload.php
    smalot
      pdfparser # unpack from git master https://github.com/smalot/pdfparser/archive/master.zip release is 0.9.25 dated 2015-09-15
        docs # optional
        samples # optional
        src
          Smalot
            PdfParser
*/

$prerequisites = array();

/**
 * TODO: ADAPT THIS PATH TO pdfparser
 */ 
$pdfparser = '/host/path/to/pdfparser';

$prerequisites['pdfparser'] = array (
    $pdfparser.'/Config.php',
    $pdfparser.'/Parser.php',
    $pdfparser.'/Document.php',
    $pdfparser.'/Header.php',
    $pdfparser.'/PDFObject.php',
    $pdfparser.'/Element.php',
    $pdfparser.'/Encoding.php',
    $pdfparser.'/Font.php',
    $pdfparser.'/Page.php',
    $pdfparser.'/Pages.php',
    $pdfparser.'/Element/ElementArray.php',
    $pdfparser.'/Element/ElementBoolean.php',
    $pdfparser.'/Element/ElementString.php',
    $pdfparser.'/Element/ElementDate.php',
    $pdfparser.'/Element/ElementHexa.php',
    $pdfparser.'/Element/ElementMissing.php',
    $pdfparser.'/Element/ElementName.php',
    $pdfparser.'/Element/ElementNull.php',
    $pdfparser.'/Element/ElementNumeric.php',
    $pdfparser.'/Element/ElementStruct.php',
    $pdfparser.'/Element/ElementXRef.php',
    $pdfparser.'/Encoding/StandardEncoding.php',
    $pdfparser.'/Encoding/ISOLatin1Encoding.php',
    $pdfparser.'/Encoding/ISOLatin9Encoding.php',
    $pdfparser.'/Encoding/MacRomanEncoding.php',
    $pdfparser.'/Encoding/WinAnsiEncoding.php',
    $pdfparser.'/Font/FontCIDFontType0.php',
    $pdfparser.'/Font/FontCIDFontType2.php',
    $pdfparser.'/Font/FontTrueType.php',
    $pdfparser.'/Font/FontType0.php',
    $pdfparser.'/Font/FontType1.php',
    $pdfparser.'/RawData/FilterHelper.php',
    $pdfparser.'/RawData/RawDataParser.php',
    $pdfparser.'/XObject/Form.php',
    $pdfparser.'/XObject/Image.php'
);

foreach($prerequisites as $project => $includes) {
    foreach($includes as $mapping => $file) {
      require_once $file;
    }
}

/*
// Information for comparison with composer
use Datamatrix;
use PDF417;
use QRcode;
use TCPDF;
use TCPDF2DBarcode;
use TCPDFBarcode;
use TCPDF_COLORS;
use TCPDF_FILTERS;
use TCPDF_FONTS;
use TCPDF_FONT_DATA;
use TCPDF_IMAGES;
use TCPDF_IMPORT;
use TCPDF_PARSER;
use TCPDF_STATIC;
*/
```

We can now create a `test.php` in the deployment folder (`pdfdemos` here) with:

```php
<?php
include "../vendor/autoload.php";

$directory = getcwd();
$file = 'INV001.pdf';
$fullfile = $directory . '/' . $file;
$content = '';
$out = '';
$parser = new \Smalot\PdfParser\Parser();

$document = $parser->parseFile($fullfile);
$pages    = $document->getPages();
$page     = $pages[0];
$content  = $page->getText();
$out      = $content;
echo '<pre>' . $out . '</pre>';
```
---
**EDIT 1 by k00ni:** added updated PHP code from @ndmax. Also removed `tecnickcom/tcpdf` (not needed anymore) and added code highlighting.

**Comment by rajeshgozoom** [comment]
Wow Man, You are great, that really awesome and worked for me...

Thanks a TON!!!

**Comment by kaustavdey** [comment]
Sir its simply great. Can you also help to install Tesseract OCR for php without composer?

**Comment by apmuthu** [comment]
I have not used this wrapper: [Tesseract OCR for PHP](https://github.com/thiagoalessio/tesseract-ocr-for-php). If you succeed in deploying it, do let us know what issues crop up.

I have only used the compiled version of [Tesseract OCR](https://github.com/tesseract-ocr/tesseract).

**Comment by yousaf50** [comment]
WOW sweet work ..love from pakistan.

**Comment by federicovilla** [comment]
Great hint apmuthu...this solve my issue since I cannot run composer on my remote server.
I'm trying to use your modified installation and autoload into a Codeigniter site...so I installed all files and autoload into the third_party folder.
I have created a library with the follpwing code
`class Pdfparser {
    function __construct() {
        require_once '/third_party/vendor/autoload.php';
    }
}`

but when I try to load the library I get the following error:
`[26-Oct-2018 08:12:25 UTC] PHP Fatal error:  require_once(): Failed opening required '/third_party/vendor/autoload.php' (include_path='.:/opt/alt/php54/usr/share/pear:/opt/alt/php54/usr/share/php') in /home/gavsit/public_html/application/libraries/Pdfparser.php on line 6`

Any hint to solve this? Thanks a lot

**Comment by apmuthu** [comment]
Make the path to the autoload relative like:
````
class Pdfparser {
    function __construct() {
        require_once ('third_party/vendor/autoload.php');
    }
 }
````

**Comment by doganoo** [comment]
What exactly you mean by „freeze“? Composer doesn’t update any files until you run „composer update“ and you don’t change your composer.json and/or composer.lock files.

Therefore, just run “composer update” on your instance and enjoy?!

**Comment by apmuthu** [comment]
For those who cannot use composer for whatever reason (offline, stability, unfamiliarity, etc), this thread lists an alternative.

**Comment by ndmax** [comment]
I really do wish this was baked into pdfparser (and other projects that assume Composer).  I don't use Composer, and don't want to add yet another dependency/package manager for one project submodule.  Composer isn't installed in my production environment.

I don't mean to suggest ejecting Composer (it's a common standard and super easy if you're already using it), but simply including an installation procedure that doesn't _require_ Composer.  An example would be the [DOMPDF](https://github.com/dompdf/dompdf) project.

In any case, thanks @apmuthu for this post.

**Comment by ndmax** [comment]
Also: `Object.php` is now `PDFObject.php`

**Comment by apmuthu** [comment]
@ndmax: Thanks for the info and glad for the +1 composer-less implementation initiative.

Yes, you're right, the renaming of the file will now require, in the code snippet above, the replacement of the line:
````
include_once  $vendorDir . "/smalot/pdfparser/src/Smalot/PdfParser/Object.php";
````
with
````
include_once  $vendorDir . "/smalot/pdfparser/src/Smalot/PdfParser/PDFObject.php";
````

**Comment by WillRun4Cake** [comment]
Apmuthu, thank you. This thread was very helpful.
Below I have attached an example for doing this without Composer. This should be extracted to the /var/www/html directory or public_html directory.
Two additional things to mention:
1. I just cloned the master branch on May 3, 2020 and the Object.php has still not been renamed to PDFObject.php
2. Make sure you have the php-mbstring extension installed, e.g.
     sudo apt-get install php-mbstring
     yum install php-mbstring
     # php.ini -> extension=mbstring
[example.zip](https://github.com/smalot/pdfparser/files/4576686/example.zip)
[example.tar.gz](https://github.com/smalot/pdfparser/files/4576695/example.tar.gz)

**Comment by apmuthu** [comment]
Thanks Joseph. Stands corrected.

**Comment by hemaantjd** [comment]
Thank you WillRun4Cake... It's working great...  https://www.hemantjadhav.com/

**Comment by j0k3r** [comment]
Duplicates https://github.com/smalot/pdfparser/issues/279

**Comment by ndmax** [comment]
For those who have been manually implementing w/o Composer, the following two new includes are now required:
    `/RawData/FilterHelper.php`
    `/RawData/RawDataParser.php`

**Comment by k00ni** [comment]
Because this issue seems interesting for some people, we could pin it. Furthermore, information like the last of @ndmax should be merged into the initial post so that new people find them quickly without the need to scroll through the whole issue.

What do you think? 

CC @j0k3r

**Comment by j0k3r** [comment]
@k00ni I agree. I've pinned the issue. Can you update the initial post?

**Comment by k00ni** [comment]
@ndmax, @apmuthu and others: I would like to keep the initial post update to date. Can you tell me, what needs to be changed?

As far as I saw, these files need to be added:

```
/RawData/FilterHelper.php
/RawData/RawDataParser.php
```

**Comment by ndmax** [comment]
Thanks @k00ni and @j0k3r.  Relative to the project directory, I think a current full list of includes would look something like this:

```
/Parser.php
/Document.php
/Header.php
/PDFObject.php
/Element.php
/Encoding.php
/Font.php
/Page.php
/Pages.php
/Element/ElementArray.php
/Element/ElementBoolean.php
/Element/ElementString.php
/Element/ElementDate.php
/Element/ElementHexa.php
/Element/ElementMissing.php
/Element/ElementName.php
/Element/ElementNull.php
/Element/ElementNumeric.php
/Element/ElementStruct.php
/Element/ElementXRef.php
/Encoding/StandardEncoding.php
/Encoding/ISOLatin1Encoding.php
/Encoding/ISOLatin9Encoding.php
/Encoding/MacRomanEncoding.php
/Encoding/WinAnsiEncoding.php
/Font/FontCIDFontType0.php
/Font/FontCIDFontType2.php
/Font/FontTrueType.php
/Font/FontType0.php
/Font/FontType1.php
/RawData/FilterHelper.php
/RawData/RawDataParser.php
/XObject/Form.php
/XObject/Image.php
```

**Comment by k00ni** [comment]
Sorry for the late response @ndmax. I hope its not too much of an ask: can you put your file list (as includes) in the code from @apmuthu so I can copy it directly?

**Comment by apmuthu** [comment]
[vendor-autoload.zip](https://github.com/smalot/pdfparser/files/5068588/vendor-autoload.zip)
The order of the files given by @ndmax is correct and the `../vendor/autoload.php` file stands attached herewith.

**Comment by ndmax** [comment]
Sorry I missed this @k00ni and thanks @apmuthu for posting up a drop-in file.

For what it's worth, I implement pdfparser as part of a larger class responsible for all PDF-related functionality. Here's how the pdfparser component get's wired up (trimmed up a bit for simplicity):

```php
<?php

  $prerequisites = array();

  $pdfparser = '/host/path/to/pdfparser';

  $prerequisites['pdfparser'] = array (
    $pdfparser.'/Parser.php',
    $pdfparser.'/Document.php',
    $pdfparser.'/Header.php',
    $pdfparser.'/PDFObject.php',
    $pdfparser.'/Element.php',
    $pdfparser.'/Encoding.php',
    $pdfparser.'/Font.php',
    $pdfparser.'/Page.php',
    $pdfparser.'/Pages.php',
    $pdfparser.'/Element/ElementArray.php',
    $pdfparser.'/Element/ElementBoolean.php',
    $pdfparser.'/Element/ElementString.php',
    $pdfparser.'/Element/ElementDate.php',
    $pdfparser.'/Element/ElementHexa.php',
    $pdfparser.'/Element/ElementMissing.php',
    $pdfparser.'/Element/ElementName.php',
    $pdfparser.'/Element/ElementNull.php',
    $pdfparser.'/Element/ElementNumeric.php',
    $pdfparser.'/Element/ElementStruct.php',
    $pdfparser.'/Element/ElementXRef.php',
    $pdfparser.'/Encoding/StandardEncoding.php',
    $pdfparser.'/Encoding/ISOLatin1Encoding.php',
    $pdfparser.'/Encoding/ISOLatin9Encoding.php',
    $pdfparser.'/Encoding/MacRomanEncoding.php',
    $pdfparser.'/Encoding/WinAnsiEncoding.php',
    $pdfparser.'/Font/FontCIDFontType0.php',
    $pdfparser.'/Font/FontCIDFontType2.php',
    $pdfparser.'/Font/FontTrueType.php',
    $pdfparser.'/Font/FontType0.php',
    $pdfparser.'/Font/FontType1.php',
    $pdfparser.'/RawData/FilterHelper.php',
    $pdfparser.'/RawData/RawDataParser.php',
    $pdfparser.'/XObject/Form.php',
    $pdfparser.'/XObject/Image.php'
  );

  foreach($prerequisites as $project => $includes) {
    foreach($includes as $mapping => $file) {
      require_once $file;
    }
  }

?>
```

**Comment by k00ni** [comment]
OK, i adapted @apmuthu's initial post with code from @ndmax. Hope I didn't miss something.

**Comment by WillRun4Cake** [comment]
I have updated my example for using PdfParser when Composer is not an option.

It now aligns with the v0.17.1 release and includes 3 new files:
  RawData/FilterHelper.php
  RawData/RawDataParser.php
  Encoding/PostScriptGlyphs.php

You can download, extract and copy this to your webroot directory to start using PdfParser immediately.
Follow the example code in text_extractor_example.php to invoke PdfParser.
Only the classes/ directory is required. The following files are for example and may be deleted:
  readme.md
  test.pdf    (replace with your own pdf)
  text_extractor_example.php    (example code)
  index.php    (use your existing index.php)

This should be placed in the /var/www/html directory or public_html webroot directory, as applicable.

Two additional things to mention:
    1. Make sure you have the php-mbstring extension installed, e.g.
        sudo apt-get install php-mbstring
        OR
        yum install php-mbstring
    2. You may also need to enable in php.ini:
        extension=mbstring

PdfParser Team, I noticed that Object.php was renamed to PDFObject.php. Thanks for making this fix.
[example.zip](https://github.com/smalot/pdfparser/files/5470125/example.zip)
[example.tar.gz](https://github.com/smalot/pdfparser/files/5470126/example.tar.gz)

**Comment by WillRun4Cake** [comment]
I have attached an updated set of example files to use the new files:
/RawData/FilterHelper.php
/RawData/RawDataParser.php

This should now align with v0.17.1. This took quite some time to get around
to doing, but hopefully this will be helpful to someone. Thanks for
including me in the email list.

**Comment by ndmax** [comment]
Hello Everyone,

If you're still implementing this project manually and you're suddenly getting 500s with `Fatal error: Uncaught Error: Class 'Smalot\PdfParser\Config' not found` there's a new include:

`'/Config.php'`

@apmuthu @k00ni it might be worth adding `$pdfparser.'/Config.php',` to the code snippet for manual include.

**Comment by k00ni** [comment]
@ndmax thank you for the hint. I updated the initial post accordingly.

---

In my opinion `Composer` should be the way to go, but I acknowledge that there is also the need to use other ways. Therefore my **proposal**: 
* create a new file in root folder, named `autoload.php` or something like that
* move includes from initial post into that file
* close this issue with a notice about that file

**Advantages:**
* Its easier for developers to just `require` this file and have everything they need (no need to parse this issue again and again when there are upgrades)
* We can extend this file by using pull requests, which makes it easier to be up to date

What do you think?

CC @j0k3r @apmuthu

**Comment by j0k3r** [comment]
That might be a good idea. We should warm people that the `mbstring` extension will then be required because the Symfony polyfill won't be installed (required in `composer.json`).
Following adding that new `autoload.php` file, we should also add a custom test to ensure it is working as expected. So the test will fail if we add a new file and forgot to update the `autoload.php` file.

**Comment by ndmax** [comment]
I think it's a good approach @k00ni.  It eliminates the cat-and-mouse for the few who incorporate manually, without disrupting the majority who install with Composer.  Comment instructions at the top of `autoload.php` and a brief reference to install options in `README.md` would point everyone down the right path.

**Comment by apmuthu** [comment]
The said `autoload.php` should not be overwritten any any unintended composer update / unzip.

A files called `autoload_standalone.php` that gets `include`d if present may be the answer.

In order not to break dependencies of certain missing libraries / files, the optional set of includes can be commented out and enabled as needed by the end user.

Notes in it as applicable to certain commits onwards would be useful to use the appropriate version.

**Comment by k00ni** [comment]
There is a new pull request which may help in the future. Once it passes there should be no more manual work required to use PDFParser without Composer.

Feedback is appreciated at #388

**Comment by DionardoMarques** [comment]
Thanks a lot, it worked perfectly! Regards from Brazil.
