### ISSUE TITLE
Fix the documentation JavaScript error

### ISSUE THREAD

**Issue by peter279k** [smalot/pdfparser#127]
In [documentation ](http://www.pdfparser.org/documentation)section, the JavaScript code highlighter has some problems.
Please fix it.

![highlighter](https://cloud.githubusercontent.com/assets/9021747/20174862/dfa4a558-a77a-11e6-914b-3e732f9504a9.PNG)

**Comment by smalot** [comment]
Fixed.
Thanks for your report
