### ISSUE TITLE
Issue with beginbfchar regex

### ISSUE THREAD

**Issue by XavierVILAIN** [smalot/pdfparser#128]
Hello,

i was parsing a pdf where the char mapping contains a space between from and to value. I fix it by changing your code here : 
```
// Support for multiple bfchar sections
  if (preg_match_all('/beginbfchar(?P<sections>.*?)endbfchar/s', $content, $matches)) {
            	
                foreach ($matches['sections'] as $section) {
// $regexp = '/<(?P<from>[0-9A-F]+)>( |)+<(?P<to>[0-9A-F]+)>[ \r\n]+/is'; // Issue with space
                    $regexp = '/<(?P<from>[0-9A-F]+)>( |)+<(?P<to>[0-9A-F]+)>[ \r\n]+/is';
```

**Comment by k00ni** [comment]
Closing this. Please submit a PR for suggestions like that in the future, because they easily get ignored when inside an issue. Also, a demo/PDF to demonstrate the fix would be helpful.

Thanks for investing the time though.
