### ISSUE TITLE
Handling Secured File

### ISSUE THREAD

**Issue by alimasyhur** [smalot/pdfparser#134]
Hi, @smalot and team
Kindly tell me how to handle the error when uploading secured pdf file while parsing that file, because there're no documentation to handle it.
To prevent this kind of error.
![secured pdf](https://cloud.githubusercontent.com/assets/8981410/20697687/c60bde56-b62d-11e6-9c15-b94bcabb56b4.png)

Thanks

**Comment by anam-imtiaz** [comment]
Same problem

**Comment by ShutUpMagda** [comment]
It is pretty simple. The `parseContent()` method returns an exception in this case. All you need to do is catch this exception on `parseFile()` declaration using PHP's try/catch:

```
function pdf_parser($filepath){
        $parser = new \Smalot\PdfParser\Parser();
        try {
            $parser->parseFile($filepath);
        } 
        catch (Exception $e) {
            if ($e->getMessage()) {
                echo 'Returned: '.$e->getMessage();
                return FALSE;
            }
        }
        $pdf = $parser->parseFile($filepath);
         /* do anything else here...*/
        return TRUE;
    }
```

**Comment by alimasyhur** [comment]
@ShutUpMagda thanks. Actually I also solved my issue

**Comment by ShutUpMagda** [comment]
So, how about closing this? ;)

**Comment by 4044ever** [comment]
I still have that problem and can't get the _ShutUpMagda_ code to work,

How would that look complete with a test.pdf file?

**Comment by gazalkochar** [comment]
> @ShutUpMagda thanks. Actually I also solved my issue

But how did you do that?

**Comment by smalot** [comment]
Indeed, secured files are not supported.
The fix provided by @ShutUpMagda is a good quick fix.
Thanks
