### ISSUE TITLE
Should license be LGPL rather than GPL?

### ISSUE THREAD

**Issue by kriegfrj** [smalot/pdfparser#137]
I note that in #11 the license was upgraded from GPLv2 to GPLv3.

Was the choice of GPL instead of LGPL deliberate? The former is a bit more restrictive than the latter - if your software is GPL then it can't be used in commercial software, LGPL libraries can be used in commercial software.

If the choice was deliberate, I respect your decision as the author, but I thought it would be good just to check.

**Comment by smalot** [comment]
"smalot/pdfparser" is mainly based on "tecnickcom/tcpdf" which is "LGPLv3".
That's why I choose this license. Did I made a mistake ?

**Comment by smalot** [comment]
Oops, seems Nicola changed its own license ...

**Comment by smalot** [comment]
Being fixed

**Comment by kriegfrj** [comment]
👍
