### ISSUE TITLE
Parser returns \f at some lines

### ISSUE THREAD

**Issue by CNekk** [smalot/pdfparser#138]

**Comment by CNekk** [comment]
Hm.... I detected where is the problem. When parser converts pdf file, it always removes right parentheis. Always. And after removing appears problem...
My level in php is not so high for fix it safely and quickly. Seems to me, trouble somewhere in this file: .../vendor/smalot/pdfparser/src/Smalot/PdfParser/Object.php
may be in string 577
while ($offset < strlen($text_part)) {
            $offset += strspn($text_part, "\x00\x09\x0a\x0c\x0d\x20", $offset);
            $char = $text_part[$offset]; ........ 
other parts in 645 and more. Where are many depends for this checking, simple commenting or deleting leads to the fact that the pdf content is not displayed.
Have a idea? )))

p.s. I'll try to remove all parentheis from pdf before upload, but I think it'll not help...

**Comment by write2art** [comment]
I`ve encountered this one too. On documents created with iText Java library parsing fails on ")" symbol. After that everything that follows gets corrupted util the end of the line.

**Comment by antonshell** [comment]
+1
Have the same issue. Any updates about it?

**Comment by edodije** [comment]
@CNekk Do you already got solution for this issue..? I have the same problem with that..

**Comment by write2art** [comment]
I`ve just swithed to another library (js) - this project looks abandoned.

**Comment by CNekk** [comment]
> @CNekk Do you already got solution for this issue..? I have the same problem with that..

Yes!
Sorry, wasnt here a so long...

**Comment by GreyWyvern** [comment]
No PDF file to test, but this seems like it would be fixed by #597

**Comment by k00ni** [comment]
> No PDF file to test, but this seems like it would be fixed by #597

Can anyone confirm that? @CNekk @write2art @antonshell @edodije
