### ISSUE TITLE
Fatal error: Call to a member function getContent() on a non-object

### ISSUE THREAD

**Issue by PetrToman** [smalot/pdfparser#14]
Parsing http://www.bcl.hamilton.ie/~barak/papers/CMU-CS-90-196.pdf by:

```
<?php
    ini_set('memory_limit', '512M');

    include '../vendor/autoload.php';

    $filename = __DIR__ . '/../samples/CMU-CS-90-196.pdf';
    $parser   = new Smalot\PdfParser\Parser();
    $document = $parser->parseFile($filename);
    $pages    = $document->getPages();
    $page     = $pages[0];
    $text     = $page->getText();

    var_dump($text);
?>
```

...causes the following error:

```
Fatal error: Call to a member function getContent() on a non-object in D:\pdfparser\src\Smalot\PdfParser\Encoding.php on line 90

Call Stack:
    0.0003     124752   1. {main}() D:\pdfparser\src\Test.php:0
    0.0081     277152   2. Smalot\PdfParser\Parser->parseFile() D:\pdfparser\src\Test.php:8
    0.1120     928536   3. Smalot\PdfParser\Parser->parseContent() D:\pdfparser\src\Smalot\PdfParser\Parser.php:74
    4.0082   19114896   4. Smalot\PdfParser\Document->setObjects() D:\pdfparser\src\Smalot\PdfParser\Parser.php:103
    4.0086   19225080   5. Smalot\PdfParser\Document->init() D:\pdfparser\src\Smalot\PdfParser\Document.php:152
    4.1115   19459320   6. Smalot\PdfParser\Encoding->init() D:\pdfparser\src\Smalot\PdfParser\Document.php:90
```

**Comment by huihuangjiuai** [comment]
The problem 1.0.2 still exists, causing me to fail to catch the exception

**Comment by huihuangjiuai** [comment]
[think\exception\ThrowableError]
  Fatal error: Call to a member function getContent() on null



Exception trace:
 () at /mnt/f/henry_jia/workspace_php/app_baogao/vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:221
 Smalot\PdfParser\Page->getText() at /mnt/f/henry_jia/workspace_php/app_baogao/app/module/PdfFile/helper/PdfFileParseHelper.php:83
 app\module\PdfFile\helper\PdfFileParseHelper::extractContent() at /mnt/f/henry_jia/workspace_php/app_baogao/app/module/PdfFile/helper/PdfFileParseHelper.php:399
 app\module\PdfFile\helper\PdfFileParseHelper::countdownToParsePdfFile() at /mnt/f/henry_jia/workspace_php/app_baogao/app/module/PdfFile/helper/PdfFileParseHelper.php:318
 app\module\PdfFile\helper\PdfFileParseHelper->savePdfFileContentForPdfParser() at /mnt/f/henry_jia/workspace_php/app_baogao/app/module/PdfFile/helper/PdfFileRabbitHelper.php:151
 app\module\PdfFile\helper\PdfFileRabbitHelper->consumeCallback() at /mnt/f/henry_jia/workspace_php/app_baogao/app/module/PdfFile/helper/PdfFileRabbitHelper.php:94
 app\module\PdfFile\helper\PdfFileRabbitHelper->app\module\PdfFile\helper\{closure}() at n/a:n/a
 call_user_func() at /mnt/f/henry_jia/workspace_php/app_baogao/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1044
 PhpAmqpLib\Channel\AMQPChannel->basic_deliver() at n/a:n/a

**Comment by k00ni** [comment]
@huihuangjiuai please provide some example code and/or PDF which we can include in our test environment (it must be free of charge and without any obligations).

**Comment by huihuangjiuai** [comment]
This is my problem I have solved, PHP7 version above, catch the Error can be，thank you

**Comment by k00ni** [comment]
> This is my problem I have solved, PHP7 version above, catch the Error can be，thank you

I am sorry, I don't fully understand. Do you mean that it is solved?
