### ISSUE TITLE
class 'TCPDF_PARSER' not find

### ISSUE THREAD

**Issue by tangxiaoguang** [smalot/pdfparser#143]
Any one can tell me where is the class of tcpdf_parser in the pdfparser-master file . Appreciate receiving

**Comment by xelan** [comment]
You have to install the dependencies [via composer](https://getcomposer.org/doc/03-cli.md#install) or manually when using this library. If you install `pdfparser` via composer, its dependencies are automatically installed into the `vendor` directory.

**Comment by j0k3r** [comment]
We removed TCPDF in the latest release.

**Comment by k00ni** [comment]
For further information on why we removed TCPDF: #299
