### ISSUE TITLE
Cannot extract text from PDF (internal font naming issue)

### ISSUE THREAD

**Issue by madmax-inc** [smalot/pdfparser#145]
Hi. 
While trying to extract the text from PDF
[test.pdf](https://github.com/smalot/pdfparser/files/867641/test.pdf)
 I was only able to extract "\n"s.
My investigation results:

While trying to parse "commandsText" (PdfParser::getCommandsText), there is an intresting issue:
Given a line "/f-0-0 1 Tf" it tries to parse it with two regular expressions assuming that the font "id" will not contain "-" symbols while it actually contains.

As a result, it stops parsing without any error message and the output is incorrect.

My fix is (one more regexp):
```php
elseif (preg_match(
                        '/^\/([A-Z0-9\._,\+\-]+\s+[0-9]+)\s+([A-Z]+)\s*/si',
                        substr($text_part, $offset),
                        $matches
                    )
                    ) {
                        $operator = $matches[2];
                        $command  = $matches[1];
                        $offset += strlen($matches[0]);
                    }
```

Pull request coming soon. Or maybe some remarks?

**Comment by GreyWyvern** [comment]
@madmax-inc PR #614 fixes this issue. May we use your _test.pdf_ file in the PdfParser test suite?
