### ISSUE TITLE
Unable to extract text from certain pdf files

### ISSUE THREAD

**Issue by mcampsteyn** [smalot/pdfparser#149]
Hi,
I'm having an issue extracting text from certain pdf files. The pdf parser is unable to extract text. Or the parser extracts something but it appears to be encoded. Attached you can find an example document and the extract we get. I also tested it via the pdfparser website and got the same result.
Any hints to resolve this issue would be  appreciated.

[EnergyInvoice.pdf](https://github.com/smalot/pdfparser/files/934693/EnergyInvoice.pdf)
![image](https://cloud.githubusercontent.com/assets/20879893/25182265/57bb63f8-2514-11e7-9a85-2c97d1562d13.png)

**Comment by rozasmerti** [comment]
May be it was encoded, I have same problem and encoding with 'qpdf --object-streams=disable %path_to_file% %new_path_to_file%'  in console help me

**Comment by BernhardWebstudio** [comment]
I also have a few examples of PDFs where the text extraction did return something but not what was expected. Do you have any tips on how to debug, @smalot ?

**Comment by Gollm** [comment]
I have the same issue with some pdf. Also tested on https://www.pdfparser.org/demo and also got the same result.
Explicit example: pdfs from comdirect bank

**Metadata**
Creator: afp2any v2.4-17_6 - Licensee 'Comdirect Prod 1'
Author: HAVI Solutions GmbH & Co. KG, phg
Licensee: Comdirect Prod 1
Producer: PDFlib 4.0.1-t3 [Linux 3.2.0-4-amd64], modified by HAVI


**Outputted Text (extract):**

> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@	
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@	@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@	
> @	
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> ðñKðøKòðñø	
> È…™™•@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Æ“–™‰•@Ç–““”…™@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Â…™‡‡‰…¡ˆÐ‚“…™@â£™K@ñõ@@@@@@@@@@@@@
> ðñò÷÷@Ä™…¢„…•@@@@@@@@@@@@@@@@@@@@@@	
> @@@@@	ñðòöó	ðñð	
> @@@@@@@@@@@@@@@@@@@
> @@@@@@@@@@@@@@@@@@@@@@@@	
> @@@@@@@

**Comment by guntherhoppe** [comment]
@smalot Hi, I also ran into this issue and tracked it down (at least for the comdirect PDF issue). The problem here is that the PDF Font Encoding Differences are currently not handled within the PdfParser lib.

Example from the comdirect PDF:
```
43 0 obj
<</Type/Encoding
/Differences[
 64/space 74/Adieresis/period 77/parenleft 92/asterisk/parenright 96/hyphen/slash 106/odieresis/comma 122/colon 124/section 127/quotedbl 129/a/b/c
/d/e/f/g/h/i 146/k/l/m/n/o/p/q/r 161/germandbls/s
/t/u/v/w 169/z 192/adieresis/A/B/C/D/E/F/G/H/I 208/udieresis
 210/K/L/M/N/O/P/Q/R 226/S/T/U/V/W/X/Y/Z
 240/zero/one/two/three/four/five/six/seven/eight/nine]
>>
```
The ```64/space``` for instance results in these '@' lines, because the ASCII code of '@' is 64 (decimal). But the PDF's font encoding maps 64 actually to SPACE character. Same to other chars.

I came up with a simple solution approach to this: [PdfFontEncodingDecoder.php.txt](https://github.com/smalot/pdfparser/files/6967709/PdfFontEncodingDecoder.php.txt)

Adding the following to the ```\Smalot\PdfParser\Font```'s method ```decodeText```:
```
$decoder = new \File\Util\PdfFontEncodingDecoder($this);
$decoded = $decoder->decode($command[PDFObject::COMMAND]);
$command[PDFObject::COMMAND] = $decoded;
```
before calling ```self::decodeHexadecimal```.

This solves the issue with comdirect PDF (and probably also for others with Font Encoding Differences defined). I did not create a PR to this, because it is a (too) simple implementation which may not support all possible cases.

**Comment by nicoflemming** [comment]
@k00ni will this fix be added to the package?

**Comment by k00ni** [comment]
The best way would be to create a pull request with these changes. There we can discuss it and see, if anything breaks.

**Comment by GreyWyvern** [comment]
The sample file [EnergyInvoice.pdf](https://github.com/smalot/pdfparser/files/934693/EnergyInvoice.pdf) is working in the current v2.7.0 release. Not sure where it got fixed along the way.
