### ISSUE TITLE
Fatal error: Class 'pdfparsermaster\PdfParser\Parser' not found

### ISSUE THREAD

**Issue by Govind13100** [smalot/pdfparser#150]
Please provide solution ASAP

**Comment by smalot** [comment]
ASAP ? Are you kidding me ?

**Comment by safi78** [comment]
Wow ...

**Comment by Govind13100** [comment]
No, i am not kidding , its important for me , i am stuck in between.

**Comment by smalot** [comment]
RTFM: http://www.pdfparser.org/documentation
