### ISSUE TITLE
Sometimes unable to parse greek character 'Σ' 

### ISSUE THREAD

**Issue by lefgoumas** [smalot/pdfparser#151]
I am trying to parse pdf files with greek characters. The issue is with capital character 'Σ'.
But not in all files. I have attached 2 files, one which is parsed ok and one which has problem when parsing
the particular character.
[ok.pdf](https://github.com/smalot/pdfparser/files/1007177/ok.pdf)
[problematic.pdf](https://github.com/smalot/pdfparser/files/1007176/problematic.pdf)

**Comment by davispuh** [comment]
Try #257 PR it should be fixed there.

**Comment by Connum** [comment]
I can confirm that this issue got fixed with 4f4fd10, testing the file `problematic.pdf` before and after that commit.
