### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by j0k3r** [smalot/pdfparser#161]
Looks like the `Object` class make the library **not** 7.2 compatible

> PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /home/travis/build/wallabag/wallabag/vendor/smalot/pdfparser/src/Smalot/PdfParser/Object.php on line 41

https://travis-ci.org/wallabag/wallabag/jobs/256892692#L874

**Comment by smalot** [comment]
Grrrrr

**Comment by smalot** [comment]
Thanks for the report

**Comment by belgattitude** [comment]
@smalot , affected too. Do you have an idea to rename 'Object' (i.e. PDFObject...) ? Will probably be a BC-break :(

If you agree I can make a P/R ?

**Comment by smalot** [comment]
I've just pushed a fix on the master branch.
Can you check it ?

**Comment by belgattitude** [comment]
@smalot works now with PHP7.2RC1. Thanks a lot
