### ISSUE TITLE
PDF PARSER DIE WHEN PDF HAS SPECIAL CHARACTERS

### ISSUE THREAD

**Issue by nicard** [smalot/pdfparser#162]
![error](https://user-images.githubusercontent.com/14842229/28938980-2cb30800-7866-11e7-9d48-8f5578a9e846.PNG)

Could you help me?

**Comment by Connum** [comment]
@nicard I know that 3 years have passed... But could you still provide an example PDF to reproduce this issue, or check if it has been solved meanwhile? Otherwise, can this issue be closed?
