### ISSUE TITLE
Api Doc not found 

### ISSUE THREAD

**Issue by mvillemont** [smalot/pdfparser#171]
Api Doc http://doc.pdfparser.org/namespaces/Smalot.PdfParser.html returns 404 error :(

**Comment by FerhatSaritas** [comment]
The parser is really great and we would like to use the API. Without the doc we would go in blind. Could you fix it, please? I tried to contact you but the contact form throws and error every time :(

**Comment by underdpt** [comment]
We're also looking for the API doc, or at least some examples to get started

**Comment by smalot** [comment]
Sorry for convenience.
Currently you can read this page https://www.pdfparser.org/documentation

**Comment by lighth7015** [comment]
That's not.. very much actual documentation. It's just a handful of code samples. There's no actual documentation on what methods are available in which classes and what return types object methods have.

Soooo? 🤷‍♂
