### ISSUE TITLE
Missing catalog.

### ISSUE THREAD

**Issue by sinan8655** [smalot/pdfparser#173]
Hello,

When i try to parse the pdf file, i can see the warning 'Missing Catalog'.
Could you please tell me the meaning of it?
Also please tell me if this sdk can fix it.

Regards,
Sinan

**Comment by johnrobertporter** [comment]
I come across this error too.

It happens in my case when we try to parse a PDF that was printed to PDF from Microsoft Word on Windows.

**Comment by tim-peterson** [comment]
I might address your issue on this other thread: https://github.com/smalot/pdfparser/issues/32#issuecomment-356353448

**Comment by rubenvanerk** [comment]
Duplicate of #32
