### ISSUE TITLE
How to install and use

### ISSUE THREAD

**Issue by akinuri** [smalot/pdfparser#186]
I've never used Composer, and for the task at hand, I don't plan to. So how do I use PDF Parser without Composer?

I'm guessing `autoload.php` includes the dependencies in some order. Can someone post the content of this file? Or show me the way to use this without using Composer, if possible?

**Comment by akinuri** [comment]
Okay, just to test this, I've downloaded and installed Composer. Used standalone method `composer update`. It outputted a folder named "vendor".

In the documentation page, it says: 

> Now create a new file with this content, in the same folder :

```
<?php
 
// Include 'Composer' autoloader.
include 'vendor/autoload.php';
 
// Your code
// ...
 
?>
```

which doesn't make sense because if this new file is in the same folder (as suggested in the documentation), it'll try to load `autoload.php` that's in "vendor" folder, and it'll fail.

So, instead of `include 'vendor/autoload.php';`, I used `include 'autoload.php';` and I supposed it did whatever it's supposed to do. But when I run this `$parser = new \Smalot\PdfParser\Parser();` I get the following error:

> Uncaught Error: Class 'Smalot\PdfParser\Parser' not found in ...

What am I doing wrong? The documentation of this lib is really poor and isn't helpful. Will somebody, please, help me install and try this lib?

**Comment by akinuri** [comment]
I thought everything I needed was just "vendor" folder, but it seems I still need the "pdfparser-master" folder. I've placed the php file inside the "pdfparser-master" and it worked.

**Comment by Aminat-Okunuga** [comment]
@akinuri Please, I'm quite confused about your solution. I also need to use the smallot pdf parser but I kept getting the class not found error. Please help out.

**Comment by Aminat-Okunuga** [comment]
> @akinuri Please, I'm quite confused about your solution. I also need to use the smallot pdf parser but I kept getting the class not found error. Please help out.

I have gotten it and fixed the issue in my code! 
It's working perfectly now.

**Comment by k00ni** [comment]
In case anyone runs into a similar issue, please check https://github.com/smalot/pdfparser/blob/master/alt_autoload.php-dist. It loads all classes and is an alternative autoloader, in case Composer doesn't work.
