### ISSUE TITLE
not supporting pdf version 1.5 

### ISSUE THREAD

**Issue by computerstar** [smalot/pdfparser#192]
An exception occurs if pdf version is 1.5
Object list not found. Possible secured file. in /pdfparser/src/Smalot/PdfParser/Parser.php on line 112

**Comment by danieljs777** [comment]
When using pdf version 1.5, pdf->getText() returns a blank string

**Comment by smalot** [comment]
Regarding the short description, this issue should be fixed on `master` branch
So I'll close this issue
Don't hesitate to report any drawback
