### ISSUE TITLE
I do not want to use Composer to install, I have a pure PHP project

### ISSUE THREAD

**Issue by tranthaihoang** [smalot/pdfparser#195]
I have a pure PHP project, so I can not use Composer.
So how can I use this library?

**Comment by doganoo** [comment]
Download the project and include all classes separately

**Comment by sbm1990** [comment]
@doganoo will you please elaborate i am also facing the same issue

**Comment by doganoo** [comment]
you need to do something like this:

> include 'src/Smalot/PdfParser/Parser.php';

and ensure that you include all other classes that are required.

But seriously: why are you not using composer? It manages all the includes for you

**Comment by tranthaihoang** [comment]
@doganoo I have linked all the class together, but no results
I can not use Composer since the project is pure PHP built in 2004, I just code purely.
```
require_once ("./PdfParser/PDFObject.php");
require_once ("./PdfParser/Element/ElementArray.php");
require_once ("./PdfParser/Element/ElementBoolean.php");
require_once ("./PdfParser/Element/ElementDate.php");
require_once ("./PdfParser/Element/ElementHexa.php");
require_once ("./PdfParser/Element/ElementName.php");
require_once ("./PdfParser/Element/ElementNull.php");
require_once ("./PdfParser/Element/ElementNumeric.php");
require_once ("./PdfParser/Element/ElementString.php");
require_once ("./PdfParser/Element/ElementXRef.php");
```

**Comment by doganoo** [comment]
you need to include each class in your main script. 

> I can not use Composer since the project is pure PHP 5.2 built in 2004, I just code purely.

you can use composer with older PHP versions as well.

**Comment by CasperBraske** [comment]
The [documentation](https://www.pdfparser.org/documentation) clearly states:

**Prerequisites**

This library requires **PHP 5.3**.

**Comment by smalot** [comment]
not a bug
