### ISSUE TITLE
getText() -> Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by Garrcomm** [smalot/pdfparser#20]
Hi,

Today I received feedback about a failing PDF. It generated a function nesting error.
I wrote a small patch that masked the problem, which is kinda dirty.

I can only upload images to a ticket, so I uploaded the files somewhere else:
The error call stack: http://nederland.ligtin.eu/sthoolen/20140217-pdfparser-error.html
The dirty patch: http://nederland.ligtin.eu/sthoolen/20140217-pdfparser-quickfix.patch
The PDF: http://www.vgogh.nl/documenten/huwelijkse_voorwaarden/files/assets/downloads/publication.pdf

Hopefully this problem can be dealt with in a somewhat more decent way? ;-)

**Comment by aik099** [comment]
I'm having small document (4 pages) and still getting this issue due an infinite recursion where text of an object with `Fm0` contains reference to same object: `Do Fm0` and it never ends.

**Comment by aik099** [comment]
The mentioned recursion was introduced in 51f795121e1864ae0293d1753dd4d03ae9e18d5c commit where support for nested xObjects were introduced.

**Comment by smalot** [comment]
Hi Alexander,

Currently I'm quite busy, so if you find a fix, I'm ok to test it and
release it.

Thanks


*Sébastien MALOT*


Please consider the environment before printing this email.



2015-01-15 15:33 GMT+01:00 Alexander Obuhovich <notifications@github.com>:

**Comment by aik099** [comment]
I've created a fix in #55 . Everybody interested please test on your PDFs if that does solve nesting level problem (for users with xdebug installed) / out of memory problem (for users without xdebug installed).
