### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by simonblatchfordnerdit** [smalot/pdfparser#203]
Hi Smalot

I keep getting an error, 

Fatal error: Class 'Smalot\PdfParser\Parser' not found in /homepages/31/d681928530/htdocs/home/lib/DocumentReader.php on line 125

but the thing is, the files are there in the places, but i cant seem to get it working, is there anything you need from me to help assist you here?

i really appreciate the help in advance, 

Best
Simon

**Comment by doganoo** [comment]
How did you install the library? By composer or manually? 

It seems like that the classes are not loaded. If you have not installed the library by composer you have to include every single file by hand (bad option, do not do it. Use composer instead).

cheers.

**Comment by simonblatchfordnerdit** [comment]
Hey Doganoo

it was my mistake because due to the new update on our database, it may have changed my files in Vendor and the lib section, so what I did was upload the original vendor and lib folder,

**Comment by rubenvanerk** [comment]
This issue can be closed.
