### ISSUE TITLE
parseFile() not working when it's used by a thread

### ISSUE THREAD

**Issue by eToTheEcs** [smalot/pdfparser#204]
I've several threads that parse files concurrently.
any thread gets passed a new instance of a parser, so there are not conflicts.
The problem is that the parseFile() method dies without throwing anything, not even a warning.

**Comment by doganoo** [comment]
I think it throws exceptions, but the error control operator (@) ignores the message. For debugging, I would remove the @ and see what the error is?

https://github.com/smalot/pdfparser/blob/665069a29435a3df90609d7b3c0902fdb427f1d7/src/Smalot/PdfParser/Parser.php#L74

**Comment by doganoo** [comment]
@eToTheEcs you have not installed TCPDF. You have to install it before using.

**Comment by doganoo** [comment]
@eToTheEcs I have created a pull request: https://github.com/smalot/pdfparser/pull/205

lets see when @smalot can merge it :)

**Comment by eToTheEcs** [comment]
@doganoo thanks a lot, I'm struggling quite a lot trying to integrate that library into this one :-)

**Comment by doganoo** [comment]
@eToTheEcs make sure that you include the TCDPF sources before using this library. If they use composer, install it as a requirement?!

**Comment by smalot** [comment]
Merged  ;)
