### ISSUE TITLE
Message: Object list not found. Possible secured file.

### ISSUE THREAD

**Issue by diasisac** [smalot/pdfparser#209]
Ao enviar PDF libraries/pdfparse
![sem titulo](https://user-images.githubusercontent.com/40832333/44408033-e940fc00-a535-11e8-9967-094bbfaadc6d.png)

**Comment by carloshdo** [comment]
Same here, no solution?

**Comment by chumleesockson** [comment]
Same here.

**Comment by murcoder** [comment]
Same here. Is there no solution yet?

**Comment by k00ni** [comment]
I am not aware of any solution.

Could you provide us the PDF which triggers the exception? It must be free to use and will be part of our test suite.

**Comment by k00ni** [comment]
We made some changes recently regarding the `mb_convert_encoding(): Illegal character encoding specified` error (#313). 

I assume you use `0.16.0`? Could you try again with `master` branch?

**Comment by murcoder** [comment]
> We made some changes recently regarding the `mb_convert_encoding(): Illegal character encoding specified` error (#313).
> 
> I assume you use `0.16.0`? Could you try again with `master` branch?

It fixed the issue with version 1.3 PDF. But the original v1.6 PDF file still runs into the error `Object list not found. Possible secured file. `

**Comment by k00ni** [comment]
OK, i will prepare a new release (0.16.1) so at least the encoding problem goes away. For the other one I need a PDF uploaded here so we can make a "failing" test to outline this problem still exist.

**Comment by k00ni** [comment]
FYI, new release `0.16.1`: https://github.com/smalot/pdfparser/releases/tag/0.16.1

**Comment by ackwo** [comment]
Got the same error. Object list not found (0.16.1)

[SLD-Paste_deutsch_03_2017.pdf](https://github.com/smalot/pdfparser/files/4852411/SLD-Paste_deutsch_03_2017.pdf)

**Comment by andreescocard** [comment]
Same problem.
