### ISSUE TITLE
Broken on PHP 7.3: "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by miklcct** [smalot/pdfparser#217]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? {"userId":"NqntwzG58vk","exception":"[object] (ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at vendor/smalot/pdfparser/src/Smalot/PdfParser/PDFObject.php:329)

**Comment by guitaristtom** [comment]
I'm also getting the same issue with my project.

**Comment by heldchen** [comment]
getting also these warning, but on some other lines (v0.13.2): `PDFObject.php:341` & `PDFObject.php:510`

**Comment by didix16** [comment]
I'm having the same issue. Any fix for that?

**Comment by k00ni** [comment]
Do you run PHP 7.3? Can you provide an example PDF (free to use and without obligations) and the code snippet you use?

**Comment by didix16** [comment]
Hi @k00ni . Sorry it was a mistake of mine. Our cache system seems lied to me. I wanted to install 0.17.x version but the app seems was using the old 0.12.x even after updating...

The code is working now. Sorry for bother you and thanks anyway.

**Comment by k00ni** [comment]
No problem, I am glad its working!
