### ISSUE TITLE
add 'test' or specific word to all lines

### ISSUE THREAD

**Issue by udaykhachar** [smalot/pdfparser#22]
how add specific word to all line..

for ex. i have 3 line pdf 
1.this is first
this is second
this is third
 and i will convert it to
this is first test
this is second test
this is third test

**Comment by Connum** [comment]
I would say this is out of scope, not a functionality that the library should provide. 

I don't suppose help is needed after more than 6 years, but anyway, this is what you could do:
```php
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile($file);
$pages = $pdf->getPages();

foreach ($pages as $index => $page) {
    if (null === $page) {
        continue;
    }
    
    $pageLines = $page->getTextArray();
    foreach($pageLines as $line) {
        print $line . ' test<br>';
    }
}
```

I'm in favour of this issue being closed, so we can clear the stack a bit.

**Comment by Connum** [comment]
_(Pinging @k00ni, as I'm not sure whether you'll be notified automatically)_

**Comment by k00ni** [comment]
> ... but this is disconnected from pdfparser library.

I follow the lead of @smalot and @Connum and close this. Also a workaround was provided.

> (Pinging @k00ni, as I'm not sure whether you'll be notified automatically)

I will get notified every time a new post and PR is made, but thanks anyway. :+1:
