### ISSUE TITLE
Read pdf after post

### ISSUE THREAD

**Issue by jafinland** [smalot/pdfparser#220]
Hello, I'm trying to create similar system like https://pdfparser.org/demo where PDF is parsed after submit. Any hints for that, $pdf = $parser->parseFile($_FILES['pdfupload']); seems not working and returns empty result.

**Comment by jafinland** [comment]
Actually it worked, after PDF upload to server!

**Comment by joncojonathan** [comment]
@smalot this issue can be closed as it's working.

**Comment by rubenvanerk** [comment]
This issue can be closed.
