### ISSUE TITLE
Demo page extracts only first page of 4 pages pdf

### ISSUE THREAD

**Issue by andrealuciani** [smalot/pdfparser#23]
I repeatedly encounter an issue with 4 pages pdf (here an example available on this site:  http://dominoweb.comune.fi.it/OdeProduzione/FIODEWeb2.nsf/AttiWEB/813329777442499EC1257C7500015561/$File/2014_M_00794.pdf).

demo page extracts text only from first page. the others are left unexpectedly blank.

Am I doing something wrong ?

Thank you,
regards.
Andrea

**Comment by pranay2206** [comment]
what is the code if the pdf file is runtime uploading file?

**Comment by Reqrefusion** [comment]
I tried the relevant document in the demo. And it shows all three pages neatly.

**Comment by k00ni** [comment]
> I tried the relevant document in the demo. And it shows all three pages neatly.

The author of this issue talked about a PDF with 4 pages. Does it mean, that you see all of them with the current version (0.16.2)?

**Comment by Connum** [comment]
Seems to work for me as well... Mentioned document only has 3 pages, all of them are extracted fine with the current version...
+1 for closing this issue!

**Comment by k00ni** [comment]
Thank you @Connum for checking it.
