### ISSUE TITLE
Invalid type: ">>".

### ISSUE THREAD

**Issue by chris087** [smalot/pdfparser#233]
With a lot of PDFs gettings this error. When open the PDF and resave it (with Adobe Acrobat), the problem is gone..

**Comment by flowerpower11** [comment]
Im getting the following sometimes [" "," "," "," "," "," "," "," "," "]
Is there a solution?

**Comment by joncojonathan** [comment]
Are there any publicly available PDFs that exhibit this behaviour?  I've not seen that here but can test some in my project if that's useful?

**Comment by flowerpower11** [comment]
Unfortunatelly I cant share the files. We've found when we use a MAC to the same file to pdf it is working. So the issue is with the files, thats sure thing.
Are there restrictions?

**Comment by chris087** [comment]
Fix:

Add to Parser.php:

    protected function parseHeaderElement($type, $value, $document)
    {
        switch ($type) {
            case '<<':
                return $this->parseHeader($value, $document);
                
              
            **case '>>':
                return $this->parseHeader($value, $document);**

**Comment by smalot** [comment]
@chris087 : I made a patch, can you check it ?

https://github.com/smalot/pdfparser/tree/smalot-patch-233

**Comment by k00ni** [comment]
@smalot: You made a branch with a patch. Is it worth merging or can we remove the branch?

**Comment by j0k3r** [comment]
The branch has been merged (https://github.com/smalot/pdfparser/commit/c8113a2d632de8111b502f65c98f3444bb056619), I guess we can remove it

**Comment by k00ni** [comment]
Thank you.
