### ISSUE TITLE
Online demo parses just fine but fails locally on /ASCII85Decode /FlateDecode

### ISSUE THREAD

**Issue by warul** [smalot/pdfparser#240]
i have multiple pdfs that parse fine with your online demo but fail locally on a machine running php 7.3.1 and pdfparser 0.14.

stream example:
11 0 obj
<<
/Length 558
/Filter [/ASCII85Decode /FlateDecode]
>>
stream
Gar&<_/?#%'YHrY5J1KQ=96F]>:DmRTh%31[VBt]Wu_PZ6qG9>6Orqh"j^s`otoqG1ZRHI0.Q\WhK:VCYC:-p4O^9NXljE.pkJ%SkK[p'M5%Fok0GeJe(<W''.s'uFdfku]@0$W*CXnimPOekh*&3aOma`FnLaX`Sa#Q\EEMMDAK3qEB/`a_Gtor`<i9<tpq,s^U>drQ6iUX>J(a[>*LRTW&gV1GQD_!*f[oQ8gW_@2F4sVo^>6#/^[I'DGktsO
Q#3"\rm@GsCDFlm![n$en.<C4W1F&=&X7fY:`r;Y!^K?9R:ZF<^jrCmVVttuXC8!F'8tR0/gk$]7C#V\&26PLELoT7Ma`OpcZ$-%kn,OUAeGZ%)%Ofh!#8`o#YK21!u*-f+Z+9FAf<[h,f;nPT[=f4%=sFk:5Lj^UEEAe;_T^J'&mZ:'a]G]'jN5^^q,d(J7@J?8-m;%>R-W#9G<d"*_Ko'NpmQO>.7N^:;l6#bjZ."giOn;?sn_h=KLDtj1W
.Soc])^]8]=%nU;@H0T]]uesY_AhhH:o`h8OAIpm*]nc~>
endstream

**Comment by k00ni** [comment]
Can you upload the PDF here so we can use it to reproduce the error? It must be free to use, because we will use it in the test suite.

**Comment by warul** [comment]
> 
> 
> Can you upload the PDF here so we can use it to reproduce the error? It must be free to use, because we will use it in the test suite.

Unfortunately not. it has been too long

**Comment by k00ni** [comment]
Ok, then closed.
