### ISSUE TITLE
Encoding Error?

### ISSUE THREAD

**Issue by garyr87** [smalot/pdfparser#241]
I'm having a problem when trying to read a Bank Statement PDF.  It appears as though its not picking up something.  Below is what is being returned from the getText() function.  Any assistance would be appreciated.  I've tried converting the text to different types however it still stays a black triangle with a ? mark in it.
 
@���������������	
2 4	Page	of @���������������	
12417220202000000062	
3 4	Page	of @���������������	
4 4	Page	of	
March 01, 2019	through	March 29, 2019	
Account Number:	
This Page Intentionally Left

Thanks much!

**Comment by davispuh** [comment]
Try #257 PR maybe it works better.

**Comment by k00ni** [comment]
@garyr87 , did you try it with #257? 

Can you upload the PDF here so we can use it to reproduce the error? It must be free to use, because we will use it in the test suite.

**Comment by Connum** [comment]
With no sample PDF provided after a ping almost 3 months ago after almost 1.5 years, and a seemingly inactive account... I'd suggest closing this issue.
