### ISSUE TITLE
issue in page->getText() function

### ISSUE THREAD

**Issue by satheshk385** [smalot/pdfparser#250]
Warning: mb_convert_encoding(): Illegal character encoding specified in /home/ubuntu/workspace/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php on line 514 Call Stack: 0.0004 234288 1. {main}() /home/ubuntu/workspace/index.php:0 0.0005 234736 2. require('/home/ubuntu/workspace/wp-blog-header.php') /home/ubuntu/workspace/index.php:17 0.0005 235672 3. require_once('/home/ubuntu/workspace/wp-load.php') /home/ubuntu/workspace/wp-blog-header.php:13 0.0006 236432 4.

**Comment by GiacomoK** [comment]
same here, someone can help pls?

**Comment by k00ni** [comment]
Can you try again with our latest release `0.16.1`?

**Comment by Connum** [comment]
This was fixed in cb1299bc78909f729356b584e59f93da2db45323, which is part of the currently pending PR #349.
