### ISSUE TITLE
TCPDF version used contains deprecated each() calls for PHP 7.2

### ISSUE THREAD

**Issue by Skullywag** [smalot/pdfparser#251]
The version of tcpdf that the composer.json file is set to use contains "tecnickcom/tcpdf": "~6.0" this will not pick up the 6.2 version where the while loop containing the deprecated each() calls  has been changed to a foreach().

Line 12579 of 6.0 tcpdf.php "while (list($key, $val) = each($prop)) {"
Line 12586 of 6.2 tcpdf.php "foreach($prop as $key => $val) {"

**Comment by Zakerius** [comment]
Did you tried to update smalot/pdfparser with dependencies:
`composer update smalot/pdfparser --with-dependencies`
I just did and it upgraded me tecnickcom/tcpdf to version 6.3.2

~ seems to work similar to ^ - https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
