### ISSUE TITLE
getFontSpaceLimit - class variable?

### ISSUE THREAD

**Issue by nickano** [smalot/pdfparser#259]
Is there any chance you could make this a configurable class variable?  Dirtyish quick way would be to set it statically on the Font object before you create a Parser instance and away we go?

At the moment we have to manually change the file every time we update the package in composer and we can't really extend the classes efficiently to fix it that way.

**Comment by nickano** [comment]
e.g. 

`
/**
 * Class Font
 *
 * @package Smalot\PdfParser
 */
class Font extends PDFObject
{

    //////////
    // snip //
    //////////

    /**
     * @var integer
     */
    public static $font_space = -50;

    //////////
    // snip //
    //////////

    /**
     * @return int
     */
    protected function getFontSpaceLimit()
    {
        return Font::$font_space;
    }

    /**
     * @param integer $font_space
     */
    public static function setFontSpaceLimit($font_space)
    {
        Font::$font_space = $font_space;
    }

    //////////
    // snip //
    //////////
}
`

Then setup and call...

`\Smalot\PdfParser\Font::setFontSpaceLimit(-100);

$oParser = new \Smalot\PdfParser\Parser();
$oPDF = $oParser->parseFile($sFile2Convert);
$sRawFile = $oPDF->getText();
`

**Comment by ilia2s** [comment]
```

$config = new \Smalot\PdfParser\Config();
$config->setFontSpaceLimit(-60);
$config->setRetainImageContent(false);
$config->setHorizontalOffset('');

$parser = new \Smalot\PdfParser\Parser([], $config);
$pdf    = $parser->parseFile('document.pdf');
 
$text = $pdf->getText();


```
