### ISSUE TITLE
compressed text fail

### ISSUE THREAD

**Issue by WilsonPedroso** [smalot/pdfparser#261]
if PDF has a compressed string, extraction fail.
A simple modification resolves.

    public function getSectionsText($content)
    {
//var_dump($content);

		//check if compressed
		if( $content[0]=='x') //part of compression signature
		{
			$un = @gzuncompress($content);
			if( $un !== FALSE )
			{	
				$content = $un;
			}
		}
		
		
        $sections    = array();
        $content     = ' ' . $content . ' ';
        $textCleaned = $this->cleanContent($content, '_');

**Comment by JanPetterMG** [comment]
Bump!
I'm having issues with some PDF documents, reporting no page contents. The above code fixes this issue.

**Comment by Connum** [comment]
@WilsonPedroso @JanPetterMG could you provide a sample PDF that we could use for testing (not subject to copyright or privacy issues)? I would be willing to write the tests and make a PR!

**Comment by WilsonPedroso** [comment]
> 
> 
> @WilsonPedroso @JanPetterMG could you provide a sample PDF that we could use for testing (not subject to copyright or privacy issues)? I would be willing to write the tests and make a PR!
> 
> _Note to myself or anyone going to work on this:_
> We should make use of `decodeFilter('FlateDecode', ...)`, which already provides `gzuncompress()` internally and handles possible errors.

Sorry @Connum , i only have  PDF with privacy issues.
To try to help, below is a content compressed part fragment.

stream
xœ½]ë—dµqÿžsü?Lˆ!8„Ao]Ìöc
‰1`H0añÂ:† Ž¿åoOÕ¯¤{¥Û­ûhŒwÎN÷ôÜª’ªJõRIs÷íÏþîNßý}WòýÞù»¿Ð«ð6jwoýñþ^«;úAû»ïžÑïKÿß£ÿklL÷ÃˆÀZ}¶bp61m›Ü½"ÚÚÞ;zºC  õ‘Gí¾÷~¼³ê>©»-ÃhB@?Ù°I‘§-ø–˜gµo7#gùíô}¤½Þ

HEX VIEW
stream
0D 0A 78 9c bd 5d eb 97 64 b5 71 ff 9e 73 fc 3f 4c 88 21 38 84 41 6f 5d 11 0c cc f6 63 0d 89 31 60 48 30 61 8f f1 c2 3a 86 20 0e 04 8e bf e5 6f 4f d5 af a4 7b a5 db ad fb 68 8c 77 ce 4e f7 f4 dc aa 92 aa 4a f5 52 49 73 f7 ed cf fe ee 4e df fd 17 7d 57 f2 fd de f9 bb bf d0 1b ab f0 36 6a 77 6f fd 9d f1  

I use version 2017-01-03, and this change was done in PDFObject.php file.

**Comment by Connum** [comment]
@WilsonPedroso unfortunately, I was not able to inject this ina PDF for testing...
Did you simply call `$pdf->getText()`, or some other code?
Were there any error messages? Or was the uncompressed stream simply visible in the otherwise decoded text?

I'm still trying to find any PDF file to reproduce this...

**Comment by JanPetterMG** [comment]
@Connum sorry, I'm not able to share any PDFs at the moment, due to privacy issues.
If I'll come across something worry-free, I'll submit it. 👍

**Comment by k00ni** [comment]
Hi @JanPetterMG, if you can please: upload a PDF here on Github, which we can also use free of charge and include in our test environment.

**Comment by pcdrivers** [comment]
I have and example pdf file compressed who pdfparser cannot read.
[fichero1.pdf](https://github.com/smalot/pdfparser/files/6204493/fichero1.pdf)

**Comment by k00ni** [comment]
Is it free of charge and can we use it in our test environment?

**Comment by GreyWyvern** [comment]
The sample file [fichero1.pdf](https://github.com/smalot/pdfparser/files/6204493/fichero1.pdf) is working in the current v2.7.0 release. There are some spacing issues, but text is successfully extracted.
