### ISSUE TITLE
generated text contains programming code

### ISSUE THREAD

**Issue by kailasvnair49** [smalot/pdfparser#263]
See below screenshot
http://prntscr.com/pqieqr

sample PDF link: 
https://www.accenture.com/_acnmedia/pdf-42/Accenture-M6-Monetizing-Big-Data.pdf

**Comment by rubenvanerk** [comment]
This piece of code:
```
struct group_info init_groups = { .usage = ATOMIC_INIT(2) };
struct group_info *groups_alloc(int gidsetsize){
    struct group_info *group_info;
    int nblocks;
    int i;
    nblocks = (gidsetsize + NGROUPS_PER_BLOCK - 1) / NGROUPS_PER_BLOCK
;
    /* Make sure we always allocate at least one indirect block pointer */
    nblocks = nblocks ? : 1;
    group_info = kmalloc(sizeof(*group_info) + nblocks*sizeof(gid_t *), GFP_USER);
    if (!group_info)
        return NULL;
    group_info->ngroups = gidsetsize;
    group_info->nblocks = nblocks;
    atomic_set(&group_info->usage, 1);
    if (gidsetsize <= NGROUPS_SMALL)
        group_info 
struct group_info init_groups = { .usage = ATOMIC_INIT(2) };
struct group_info *groups_alloc(int gidsetsize){
    struct group_info *group_info;
    int nblocks;
    int i;
    nblocks = (gidsetsize + NGROUPS_PER_BLOCK - 1) / NGROUPS_PER_BLOCK
;
```

Is repeated between the actual text of the pdf which gets parsed fine. This code is used on [hackertyper.com](http://hackertyper.com/). So I assume this is a problem with the pdf and not with pdfparser.

**Comment by Connum** [comment]
You can actually search for that "code" in the PDF file and it will mark some text that is used in kind of a watermark-style light overlay on the background:
![grafik](https://user-images.githubusercontent.com/13076806/93785383-5308c400-fc2e-11ea-9e2b-a74ead46e615.png)

The library can't decide whether text content is just decorative or "real" text (well, maybe it could based on contrast, but that would have to be a setting to turn on or off, optimally with a configurable contrast setting - but that seems way out of scope for a parsing library). So I think this is not a bug and should be closed.

**Comment by kailasvnair49** [comment]
Thanks @Connum @rubenvanerk

**Comment by k00ni** [comment]
Thank you for checking it.
