### ISSUE TITLE
Library crashes when parsing some 1.3 PDF files

### ISSUE THREAD

**Issue by alexandermak95** [smalot/pdfparser#264]
I am having problems with your library because it crashes when trying to parse some PDF files with 1.3 version. It crashes even when i try to upload it to your demo site.

1754-Rosn.pdf

File info
http://prnt.sc/q0htx3

**Comment by rubenvanerk** [comment]
Can you share the PDF?

**Comment by k00ni** [comment]
... and the error message would be helpful as well.

**Comment by k00ni** [comment]
If there is no feedback from the author I will close this issue soon due to lack of information. We reproduce this bug.
