### ISSUE TITLE
How can I view the pdf content on a web page as displayed in your demo?

### ISSUE THREAD

**Issue by matteocol** [smalot/pdfparser#265]
Congratulations on making this library.
How can I view the pdf content on a web page as displayed in your demo?
With this instruction I have only one string: $ text = $ pdf-> getText ()
Thank you in advance

**Comment by rubenvanerk** [comment]
The demo replaced the line breaks (`\n`) with `<br>`. This is how you could do that: `str_replace("\n", "<br>", $text)`.

Wrapping `$text` in a `<pre>` block would also work.

**Comment by k00ni** [comment]
@matteocol does this solves your problem?

**Comment by asokr** [comment]
Hello, I have the same question, can you please help me.
This is demo result
![demo](https://user-images.githubusercontent.com/47985432/84562152-ec385c80-ad5a-11ea-84c2-67badbe2760f.JPG)
And the same file on localhost or linux hosting
![my](https://user-images.githubusercontent.com/47985432/84562161-fa867880-ad5a-11ea-80f9-3ce7339d3f3d.JPG)
Can you tell me how to configure the server/script to get demo result?

**Comment by oneklema** [comment]
I was searching for a solution to this problem, and ran across this thread. I see that someone asked if this was a solution, and I just wanted to answer that the solution presented by rubenvanerk works well. Just replace the /n with <br> and the output is formatted like the demo. Thank you.

**Comment by k00ni** [comment]
OK as far as I can tell the original issue is solved, thanks for the feedback @oneklema.

@asokr, if you problem still persist please open a new issue.

**Comment by oneklema** [comment]
yes, thank you.

And just FYI, when using the contact form on you PDF Parser web site, i 
responds with an error when the form is submitted.

  - Andy

------ Original Message ------

**Comment by k00ni** [comment]
OK.

/CC @smalot

**Comment by pedrofeliz90** [comment]
> 
> 
> The demo replaced the line breaks (`\n`) with `<br>`. This is how you could do that: `str_replace("\n", "<br>", $text)`.
> 
> Wrapping `$text` in a `<pre>` block would also work.

Where do I make this change?

the output of the text after analyzing the PDF, is ignoring all line breaks and placing the text on only one line.
Do you know how to solve this?

**Comment by k00ni** [comment]
> $text = $pdf-> getText ()

If I understood it correctly, `$text` is the result of `Document::getText()`. So you could use:

```php
$text = $pdf-> getText();
$text = str_replace("\n", "<br>", $text);
// $text now contains a <br> for each \n

// your code, like
echo $text;
// or
echo '<pre>'.$text.'</pre>';
```

**Comment by pedrofeliz90** [comment]
perfect, that's right, it worked perfectly, thanks!!
