### ISSUE TITLE
Fatal Memory Allocation Error with Arabic and Urdu Character PDFs

### ISSUE THREAD

**Issue by githubuser584** [smalot/pdfparser#266]
I am experiencing persistent fatal errors when parsing PDF files that contain Arabic or Urdu-language text.  The error is almost always exactly the same:

Fatal error: Possible integer overflow in memory allocation (0 * 36 + 32) in /Users/code/src/Smalot/PdfParser/Font.php on line 199

**Comment by githubuser584** [comment]
I meant to add, this is the section of Font.php that seems to be having the issue:

                        for ($char = $char_from; $char <= $char_to; $char++) {
                            $this->table[$char] = self::uchr($char - $char_from + $offset);
                        }

**Comment by githubuser584** [comment]
I have temporarily addressed this by creating an excessive integer value limit checker for the $char variable and also added a timeout value...

for ($char = $char_from; $char <= $char_to; $char++) 
{
     if((PHP_INT_MAX > $char + 2) && ($timeoutValue > strtotime('now')))
     {
          ....
     }
     else
     {
          echo 'this is taking too long and/or would have crashed the parser so we end the process prematurely';
     }
}

**Comment by k00ni** [comment]
Hi @githubuser584, can you provide a PDF file which leads to this error?

**Comment by k00ni** [comment]
Closed due to inactivity. Please reopen, if you have further info or a working example which triggers the error.
