### ISSUE TITLE
Split pages into files and save it

### ISSUE THREAD

**Issue by dhcmega** [smalot/pdfparser#268]
Hi!
Is it possible to split a pdf file with multiple pages into files?
Something like this:
```
<?php
 
// Include Composer autoloader if not already done.
include 'vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('document.pdf');
 
// Retrieve all pages from the pdf file.
$pages  = $pdf->getPages();
 
// Loop over each page to extract text.
foreach ($pages as $page) {
    $page->storeAs($path_to_location_and_file_name);
}
 
?>
```

Thanks!

**Comment by BlackRhinoMedia** [comment]
Has anyone successfully done this?

**Comment by dhcmega** [comment]
I've used PDF Merger, which allows you to add a single page of a PDF to another PDF.
So, I cycle over the pdf to split, page by page.
And FPDI to get the array of page numbers.
I then inside the loop, generate a new empty pdf and then i merge the single page to it.
After the whole thing i end up with as many pdfs as pages where on the big one that i cycle

**Comment by k00ni** [comment]
PDFParser library focuses solely on parsing PDF files. Generating and saving them is out of scope. 

You should try https://github.com/tecnickcom/TCPDF and others, which might provide such features.
