### ISSUE TITLE
Sorting lines

### ISSUE THREAD

**Issue by uldisn** [smalot/pdfparser#27]
Hi!
I implement line sorting by Y coordinates. Changes can see:
https://github.com/uldisn/pdfparser.git in obeject->getText(). All rows save in array, then sort by Y coordinate.

I have some questions:
1) in obeject->getText()  for command Td i comment out horizontal offset. In My code 282 row. This offset create extra spaces before each no latin character in follow pdf: http://www.tiesas.lv/files/AL/11_2007/12_11_2007/AL_1211_apg_AA43-2105-07_15.pdf
2) How You debugging? I created some echo strings in obeject->getText() for it.

**Comment by k00ni** [comment]
Hi, thank you for the effort. If you still interested in this feature, please create a PR and we can discuss there.
