### ISSUE TITLE
Exception: Missing catalog

### ISSUE THREAD

**Issue by StudPro** [smalot/pdfparser#272]
Hi,
i tried to parse a pdf born from "word openoffice" but return an exception with a "Missing catalog". If hide error the process return a empty string. 

I use the last version from composer

File
pdfparser/src/Smalot/PdfParser/Document.php 248

Solution?

Thank's a lot

**Comment by styler2go** [comment]
Also got this problem. Any ideas?

**Comment by j0k3r** [comment]
Could you provide a PDF sample to reproduce the bug?

**Comment by rubenvanerk** [comment]
Duplicate of #32
