### ISSUE TITLE
Usage without composer?

### ISSUE THREAD

**Issue by katsar0v** [smalot/pdfparser#279]
Hi, can this parser be used without composer? I would like to read pdf files on a server without composer and without root access (just clean php). Is this possible?

**Comment by j0k3r** [comment]
Composer is **the** PHP tool to ease maintainer of project to integrate library from outside. We’ll never remove it.

On the other hand, you can install the lib locally on your desktop, install the library using Composer, code your functionality and then create a zip with everything and put it on your server. Ensure your local env have the same PHP configuration as the server.
