### ISSUE TITLE
endless loop at $xobject->getText($page);

### ISSUE THREAD

**Issue by dittertp** [smalot/pdfparser#28]
Hi,

while playing around with your library i found a .pdf that couse a endless loop in Object.php Line 360. 

you can download the pdf here:
http://www.techdivision.com/fileadmin/images/content/jobs/stellenangebot-2-PHP_Web_Entwickler.pdf

Thanks!

**Comment by aik099** [comment]
I've created a fix in #55 . Everybody interested please test on your PDFs if that does solve nesting level problem (for users with xdebug installed) / out of memory problem (for users without xdebug installed).

**Comment by rubenvanerk** [comment]
@k00ni @j0k3r #55 was merged, so this issue can be closed.
