### ISSUE TITLE
Read File from FTP Server

### ISSUE THREAD

**Issue by anugrahdputra** [smalot/pdfparser#287]
how to parseFile for read files on a different FTP server?

**Comment by k00ni** [comment]
Hi, if i understand you correctly, it would already help, if you download the file first and parse it aftwards. Or do you expect file downloads from the pdfparser?

**Comment by anugrahdputra** [comment]
That's true, but I need it every time I upload a PDF to read the number of pages of the file and read the number of other pdf files stored on the FTP server. There are hundreds of thousands of files if I have to download them manually first. Are there other solutions?

**Comment by smalot** [comment]
@k00ni is right.
You need to separate file download from file parsing.
It is one of the SOLID concept. "S" is for "Single-responsibility principle" which says:
"A class should only have a single responsibility, that is, only changes to one part of the software's specification should be able to affect the specification of the class."

In other words, use any library for the transport and use PdfParser to extract content.

cf: https://en.wikipedia.org/wiki/SOLID
