### ISSUE TITLE
Does PDFParser support PDF version 2.0?

### ISSUE THREAD

**Issue by vecca26** [smalot/pdfparser#293]
Will it work on higher version of pdf ???

**Comment by j0k3r** [comment]
What pdf version are you talking about ?

**Comment by vecca26** [comment]
if i upload higher version pdf file i will still be able to convert the text from it??

**Comment by j0k3r** [comment]
Define: ** higher version pdf**.

**Comment by vecca26** [comment]
2.0 pdf version

**Comment by vecca26** [comment]
i am not able to upload the PFD whichis not in the current directory?

**Comment by vecca26** [comment]
Warning: file_get_contents(caste certificate.pdf): failed to open stream: No such file or directory in C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Parser.php on line 70

Fatal error: Uncaught Exception: TCPDF_PARSER ERROR: Empty PDF data. in C:\xampp\htdocs\readpdf\vendor\tecnickcom\tcpdf\tcpdf_parser.php:807 Stack trace: #0 C:\xampp\htdocs\readpdf\vendor\tecnickcom\tcpdf\tcpdf_parser.php(104): TCPDF_PARSER->Error('Empty PDF data.') #1 C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Parser.php(93): TCPDF_PARSER->__construct('') #2 C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Parser.php(81): Smalot\PdfParser\Parser->parseContent(false) #3 C:\xampp\htdocs\readpdf\file.php(33): Smalot\PdfParser\Parser->parseFile('caste certifica...') #4 {main} thrown in C:\xampp\htdocs\readpdf\vendor\tecnickcom\tcpdf\tcpdf_parser.php on line 807

**Comment by rubenvanerk** [comment]
Could you share the pdf?

**Comment by vecca26** [comment]
> Could you share the pdf?

**Comment by vecca26** [comment]
[Mohit-Rouniyar-Data-Analyst.pdf](https://github.com/smalot/pdfparser/files/4712281/Mohit-Rouniyar-Data-Analyst.pdf)

**Comment by vecca26** [comment]
Uncaught Exception: Missing catalog. in C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Document.php:248 Stack trace: #0 C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Document.php(259): Smalot\PdfParser\Document->getPages() #1 C:\xampp\htdocs\readpdf\file.php(43): Smalot\PdfParser\Document->getText() #2 {main} thrown in C:\xampp\htdocs\readpdf\vendor\smalot\pdfparser\src\Smalot\PdfParser\Document.php on line 248

**Comment by rubenvanerk** [comment]
Can confirm I'm getting the same error.
I was able to fix this issue for this pdf with `qpdf`. I executed the following command: `qpdf Mohit-Rouniyar-Data-Analyst.pdf Mohit-Rouniyar-Data-Analyst-Fixed.pdf`

Here is your file, fixed: [Mohit-Rouniyar-Data-Analyst-Fixed.pdf](Mohit-Rouniyar-Data-Analyst-Fixed.pdf)

**Comment by vecca26** [comment]
getting error failed to open the fixed pdf

**Comment by rubenvanerk** [comment]
Looks like you're not referencing the file correctly? Can you share your code and directory structure?

**Comment by vecca26** [comment]
<?php




?>
<center><h1> PDF TO TEXT CONVERSION</h1>

	<form method='POST' enctype='multipart/form-data'>
<input type="file" name="fileToUpload" id="fileToUpload" required>
<input type='submit' name='submit'></form>
</center>


<?php


if(isset($_POST['submit']))
	{

				
$hold =$_FILES["fileToUpload"]["tmp_name"];


 
// Include Composer autoloader if not already done.
include 'vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile($hold);
 

$text = $pdf->getText();


echo'<center><div style="width:400px;height:200px;"><div id="top"><p>Conversion of PDF To Text </p></div><div id="inside">'. $text.'</div>';
 


}

?>
<style>
#inside{background-color:#caebf7;
border: solid black 1px;
}	
#top{background-color:#4343ab;
border: solid black 1px;}
#top p{
	color:white;
	font-size:16px;
}
</style>

**Comment by rubenvanerk** [comment]
How do you instantiate `$pdf` exactly?

**Comment by vecca26** [comment]
<form method='POST' enctype='multipart/form-data'>
<input type="file" name="fileToUpload" id="fileToUpload" required>
<input type='submit' name='submit'>
<?php


if(isset($_POST['submit']))
	{

				
$hold =$_FILES["fileToUpload"]["tmp_name"];


 
// Include Composer autoloader if not already done.
include 'vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile($hold);
 

$text = $pdf->getText();


echo'<center><div style="width:400px;height:200px;"><div id="top"><p>Conversion of PDF To Text </p></div><div id="inside">'. $text.'</div>';
 }
?>

**Comment by k00ni** [comment]
What was fixed using `qpdf`?

**Comment by rubenvanerk** [comment]
@k00ni I don't know exactly but I use `qpdf` whenever I get a weird error like this or when the file is secured. Sometimes it helps, in this case it did.

**Comment by vecca26** [comment]
> @k00ni I don't know exactly but I use `qpdf` whenever I get a weird error like this or when the file is secured. Sometimes it helps, in this case it did.

how do I use it with my code?

**Comment by rubenvanerk** [comment]
@vecca26 you can use it on the command line like this: `qpdf broken.pdf fixed.pdf`. As I said I already did this for you: https://github.com/smalot/pdfparser/issues/Mohit-Rouniyar-Data-Analyst-Fixed.pdf
I can't replicate the error you we're getting after this though. Maybe check if the file is actually uploaded? What's in your `$hold` variable?

**Comment by k00ni** [comment]
Do you know if there is a difference-tool for PDFs?

**Comment by vecca26** [comment]
$hold Contains temp location of the pdf

**Comment by vecca26** [comment]
> Do you know if there is a difference-tool for PDFs?

no I  am unaware of that

**Comment by rubenvanerk** [comment]
@vecca26 I had no problems using your code. I think the problem was in the pdf I uploaded. I'm trying this again: 
[Mohit-Rouniyar-Data-Analyst.qpdf.pdf](https://github.com/smalot/pdfparser/files/4725421/Mohit-Rouniyar-Data-Analyst.qpdf.pdf)
You can also try to fix your file yourself using `qpdf` as I mentioned above.

**Comment by k00ni** [comment]
OK, i am closing this now.

It seems original question (*Does PDFParser support PDF version 2.0?*) can not be answered at this point.

About the "other" problem. I think @rubenvanerk provided a working solution. Discussion can still continue here, but only open if it is about the PDF version.
