### ISSUE TITLE
Exception : TCPDF_PARSER ERROR: Empty PDF data

### ISSUE THREAD

**Issue by kiwad** [smalot/pdfparser#3]
I load index.php, i use the form to upload a PDF and it results in this error :

Exception : TCPDF_PARSER ERROR: Empty PDF data. in TCPDF_PARSER->Error() (ligne 790  /pdfparser/vendor/tecnick.com/tcpdf/tcpdf_parser.php).

Version = v0.9.8

**Comment by macojaune** [comment]
Hi ! I have the same error could you explain how you solved it ? 

Where was the permissions issue ?

**Comment by Anan7Codes** [comment]
Uhm if anybody is here, I have the same error. It works fine for me in my directory but when I try to extract the PDFs from a network eg( \\100.100.100.100\My Bills) it gives me this error -> Fatal error: Uncaught Exception: TCPDF_PARSER ERROR: Empty PDF data.

**Comment by anujprimefocus** [comment]
same issue not able to figure out the issue

**Comment by colelloa** [comment]
same issue - please reopen

**Comment by smalot** [comment]
Which version are you using ?
Can you some sample code ?
