### ISSUE TITLE
Object list not found. Possible secured file.

### ISSUE THREAD

**Issue by johannesjo** [smalot/pdfparser#30]
When trying to encode my pdf i get the following error 

```
Object list not found. Possible secured file.
```

What does this mean?

If I use pdftotext from the command line, I'm able to output the text of my test-file just fine.

**Comment by sendyputra** [comment]
i have same issue here
<pre>
Fatal error: Uncaught exception 'Exception' with message 'Object list not found. Possible secured file.' in /home/user/public_html/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php:95 
Stack trace: 
#0 /home/user/public_html/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php(74): Smalot\PdfParser\Parser->parseContent('%PDF-1.5\n%\xE4\xF0\xED\xF8\n...') 
#1 /home/user/public_html/upload/pdfparser/index.php(10): Smalot\PdfParser\Parser->parseFile('/home/user/...') 
#2 {main} thrown in /home/user/public_html/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 95
</pre>

try this file http://samples.leanpub.com/serversforhackers-sample.pdf or mirror here https://drive.google.com/file/d/0B7Fp0f32TQX3YzlaVDhPRWZweXc/view?usp=sharing

**Comment by greg2fs** [comment]
is there a solution now ?

**Comment by shubaivan** [comment]
I have some problem 

    `object list not found. Possible secure file.`

and version bundle 

    `"smalot/pdfparser": "*",`

Who knows when fix this problem?

**Comment by ikkez** [comment]
same problem here

**Comment by unicod3** [comment]
Is there any update on this?

**Comment by diasisac** [comment]
Object list not found. Possible secured file.
![sem titulo](https://user-images.githubusercontent.com/40832333/44408428-bcd9af80-a536-11e8-98d1-1eef58c00500.png)

**Comment by ikkez** [comment]
I solved my issue here by simply opening the pdf in a reader and saving a copy of the pdf file... then the copy was fine for the pdfparser.

**Comment by seliquity** [comment]
@sendyputra's test file at least doesn't load due to a parsing bug in TCPDF (not sure if this also applies to the original poster's issue). TCPDF assumes the XRef stream has some attributes which are actually optional, and fails if they're missing.

I opened a PR upstream with a fix https://github.com/tecnickcom/TCPDF/pull/104

**Comment by paaaaaaaaaa** [comment]
Same problem. Looks like TCPDF is deprecated and a new library was created: https://github.com/tecnickcom/tc-lib-pdf-parser

**Comment by Tudhaliyas** [comment]
> 
> 
> @sendyputra's test file at least doesn't load due to a parsing bug in TCPDF (not sure if this also applies to the original poster's issue). TCPDF assumes the XRef stream has some attributes which are actually optional, and fails if they're missing.
> 
> I opened a PR upstream with a fix [tecnickcom/TCPDF#104](https://github.com/tecnickcom/TCPDF/pull/104)

as seliquity mentioned, if you edited the pdf with pdf editor softwares and it throws the "Object list not found. Possible secured file." error, you can open the pdf file in a reader and save a copy of it and then it should work on the copy.

**Comment by reza-akbari** [comment]
I use [ghostscript](https://www.ghostscript.com/) to convert the pdf to version 1.4 before using this package

for example the `input.pdf` throws `Object list not found. Possible secured file`

run
`
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf input.pdf
`

the `output.pdf` works fine

**Comment by shakeelmohamed** [comment]
@reza-akbari thanks that helped!
