### ISSUE TITLE
Fix encoding in demo

### ISSUE THREAD

**Issue by romanmatyus** [smalot/pdfparser#319]
Please, I have PDF 
[VysledokAukcie-127691.pdf](https://github.com/smalot/pdfparser/files/4899897/VysledokAukcie-127691.pdf)

Output on demo page it's: 

```
100,00


1


EUR


1589,00


0,00


1589,00


HS technology s.r.o., IČO: 52081061, Sídlo: Fraňa Mojtu 22, 94901 Nitra,
Slovenská republika


99,10
...
```

My best encoded output it's:

```
100,00


1


EUR


1589,00


0,00


1589,00


HS technologVUR,26tGOR)UDD0RMWX1LWUD,
 Slovenská republika


99,10
```

How you encode and write text to html?

Thanks

**Comment by Connum** [comment]
I was able to confirm that this is the same regression introduced by 4f4fd10 as a fix for #260, as in #322!
Prior to that change, the text was decoded properly!
