### ISSUE TITLE
Command line file path issue

### ISSUE THREAD

**Issue by arturssmirnovs** [smalot/pdfparser#323]
Hey, i noticed that setting up path that contains white space gives back error on running process.

Filename: "CV Education- science/CV - XXXXXXX.pdf"
Command line executed: "/usr/bin/pdftotext /mnt/c/www/cv-parser/files/CV Education- science/CV - XXXXXXX.pdf -."

I was able to fix it by simple adding "" to PdfToTextParsere.php line 58..

Before: 
`$this->process->run("{$this->binary} {$this->file} -");`
After
`$this->process->run("{$this->binary} '{$this->file}' -");`

Guess it could be inspected on other special characters as well.

**Comment by j0k3r** [comment]
Are you sure you are using the PHP library? Because PdfParser doesn't have the `PdfToTextParsere.php` file nor the `pdftotext` binary file.

**Comment by arturssmirnovs** [comment]
Sorry, i posted in wrong PHP library, was using two different libraries, this and other, the issue was with other one.. 

Sorry for posting here.
