### ISSUE TITLE
Missing linebreak inside column

### ISSUE THREAD

**Issue by cdnhaese** [smalot/pdfparser#325]
I'm using this library (using the 'master' branch) with the following snippet of code: 
```php
<?php
 
// Include Composer autoloader if not already done.
include 'pdfparser/vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile($argv[1]);
 
$text = $pdf->getText();

$myfile = fopen("output.txt", "a") or die("Unable to open file!");
fwrite($myfile, $text);
fclose($myfile);
 
?>
```

This is part of the input file I'm using: [example.pdf](https://github.com/smalot/pdfparser/files/5116920/example.pdf)

The problem I'm having with this input, is that the linebreaks that appear visually inside a table cell are missing in the output.

As an example, the screenshot below shows a break between the words `fysiologische` and `systemen`.
![example](https://user-images.githubusercontent.com/29987739/91027349-47f55080-e5fc-11ea-964f-51026f273827.png)
This break is missing in the output, where it just shows `fysiologischesystemen` without any whitespace.

The problem is occuring everywhere in this file where there are multiple lines inside a single table cell.
Does anyone have a solution to make it such that any whitespace appears between those two words?

**Comment by rubenvanerk** [comment]
If you change the value `10` in this line to `9`: https://github.com/smalot/pdfparser/blob/master/src/Smalot/PdfParser/PDFObject.php#L346
Then it will detect the line break. However, more line breaks are detected too, so I don't know if this is desirable.

**Comment by cdnhaese** [comment]
Ok, thanks, this fixes my problem. More line breaks can always be handled, if they are missing to begin with thats much harder to do.

Would be nice to have this option configurable instead of having to adapt the code, which is already mentioned in #305.
