### ISSUE TITLE
Suddenly i get white boxes

### ISSUE THREAD

**Issue by Sandbird** [smalot/pdfparser#326]
I am using pdfparser to parse the daily infection reports for Covid in Greece. Up until now there have been some minor problems with spacing but overall i was able to get all the values from the pdf that i needed daily.
Today though, i am getting white boxes instead of text (http://prntscr.com/u5og9j), and i have no idea as to why.
Here is the new pdf that is causing problems: https://eody.gov.gr/wp-content/uploads/2020/08/covid-gr-daily-report-25-08-2020.pdf

Anyone has any idea ?

**Comment by j0k3r** [comment]
Did you update to a newer version of the lib? What version are you using?

**Comment by Sandbird** [comment]
The latest one, i only downloaded it a few days ago.

**Comment by k00ni** [comment]
Is the new PDF working with the version you used before?

**Comment by Sandbird** [comment]
> Is the new PDF working with the version you used before?
Hmm not sure i follow...
I just downloaded this library about 4 days ago. With other pdfs from previous days it is working fine. (For example this one: https://eody.gov.gr/covid-gr-daily-report-24-08-2020/). Today's pdf comes like i said with boxes.

**Comment by k00ni** [comment]
So if I understand you correctly, you confirm that the error ONLY appears because of the new lib version and NOT because of the new PDF. Did you check that the new PDF runs with an older version?

**Comment by Sandbird** [comment]
hehe, we are lost in translation :) i dont know if the 'old' version works because i've never tried it. I just found out about pdfparser a few days ago...I see that the last build was from 2-3 months ago.
I've parsed (every day i do one) 4 pdfs from the official Greek CDC website so far. The past few days everything was going fine, until today. ONLY this new pdf comes out all weird...Any previous PDFs from their website are fine....so something is happening with the NEW pdf that the library cant read...I dont know if they used a different font or something...i am asking for any ideas because it's just weird :)
I'll try downloading the older version of the library now and give that a go

**Comment by k00ni** [comment]
Any news on this?

We had a few bug fixes, so can you please try again with v0.17.0 and get back to us?

**Comment by Sandbird** [comment]
I just tried it, on the same pdf file and i still get the white boxes.. But i tried it with the latest pdf (since like i said these are daily pdf reports on Covid), and i got 'Object list not found. Possible secured file.'. Passing the file through **qpdf** first solved the problem. (https://prnt.sc/uxr2wo).
Maybe the white boxes were some weird font which are not used anymore, so apart from the qpdf problem, and some spacing problems (if you check the screenshot above) i guess everything is fine now :)

**Comment by k00ni** [comment]
> i guess everything is fine now :)

OK, so closed. Open an issue for each other problem in this regard.
