### ISSUE TITLE
v0.16.2

### ISSUE THREAD

**Issue by j0k3r** [smalot/pdfparser#329]
Prepare next release: https://github.com/smalot/pdfparser/releases/tag/untagged-4ff32cb9e2341d8cedd6

v0.16.2

Also we should be vigilant about the tag name. It must always start with a `v` :)

**Comment by k00ni** [comment]
I forgot it sometimes, my bad. 

> It must always start with a v :)

We can keep the `v` to be consistent, but as I read in different sources, using `v` became optional:
* SemVer 1.x required it, 2.x doesn't. https://semver.org/#is-v123-a-semantic-version
* Composer allows both: https://getcomposer.org/doc/04-schema.md#version
* Using `v` was historical: https://stackoverflow.com/a/6273142/5301527

**Comment by j0k3r** [comment]
It's just to be consistent with previous release :)
