### ISSUE TITLE
Fatal error: Call to undefined method Smalot\PdfParser\Object::decodeText() 

### ISSUE THREAD

**Issue by Garrcomm** [smalot/pdfparser#33]
With the PDF of one of our customers, I got the error message "Fatal error: Call to undefined method Smalot\PdfParser\Object::decodeText() in /pdfparser/src/Smalot/PdfParser/Object.php on line 318"
I created a small workaround to help my customer, but I think this needs some more work.

PDF file: http://nederland.ligtin.eu/sthoolen/20140416-Algemene%20bepalingen%20huurovereenkomst%20woonruimte.pdf
Patch file: http://nederland.ligtin.eu/sthoolen/20140416-pdfparser.patch

**Comment by rubenvanerk** [comment]
This issue was fixed by #41
