### ISSUE TITLE
Can't parse a PDF, saying "Possible secured file"

### ISSUE THREAD

**Issue by ackwo** [smalot/pdfparser#330]
Empty text after parsing this file (see attachment).

[SDS__chlorhaltiges_Desinfektionsmittel_(de-DE).pdf](https://github.com/smalot/pdfparser/files/5150727/SDS__chlorhaltiges_Desinfektionsmittel_.de-DE.pdf)

**Comment by ackwo** [comment]
The v0.16.2 demo says: "Object list not found. Possible secured file."

**Comment by j0k3r** [comment]
I tried too but nothing got parsed.
I don't know why. The PDF looks ok BTW.

**Comment by rubenvanerk** [comment]
Using `qpdf input.pdf output.pdf` may have fixed the file. Can you please try again with [this file](https://github.com/smalot/pdfparser/files/5155937/fixed.pdf)?

**Comment by ackwo** [comment]
Thanks for the answer! After qpdf the file can be analyzed and metadata is also found (pages, title, etc.), but unfortunately I cannot find any text again.

**Comment by vitalygoji** [comment]
Just installed pdf parser and got "Object list not found. Possible secured file". Big dissapointment.

**Comment by vitalygoji** [comment]
Just installed pdf parser and got "Object list not found. Possible secured file". Big disappointment.  EVERY online parser has no problem with that file. "pdfparser" fails..
