### ISSUE TITLE
Does not parse pages other than the first page

### ISSUE THREAD

**Issue by Reqrefusion** [smalot/pdfparser#331]
It converts only the first page of a 3 page pdf file. It does not do anything related to other pages. You can also observe this on the demo page.
Related pdf file:
https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2020/09/20200914-4-4.pdf

**Comment by Reqrefusion** [comment]
Acrobat PDFMaker 10.1 for Word is used for this file, but similarly, files converted to PDF have the same error.

**Comment by Connum** [comment]
Interesting... You can use `$pdf->getPages();` to get all three pages, but `->getText()` returns an empty string on the last two of them. Furthermore, the third page is of type `Smalot\PdfParser\PDFObject` instead of `Smalot\PdfParser\Page`. That should be handled in `Pages.php` inside the if/else construct in `getPages()`. In my opinion this should never return anything else than `Page`s!

**Comment by Connum** [comment]
I invested several hours now, trying to figure out what's wrong here...
I think one thing we should do at least is to change the `} else {` in `Pages.php` to
```php
} elseif ($kid instanceof Page) {
```

`getPages()` should only ever return array elements of the type `Page`, but evidently, `'Kids'` can hold other types too that we wouldn't want to pollute the resulting array with!

Other than that, I'm at a bit of a loss here...

**Comment by Reqrefusion** [comment]
@Connum Thanks for trying but I didn't see any improvement. Maybe in the future this problem will be resolved somehow. Thank you again.

**Comment by Connum** [comment]
Yeah, that wasn't a fix for the issue itself, just something I noticed we'd want to change while investigating it. For the issue itself, maybe I'll find some more time and motivation to investigate it, otherwise hopefully someone else will.

**Comment by hpvd** [comment]
ahh, found the same problem when trying the demo for several documents https://github.com/smalot/pdfparser/issues/416
-> are the any multipage files working fine?

**Comment by hpvd** [comment]
Another example file can be found here: https://github.com/smalot/pdfparser/issues/416#issuecomment-829056645
