### ISSUE TITLE
Supported PHP versions

### ISSUE THREAD

**Issue by Regal88** [smalot/pdfparser#332]
Hi, can you please confirm if PDFparser only works with PHP 5.3 as stated on the website or if this is the minimum version supported i.e. any version after PHP 5.3 also works?

Thanks

**Comment by j0k3r** [comment]
The website isn't up to date.
The minimum version is now PHP 5.6 (since [v0.15.1](https://github.com/smalot/pdfparser/releases/tag/v0.15.1)).

If you want to use that library with a lower version (like PHP 5.3) you have to use the version v0.15.0
