### ISSUE TITLE
Installing PdfParser without Composer

### ISSUE THREAD

**Issue by Regal88** [smalot/pdfparser#333]
Hi, can you please confirm if it is still possible to install PdfParser without Composer and, if so, provide the sample autoload file and instructions that relate to the current version (v0.16.2). It is difficult for me to install Composer in my hosted web service environment.

I have read through the the pinned issue (Using PdfParser without Composer #117) but I imagine this would be outdated now given it was last updated in Sep 2016.

Thanks in advance for your support.

**Comment by j0k3r** [comment]
The post is up to date, see the last comment https://github.com/smalot/pdfparser/issues/117#issuecomment-674725594

**Comment by Regal88** [comment]
Thank you very much.

Got it working now.

Cheers
Lynden

**Comment by k00ni** [comment]
I updated the initial post in #117 to reflect that its a viable alternative. Hope its more clear now.
