### ISSUE TITLE
Characters are translated correctly in Demo but not in Local

### ISSUE THREAD

**Issue by CharmaineLohSiYing** [smalot/pdfparser#334]
Hi, 

I have used this file for testing both on the demo page and on my local server (using PHP version 7.4.9).  
[tested-file.pdf](https://github.com/smalot/pdfparser/files/5229114/tested-file.pdf)

This is the output on the demo page:

![demo output](https://user-images.githubusercontent.com/44079990/93282727-a1b6f800-f801-11ea-8a4e-adab89cf9b3f.png)

and this is the output on my local server:

![local output](https://user-images.githubusercontent.com/44079990/93283636-81883880-f803-11ea-9274-6c580e162529.png)

To view the decimal values of the unmatched characters, I replaced "return $use_default ? self::MISSING : $char;" with "return $use_default ? self::MISSING : $dec." ";" in the translatechar() function in Font.php:

![local decimal](https://user-images.githubusercontent.com/44079990/93283843-ea6fb080-f803-11ea-8ef8-b627ee04355c.png)

From this, I managed to match these (abnormally large) decimal values with the characters that they are 'supposed' to be matched with:

- decimal 0 --> 'y'
- decimal 18432 --> 'e'
- decimal 768 --> ' ' (space)
- decimal 22272 --> 't'
- decimal 20992 --> 'o' 
...etc.

1. I noticed that these large decimal values usually appear when my pdf file is generated by converting from a webpage (using the print --> convert to pdf function). Could it be that files which are generated this way have different encoding rules?

2. May I know what changes I can make to attain the same result as on the demo page?

Thank you!

**Comment by Connum** [comment]
Reading "works in the demo but not on my dev system" is ringing my alarm bells now! 😅 I was able to confirm yet again that this is the same regression introduced by 4f4fd10 as a fix for #260, as in #322 and #319! The more I see issues caused by that "fix" for alleged bug that remains yet to be reproduced, in some mysterious PDF file that was never provided... the more I tend to recommending to revert that fix.
