### ISSUE TITLE
PHP 8:  Call to undefined function mb_convert_encoding()

### ISSUE THREAD

**Issue by Connum** [smalot/pdfparser#335]
I'm currently testing PHP 8.0.0 beta3, and using this library. I encountered the following error:

> Call to undefined function Smalot\PdfParser\mb_convert_encoding() in ***\vendor\smalot\pdfparser\src\Smalot\PdfParser\Font.php:500´

running the following code:
```php
    $parser = new \Smalot\PdfParser\Parser();
    $pdf    = $parser->parseFile('a_valid_pdf_file.pdf');
    $text = $pdf->getText();
```

**Comment by k00ni** [comment]
Good catch! I took a quick search but couldn't find a replacement for `mb_convert_encoding`. But hopefully there is some UPGRADE route soon available.

**Comment by j0k3r** [comment]
We should use `symfony/polyfill-mbstring` https://github.com/symfony/polyfill/tree/master/src/Mbstring
