### ISSUE TITLE
getDataTm() seems to be broken completely (wrong coordinates and wrongly decoded text content)

### ISSUE THREAD

**Issue by Connum** [smalot/pdfparser#336]
I created a very simple PDF for testing, because I had issues getting correct x and y coordinates when using `getDataTm()` (unfortunately, I can't provide any other PDFs for privacy reasons...)

=> [xy.pdf](https://github.com/smalot/pdfparser/files/5231236/xy.pdf)

```php
    $parser = new \Smalot\PdfParser\Parser();
    $pdf    = $parser->parseFile('xy.pdf');
    
    $pages = $pdf->getPages();

    foreach ($pages as $index => $page) {
        if (null === $page) {
            continue;
        }
        
        var_dump($page->getDataTm());
    }
```

For this PDF, the Text is not read correctly when using `getDataTm()` (but interestingly, it works when using `getText()` instead). Instead, where the text should be, there's what looks like HEX-encoded strings:

```php
array (size=13)
  0 => 
    array (size=2)
      0 => 
        array (size=6)
          0 => string '1' (length=1)
          1 => string '0' (length=1)
          2 => string '0' (length=1)
          3 => string '1' (length=1)
          4 => string '33.173' (length=6)
          5 => string '665.721' (length=7)
      1 => string '00270050005000430042005300010001' (length=32)
  1 => 
    array (size=2)
      0 => 
        array (size=6)
          0 => string '1' (length=1)
          1 => string '0' (length=1)
          2 => string '0' (length=1)
          3 => string '1' (length=1)
          4 => string '213.173' (length=7)
          5 => string '665.721' (length=7)
      1 => string '00230042005B004300420053' (length=24)
  2 => [...]
```

**Comment by k00ni** [comment]
Hi @izabala, because the functionality was provided by you, can you help us here?

**Comment by izabala** [comment]
Ok. Let me have a look on this!
I let you know.
Ivan Zabala Cell: +58414-929-8558 / +58412-2102012 e-mail: izabala@yahoo.com 

    On Wednesday, 16 September 2020, 05:38:54 am GMT-4, Konrad Abicht <notifications@github.com> wrote:  
 
 


Hi @izabala, because the functionality was provided by you, can you help us here?

**Comment by izabala** [comment]
I will have a look as soon as I can.

**Comment by Connum** [comment]
#340 should fix a part of this issue, the text decoding. I'll try to look into the coordinates myself as well, but I'm not sure if I'm able to wrap my head about the whole thing, not being experienced with the PDF specifications at all.

**Comment by Connum** [comment]
I can't seem to figure out what's going on... According to the PDF specs, the Td and TD commands seem to be implemented as they should, offsetting the coordinates from the current line with the given set of coordinates... But then I don't understand why the PDF looks correct and the the texts are aligned correctly... If I replace the `+=` operator with simply `=`, the coordinates seem to be fine and I can make a decision based on those coordinates whether two pieces of text are aligned in the same "column2" - but that seems to go against the specs...

**Comment by k00ni** [comment]
Could you please add some parts of the spec you are referring to? That would be helpful and may help others to help out here.

**Comment by Connum** [comment]
I'll link to the PDF when I'm back home, but the crucial parts are actually quotes in comment blocks in the code before each switch/case statement of the different commands!

**Comment by izabala** [comment]
I am having a look to the decode part.  I believe that I know what should be done to corrected it.  After that with more info, because I dont understand the problem, we can see the TD and td part with the  += and = operation part. We have to have an example to really understand what is needed there.

I let you know when I have the first part fixed.

**Comment by Connum** [comment]
> I let you know when I have the first part fixed.

Hi and thanks! The first part should already be fixed with my PR #340. I uploaded an example PDF in the opening post of this issue. The words that are in one column (e.g. the two "Lorem"s) should have the same x coordinate and only slightly different y coordinates, but they differ greatly.

**Comment by izabala** [comment]
Thanks for th PR#340.  It is a better solution!!!.  Let me have a look the coordinate problems... and I let you know what I see ASAP.

**Comment by izabala** [comment]
Let have a discussion on this.
 All the information about the text command are in the link: 
[https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf](url)

Chapter 5 (and some explanation of the beggining of Chapter 4). Starting from the page 308 and mainly in the pages 310 and 311.  (In the page 134 there is a Table with the index of every command).
They used 2 matrix (to described the commands) the TM (text matrix) and the TLM (texlt line matrix). I used just the TM because for the usage we have, I dont see why to used both, and I dont see that this is the problem here.

For seeing what is happening, I used the extractDecodedRawData() because it let us know all the commands that are in the pdf.

Here are some lines of that:
```
array (size=3)
  't' => string '' (length=0)
  'o' => string 'Td' (length=2)
  'c' => string '33.173 665.721' (length=14)
array (size=3)
  't' => string '[' (length=1)
  'o' => string 'TJ' (length=2)
  'c' => 
    array (size=3)
      0 => 
        array (size=3)
          't' => string '<' (length=1)
          'o' => string '' (length=0)
          'c' => string 'Foobar ' (length=7)
      1 => 
        array (size=3)
          't' => string 'n' (length=1)
          'o' => string '' (length=0)
          'c' => string '94' (length=2)
      2 => 
        array (size=3)
          't' => string '<' (length=1)
          'o' => string '' (length=0)
          'c' => string ' ' (length=1)
array (size=3)
  't' => string '' (length=0)
  'o' => string 'Td' (length=2)
  'c' => string '180 0' (length=5)
array (size=3)
  't' => string '<' (length=1)
  'o' => string 'Tj' (length=2)
  'c' => string 'Bazbar' (length=6)
array (size=3)
  't' => string '/' (length=1)
  'o' => string 'Tf' (length=2)
  'c' => string 'C0_1 12' (length=7)
array (size=3)
  't' => string '' (length=0)
  'o' => string 'Td' (length=2)
  'c' => string '318.185 665.044' (length=15)
array (size=3)
  't' => string '<' (length=1)
  'o' => string 'Tj' (length=2)
  'c' => string 'Lorem' (length=5)
array (size=3)
  't' => string '' (length=0)
  'o' => string 'Td' (length=2)
  'c' => string '416.619 664.366' (length=15)
array (size=3)
  't' => string '<' (length=1)
  'o' => string 'Tj' (length=2)
  'c' => string 'Ipsum' (length=5)
```
We have a Td before Foobar (it sets the TM), after foobar we have another Td with X = 180 and Y = 0 (This is OK, it just move in X but no it Y) and then we have Bazbar.  After that we have another Td with X = 318.185 and Y = 665.044, (not Y = 0) That's create the problem.  
Because the Td as is shown on page 310 of the PDF Refence, should change the TM and the Tlm every time.  (Unless I get it totally wrong).
I also have a look to the extractRawData() and extractDecodedRawData() to see if we are missing commands, that can explain the problem, but It seems that it is Ok.
So having this, I dont see where is the problem.

**Comment by izabala** [comment]
By the way... all this is the same that Connum says when he says: 
"_I can't seem to figure out what's going on... According to the PDF specs, the Td and TD commands seem to be implemented as they should, offsetting the coordinates from the current line with the given set of coordinates... But then I don't understand why the PDF looks correct and the the texts are aligned correctly..._ "

**Comment by k00ni** [comment]
I followed this issue and would like to summarize what we currently have. Please correct me, when I am wrong.

* PDF Spec says A.
* We do A, but get B.
* We currently don't know what is required to get the results we expect?

**Comment by izabala** [comment]
I beleive I got it.  I used the debugger at the beginning of the extractRawData method.  And I look into $values:
```
"BT 0 i  /C0_0 12 Tf 33.173 665.721 Td [<0027005000500043004200530001>94 <0001>]TJ 180 0 Td <00230042005B004300420053>Tj ET /TouchUp_TextEdit MP BT /C0_1 12 Tf 318.185 665.044 Td <002D005000530046004E>Tj ET /TouchUp_TextEdit MP BT 416.619 664.366 Td <002A005100540056004E>Tj ET /TouchUp_TextEdit MP BT /C0_0 12 Tf 33.173 616.3 Td <0027005000500043004200530001>Tj /C0_2 12 Tf -1.128 Tw 35.999 0 Td <0013>Tj /C0_0 12 Tf 33.276 Tw <0001>Tj 0 Tw 149.76 0 Td <00230042005B004300420053>Tj /C0_2 12 Tf <0013>Tj ET /TouchUp_TextEdit MP BT /C0_1 12 Tf 318.185 615.624 Td <002D005000530046004E>Tj /C0_2 12 Tf <0013>Tj ET /TouchUp_TextEdit MP BT /C0_1 12 Tf 416.619 614.946 Td <002A005100540056004E>Tj /C0_2 12 Tf <0013>Tj ET "
```
If you see the value of that string, it has a bunches of BT and ET.  That's makes the TM to reset every time.
But if you go down in the extractRawData, it goes to:
`$sectionsText = $content->getSectionsText($content->getContent());`
but now $sectionText doesnt have the BT or the ET.  So Thats makes the problem.

**Comment by izabala** [comment]
Guys, I cant spend more time right now (and for a couple of days ) on this, But I beleive that changing in extractRawData... the line:
`$sectionsText = $content->getSectionsText($content->getContent());`
and using getCommandsText($values) can we what we have.. but we have to double check on this.. .and test it.

**Comment by Connum** [comment]
Thanks @izabala for pointing us in the right direction! I'll also have another go at it, but it might take me a couple of days as well.

**Comment by Connum** [comment]
I was able to look into this quicker than I thought I was going to be able to and just created PR #341!
It took me a while to figure this out, but the solution was actually quite simple... Have a look at my remarks in the PR. I'm looking forward to your feedback!

**Comment by izabala** [comment]
Excelent!!! If i have a chance i will have a look!

Ivan Zabala Cell: +58414-929-8558 / +58412-2102012 e-mail: izabala@yahoo.com 

    On Friday, 18 September 2020, 03:34:26 pm GMT-4, Connum <notifications@github.com> wrote:  
 
 


I was able to look into this quicker than I thought I was going to be able to and just created PR #341!
It took me a while to figure this out, but the solution was actually quite simple... Have a look at my remarks in the PR. I'm looking forward to your feedback!

**Comment by k00ni** [comment]
@Connum: After merging your two PRs, we ran into a failing tests. I don't know why it happened *after* the merge.

Example: https://travis-ci.org/github/smalot/pdfparser/jobs/730197753#L260

```
1) Tests\Smalot\PdfParser\Integration\PageTest::testGetDataTmIssue336
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => '1'
     1 => '0'
     2 => '0'
     3 => '1'
-    4 => '531.358'
-    5 => '1330.765'
+    4 => '318.185'
+    5 => '665.044'
/home/travis/build/smalot/pdfparser/tests/Integration/PageTest.php:445
```

Any idea why?

**Comment by Connum** [comment]
Now that's quite strange... I even had a local branch where I merged in all of my recent PRs, with the tests passing... 🤔 Was anything else merged in the meantime that could cause a cross-interference? I'll also have a look at it as soon as I find the time!

**Comment by k00ni** [comment]
As seen in the commits list, only changes by you where made since August (https://github.com/smalot/pdfparser/commits/master)

```
Commits on Sep 25, 2020
- fix missing BT command before each section (could result in wrong coo… …
Connum committed 2 hours ago
  
- rely on getTextArray() in getDataTm() to extract the texts (#340) …
Connum and k00ni committed 2 hours ago


Commits on Sep 17, 2020
- Merge pull request #337 from Connum/mbstring-polyfill …
j0k3r committed 8 days ago
  

Commits on Sep 16, 2020
- replace the requirement for ext-mbstring with symfony/polyfill-mbstri… …
Connum committed 9 days ago
```

> I'll also have a look at it as soon as I find the time!

That would be great. Thank you.

**Comment by Connum** [comment]
It seems that I missed something when merging my PRs locally. The values that are marked as unexpected in the test are indeed the correct values after implementing #341! (That's why the coordinate values are so big...) Fixed with PR #343!

**Comment by k00ni** [comment]
OK, thank you. Is this issue solved?

**Comment by Connum** [comment]
Yup, solved for me!

**Comment by k00ni** [comment]
Thank you.
