### ISSUE TITLE
How to organize documentation for PDFParser?

### ISSUE THREAD

**Issue by k00ni** [smalot/pdfparser#352]
@Reqrefusion thank you for taking the time to create a Wiki page. I saw that there are some outdated information, like minimum PHP version. It begged the question how to communicate about errors and changes in the future.

**Therefore I propose moving documentation from the Wiki to the repository itself**, also use Markdown for content. A good location could be `/doc`. For changes and new content we create PRs.

What do you think?

**Comment by Reqrefusion** [comment]
Before you, thank you for continuing this project. The reason I created a documentation on the wiki page, not inside the files, was that it was easier to create a wiki. There are of course many advantages to creating documentation inside files.

**Why wiki?**

- It's easier to change. Development can be made easily.
- It is more convenient for more than one person to work. Although the original documentation is not bad, I think they are very old and need to be improved. Documentation will be more necessary if the idea suggested in #305 is realized, especially when there are plans such as moving to 1.0. In this case, it is more convenient to work on the wiki.
- The wiki is easier to access. Without entering the codes, editing the wiki can be done like creating a header in the isues section. This increases the number of people doing work.

**Why / doc?**

- It's more under control. Changes proceed in a controlled manner.
- Multiple language support. Documentation can be created for other languages ​​easily.

These are the things that come to my mind for now. But I am sure that a library is only as good as its documentation. Storing it as / doc seems to be the best method if a good documentation is created at first. It should also be indexed well and ready for other languages.

**Comment by k00ni** [comment]
Your points sounds reasonable. Please continue your work and let me/us know, if there a certain things to discuss. Closing for now.
