### ISSUE TITLE
getText() adds the letter "j" to a lot of words in the PDF content

### ISSUE THREAD

**Issue by conkreet** [smalot/pdfparser#353]
When I parse the attached PDF, the letter "j" is added to random words when I use getText(). For instance, in some cases the term "BrabantWonen" is changed to "BjrabantWonen" and "aanbrengen" becomes "aanbrengejn". Is this a known issue?

[4c011e062aafcc305834aa245734eafc6945c1dc.pdf](https://github.com/smalot/pdfparser/files/5343195/4c011e062aafcc305834aa245734eafc6945c1dc.pdf)

**Comment by GreyWyvern** [comment]
Hi @conkreet. Are we able to use your sample PDF [4c011e062aafcc305834aa245734eafc6945c1dc.pdf](https://github.com/smalot/pdfparser/files/5343195/4c011e062aafcc305834aa245734eafc6945c1dc.pdf) in the PdfParser test suite? Is the file free to use? Thanks!
