### ISSUE TITLE
Problems with PDF Version: 1.5 (Object list not found. Possible secured file. Parser.php 102)

### ISSUE THREAD

**Issue by Sandbird** [smalot/pdfparser#356]
I know there are several posts with this problem, but I didn't want to hijack their post, plus i thought i could provide some more data on the problem.
**PDF File**: https://eody.gov.gr/wp-content/uploads/2020/10/covid-gr-daily-report-20201011.pdf **(free to use, [ref](https://github.com/smalot/pdfparser/issues/356#issuecomment-724618850))**
**Error**: Object list not found. Possible secured file. (src\Smalot\PdfParser\Parser.php102)
**Fonts Used**: http://prntscr.com/uxrjhi
**Security details**: http://prntscr.com/uxrjyt
**qpdf check**:
```
C:\qpdf --check daily.pdf
checking daily.pdf
PDF Version: 1.5
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain errors that qpdf cannot detect
```
Parsing the file first with **qpdf** does solves the problem, but that's not really a solution (at least for me since i cant install qpdf on my server, and i have to use the windows version first and then manually upload the file on my linux server).

**Comment by k00ni** [comment]
Thank you for reporting it. Can you reference these posts you mentioned, please?

**Comment by clicksistema** [comment]
It happens for me too and the version of PDF is 1.7
[file](https://www.riodasostras.rj.gov.br/wp-content/uploads/2020/07/encarte-ldo-ed-1197.pdf)

**Comment by k00ni** [comment]
@Sandbird and @clicksistema: Can we use your PDF files in our test environment? They must be free to use and without any obligations.

**Comment by Sandbird** [comment]
Yup.

**Comment by clicksistema** [comment]
yes
