### ISSUE TITLE
Charset encoding error?

### ISSUE THREAD

**Issue by ermorela** [smalot/pdfparser#36]
I'm having a problem while reading german chars. 
ü is read as Ã¼, ö as Ã¶, but also on Latin à becomes Ã and so on.
Thanks in advance for your help

**Comment by bakhtiyar8** [comment]
Hi, i have probably the same problem, I put the header('Content-Type: text/html; charset=utf-8'); and it didn't work, in the output shows simboles like: 
----
(%PDF-1.5 %���� 1 0 obj <>>> endobj 2 0 obj <> endobj 3 0 obj <>/ProcSet[/PDF/Text/ImageB/ImageC/ImageI] >>/MediaBox[ 0 0 595.32 841.92] /Contents 4 0 R/Group<>/Tabs/S/StructParents 0>> endobj 4 0 obj <> stream x��\[��~7��a�4杜`!@�UѢZ�E�>;M�8���<ΐÑDikI���wn�ҽ�K��������l��a���=�y{��4�0ݻOod'��R����ת{�)  ......
---
Do you know how to fix this?

**Comment by Connum** [comment]
Three years have passed... If @bakhtiyar8 could still provide the PDF in question for us to test and debug (or see whether the issue has been fixed meanwhile), I could have a look at it. Otherwise, as the original poster's initial issue has been solved, I'd be in favour of closing it.

**Comment by k00ni** [comment]
There could be many reasons for encoding problems:
1. The encoding of the PDF file and your script are not the same
2. No proper transformation from one encoding to another
3. Output is encoded in another encoding as the data you wanna output

Putting `header('Content-Type: text/html; charset=utf-8');` somewhere seems to be my third point. @ermorela's question was answered by himself, therefore issue is done.

@bakhtiyar8 if you still have a encoding problem please open a new issue. If you can, please provide some example code and a PDF that we can use to verify this. 

Thanks for checking @Connum.
