### ISSUE TITLE
Call to undefined method Smalot\PdfParser\Encoding::__toString()

### ISSUE THREAD

**Issue by rubas** [smalot/pdfparser#364]
We are seeing a lot of uncatched errors, when we try to extract the content of some pdfs.

----
# Encoding::__toString()
`Call to undefined method Smalot\PdfParser\Encoding::__toString()`

You find the complete stack trace [here](https://sentry.io/share/issue/e9900813f79640bebcfdce74742fd670/). The char is `\`.

```
if (\strlen($char) < 2 && $this->has('Encoding') && 'WinAnsiEncoding' === $this->get('Encoding')->__toString()) {
    $fallbackDecoded = self::uchr($dec);
 }
```

https://github.com/smalot/pdfparser/blob/master/src/Smalot/PdfParser/Font.php#L104

---
# Header::__toString()

`Call to undefined method Smalot\PdfParser\Header::__toString()`
You find the complete stack trace [here](https://sentry.io/share/issue/3aadd3b6478844759f0c46a60cccf6f4/). The char is `!`.

---
# Code
Our code is simple.
```
use Smalot\PdfParser\Parser;

$content = file_get_contents($url);
...
$parser = new Parser();
$pdf    = $parser->parseContent($content);

return $pdf->getText();
```

---
# Testfiles
[10-12.pdf](https://github.com/smalot/pdfparser/files/5464128/10-12.pdf)
[12-14.pdf](https://github.com/smalot/pdfparser/files/5464130/12-14.pdf)
[28-32-2.pdf](https://github.com/smalot/pdfparser/files/5464131/28-32-2.pdf)

**Comment by k00ni** [comment]
Thank you for your detailed bug report.

**Comment by clicksistema** [comment]
it's happening for me too.
I've followed the error and looks like one of object returned by function "resolveXRef" from class header isn't a element class.
the archive i've tried to read is [this](https://www.riodasostras.rj.gov.br/wp-content/uploads/2020/02/ed1136.pdf)

**Comment by clicksistema** [comment]
the function __toString is missing on class Encoding
I've created it to return anything and the test and the error stoped

**Comment by k00ni** [comment]
Can you paste your fix here?

**Comment by clicksistema** [comment]
I've insert this function to class Encoding:

```
    public function __toString()
	{
		return implode(',',$this->encoding);
	}

```
Just to be clear that i didn't check for what this class is used. I just created a function that works and was not founded before.
I belive that most times this class was not returned as a object of HEADER class but when HEADER has one object of this class the error occurs

**Comment by johnyboom** [comment]
Hi, I have the same issue. But sadly the fix removes the error not the problem.
If you have one rouge character in a file no big deal but some of the files, I need to parse, are almost entirely unreadable.

[pd120320.pdf](https://github.com/smalot/pdfparser/files/5515771/pd120320.pdf)

`TISKOVÁ ZPRÁVA
Centrum pro výzkum veejného mínní
Sociologický ústav AV R, v.v.i.
 
!"#
 $%&'%()&&&*  ` etc.

Despite this, the majority of files are parsed nicely so great work.

**Comment by k00ni** [comment]
@johnyboom: Is the PDF you posted free to use and without obligations? We may add it to our test environment to test potential fixes.

**Comment by johnyboom** [comment]
Well, it is a public document but to be sure I'll ask for consent.

https://cvvm.soc.cas.cz/media/com_form2content/documents/c2/a47/f9/pd120320.pdf

**Comment by johnyboom** [comment]
> @johnyboom: Is the PDF you posted free to use and without obligations? We may add it to our test environment to test potential fixes.

Ok, we have consent to use it for tests. I've forwarded the details to your email.

**Comment by k00ni** [comment]
The following consent was given for the mentioned PDF file:

> We are giving consent to https://www.pdfparser.org to freely use pdf file https://cvvm.soc.cas.cz/media/com_form2content/documents/c2/a47/f9/pd120320.pdf for testing purposes.
Content of the file is still intellectual property of "CENTRUM PRO VÝZKUM VEŘEJNÉHO MÍNĚNÍ Sociologický ústav AV ČR, v.v.i." and should be handled according to https://cvvm.soc.cas.cz/cz/cvvm/dokumenty/13-pravni-ujednani.

If someone wants to provide a fix and using this file to check, **please include my quote as is and add it to the code part which uses the PDF**.
