### ISSUE TITLE
Reading Umlauts adds additional whitespaces around it

### ISSUE THREAD

**Issue by panique** [smalot/pdfparser#365]
# BUG

PDFparser puts a space after and before each german umlaut (ü, ä, ö and maybe others too) which makes no sense.

### Expected behaviour

The word `Sämtliche` should be parsed as `Sämtliche`

### Actual behaviour

The word `Sämtliche` is parsed as `S ä mtliche`

### How to reproduce

I can reproduce with the `"v0.16.2` but also with live demo on https://pdfparser.org/demo
I've attached an demo pdf that contains the above case for better testing.

[test2.docx.pdf](https://github.com/smalot/pdfparser/files/5482234/test2.docx.pdf)

**Comment by k00ni** [comment]
Just to be sure, can you please try again with the latest version 0.17.1?

**Comment by panique** [comment]
Hi @k00ni , the result with `0.17.1` is exactly the same!

**Comment by k00ni** [comment]
Thank you for testing it.

**Comment by hpvd** [comment]
just did some more testing:
- problem still exists using demo with parser v0.19
- simple copy and paste text from this pdf does not add these white spaces

when exporting same text from ms word instead of libre office to pdf, everything looks fine using demo parser
file: 
[test-german-umlauts.pdf](https://github.com/smalot/pdfparser/files/6391934/test-german-umlauts.pdf)

**Comment by rubenvanerk** [comment]
Using #505, this seems to fix the issue:

```php
$config = new \Smalot\PdfParser\Config();
$config->setHorizontalOffset('');

$parser = new \Smalot\PdfParser\Parser([], $config);
$pdf    = $parser->parseFile('document.pdf');
 
$text = $pdf->getText('path/to/pdf.pdf');
```

Outputs:
```text
Vorwort 
In   dieser   Arbeit   wird   zugunsten   der   besseren   Lesbarkeit   auf   die   gleichzeitige
Verwendung   männlicher   und   weiblicher   Sprachformen   verzichtet.   Sämtliche
Personenbezeichnungen gelten gleichwohl für beiderlei Geschlecht.
1 von 1 
...
```

To get rid of the extra spaces between some words, use a font space limit of -132 or lower:
```php
$config->setFontSpaceLimit(-32);
```

Output:
```text
                                Vorwort 
In dieser Arbeit wird zugunsten der besseren Lesbarkeit auf die gleichzeitige
Verwendung männlicher und weiblicher Sprachformen verzichtet. Sämtliche
Personenbezeichnungen gelten gleichwohl für beiderlei Geschlecht.
1 von 1 
```

**Comment by k00ni** [comment]
Thank you for your work here and in other issues lately @rubenvanerk.

Closed, please reopen if problem persists.
