### ISSUE TITLE
Weird characters and missing text in multiline metadata text

### ISSUE THREAD

**Issue by gnojus** [smalot/pdfparser#366]
Hello.
I have an issue with the way this library extracts metadata from a PDF file. It comes out corrupted, and I'm not sure why.
It looks to me that for some reason `\` are prefixed before newlines, but I may be wrong.
Code used:
```php
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('./file.pdf');
$details  = $pdf->getDetails();
echo $details['Subject'];
```
I attach the pdf's tested with metadata descriptions used, inserted with _Adobe Acrobat_.
[pdf_1.pdf](https://github.com/smalot/pdfparser/files/5483330/pdf_1.pdf)
[pdf_2.pdf](https://github.com/smalot/pdfparser/files/5483331/pdf_2.pdf)
[pdf_3.pdf](https://github.com/smalot/pdfparser/files/5483332/pdf_3.pdf)
[subject_in_1.txt](https://github.com/smalot/pdfparser/files/5483333/subject_in_1.txt)
[subject_in_2.txt](https://github.com/smalot/pdfparser/files/5483334/subject_in_2.txt)
[subject_in_3.txt](https://github.com/smalot/pdfparser/files/5483335/subject_in_3.txt)
[subject_out_1.txt](https://github.com/smalot/pdfparser/files/5483339/subject_out_1.txt)
[subject_out_2.txt](https://github.com/smalot/pdfparser/files/5483341/subject_out_2.txt)
[subject_out_3.txt](https://github.com/smalot/pdfparser/files/5483342/subject_out_3.txt)

Also I actually came here because of another library https://github.com/pauln/tcpdi. However, that one didn't seem very active and both of these libraries seemed to have problems with metadata. So there comes my other question - what is the relationship between `tcpdi_parser` and`tcpdf_parser` could `tcpdi_parser` be replaced by `tcpdf_parser`, this way having more update version?

**Comment by k00ni** [comment]
> Also I actually came here because of another library https://github.com/pauln/tcpdi. However, that one didn't seem very active and both of these libraries seemed to have problems with metadata. So there comes my other question - what is the relationship between tcpdi_parser andtcpdf_parser could tcpdi_parser be replaced by tcpdf_parser, this way having more update version?

PDFParser used some code from https://github.com/tecnickcom/TCPDF, but I ported it and removed TCPDF as Composer dependency. The files I ported can be found here: https://github.com/smalot/pdfparser/tree/master/src/Smalot/PdfParser/RawData

Last time I checked tecnickcom's TCPDF project, it had the following message in the README.md:

```
A new version of this library is under development at https://github.com/tecnickcom/tc-lib-pdf 
and as a consequence this version will not receive any additional development or support. 
This version should be considered obsolete, new projects should use the new version as soon 
it will become stable.
```

I don't know if `tcpdf_parser` is more up to date, but the project it belongs to is not actively maintained and I don't think its a good idea to add it as a dependency again. But we could discuss potential code contributions as a PR for instance.

**Comment by nojus297** [comment]
All right, thanks for information.
Do you have any idea about the corrupted metadata (description).

**Comment by nojus297** [comment]
All right, I think I found the bug myself - special characters in PDF strings may be escaped (e. g. `(`, `)`, `\r`), thus when querying metadata they should be un-escaped.

**Comment by k00ni** [comment]
> All right, I think I found the bug myself - special characters in PDF strings may be escaped (e. g. (, ), \r), thus when querying metadata they should be un-escaped.

So one has to take care of himself or do you suggest a change in the PDFParser?

**Comment by nojus297** [comment]
I strongly believe that this should be handled by the library - end user shouldn't be required to read PDF specification and implement his own escaping function just to extract metadata as simple text.

**Comment by gnojus** [comment]
Yes, from a quick test, it seems to work correctly with my first test pdf.
