### ISSUE TITLE
Call to a member function init() on boolean in Header.php on line 66

### ISSUE THREAD

**Issue by lukgru** [smalot/pdfparser#367]
Call to a member function init() on boolean" at vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php line 66
Version: 0.17.1

**Comment by MrNickert** [comment]
Having the same issue.

Fatal error: Uncaught Error: Call to a member function init() on boolean in /PdfParser/Header.php:66 Stack trace: #0 /PdfParser/Document.php(80): Smalot\PdfParser\Header->init() #1 /PdfParser/Document.php(147): Smalot\PdfParser\Document->init() #2 /PdfParser/Parser.php(115): Smalot\PdfParser\Document->setObjects(Array) #3 /PdfParser/Parser.php(81): Smalot\PdfParser\Parser->parseContent('%PDF-1.4\n1 0 ob...') #4 index.php(7): Smalot\PdfParser\Parser->parseFile('..') #5 {main} thrown in /PdfParser/Header.php on line 66

**Comment by k00ni** [comment]
Can you provide an example PDF which triggers the error? It must be free to use for us (no obligations) and will be part of the test environment.

**Comment by MrNickert** [comment]
Trying to digitalize some recipes i've gotten from a meal subscription. Got one from their website for now.
[R-65505_-_Marokkaanse_kip_met_harissa-CV.pdf](https://github.com/smalot/pdfparser/files/5560632/R-65505_-_Marokkaanse_kip_met_harissa-CV.pdf)

**Comment by k00ni** [comment]
I am no expert in copyright law, but that file contains intellectual work (written text as well as these photos) and without permission of the actual owner, we would infringe their copyright.

Lets leave this file here for test reasons. Maybe there is another one, which can be used in the test environment.

**Comment by MrNickert** [comment]
Yeah i know. Wanted to use it for personal use only. Can you do a test on it so I know more where the error is coming from? Mabye the pdf is protected?

**Comment by lukgru** [comment]
Quick fix working for me
`foreach ($this->elements as $name => $element) {
        	$element->init();
        }`
replace with
`foreach ($this->elements as $name => $element) {
        	if($element instanceof Element) {
				$element->init();
			}
        }`

**Comment by MrNickert** [comment]
awesome. Thanks!

**Comment by k00ni** [comment]
@lukgru where did you deploy your fix?

**Comment by lukgru** [comment]
@k00ni if my fix is correct i can create pull request

**Comment by k00ni** [comment]
@lukgru that would be great. But we need a test case which triggers the error in the old code but runs without an error using the fix. One way to do it, could be with a PDF which triggers the error.

**Comment by mathias1981** [comment]
Hi, i have the sameb bug on my side. The bugfix also works for me. Can yo push on next release?

**Comment by k00ni** [comment]
@mathias1981 thank you for the reminder. 

@lukgru I created a PR with your fix.

Closing this in favor of #380.
