### ISSUE TITLE
Code of the example page

### ISSUE THREAD

**Issue by skillgamer** [smalot/pdfparser#374]
I was just wodering what the php code of the demo website is (https://www.pdfparser.org/demo) could you may give it me or is that some where on the github ? Sorry if I bother you

**Comment by k00ni** [comment]
> Sorry if I bother you

Don't worry, that's what an issue tracker is for.

If I remember correctly, its just a form with a file upload. After the upload it may check if its a PDF, parses it and outputs its content.

CC @smalot

**Comment by skillgamer** [comment]
ah ok do you know how I can use a file from $Post ? so do I have to save it on the server and then read it ?

**Comment by k00ni** [comment]
That is basic PHP knowledge and can't be answered (or discussed) in this issue tracker. Have a look at https://www.php.net/manual/en/features.file-upload.post-method.php for a good introduction.

After the upload you can use `Parser::parseFile` to parse PDF and get its content.
