### ISSUE TITLE
Missing object reference #397_0.

### ISSUE THREAD

**Issue by babarinde** [smalot/pdfparser#38]
Hello and great work on this tool.
Please when I upload this file:

```
https://s3-us-west-2.amazonaws.com/gindex/a.pdf
```

in the provided demo

I get the error:

```
 Missing object reference #397_0.
```

I get The same error when using the code directly as well with a stack trace:

```
#0 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Header.php(146): Smalot\PdfParser\Header->resolveXRef('Info')
#1 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(122): Smalot\PdfParser\Header->get('Info')
#2 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(86): Smalot\PdfParser\Document->buildDetails()
#3 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(152): Smalot\PdfParser\Document->init()
#4 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php(106): Smalot\PdfParser\Document->setObjects(Array)
#5 /usr/local/www/alas/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php(73): Smalot\PdfParser\Parser->parseContent('%PDF-1.5?%?????...')
#6 /usr/local/www/alas/module/Application/view/application/index/index.phtml(3): Smalot\PdfParser\Parser->parseFile('/usr/local/www/...')
```

I am quite sure its the file as another file uploads perfectly but can't quite figure out whats wrong
Thanks

**Comment by abaecor** [comment]
Hi Garrcomm,

AM getting 'Exception' with message 'Missing object reference #837_0 error so I tried the patch you mentioned, but now it gives me  Fatal error: Call to a member function getHeader() on a non-object on line 123. Can you please help.

Awaiting response. 
Thanks.

**Comment by abaecor** [comment]
Sorry I got it worked patch worked just fine.

Cheers :)

**Comment by k00ni** [comment]
Hey, if you are still using this library it would be great if you could try again with our latest release and get back to us. Thank you.
