### ISSUE TITLE
weired characters and missing texts

### ISSUE THREAD

**Issue by mano077** [smalot/pdfparser#387]
[ALE9613-ZURICH.pdf](https://github.com/smalot/pdfparser/files/5864887/ALE9613-ZURICH.pdf)

**please check below text ..** 

Motor Quotation For New Business:Issue Date & Time:Quotation Number MQ21000017339621/01/2021 10:36:59Quotation Expiry date :31/01/2021Coverage Details-gBArEiFby QBxQfBS gMMM- gNBAQBxQfBS g FBRsAiQCB MD.F.TQf.D-TR%RCJoKR-ToKLFRQfLTQMQNMuToKRTIVQOasQlhlV IhQOasQlhll VVIQPDLTQRFQKLRSRTVehicle DetailsMMDaU QBxQK VNEW K VNEW QT XNtigaiNBsQCBYLRRdPVI-RT.uSLQZRNNLQLuKLCfRQD[VPQ\QJ-QLSF.DLFof[ agQBxQDaU MCrev gQBxQ-att sX gt MMfayaENibMV]IldYhhQff( lhVd-DlZIhVJhhIVlc\P\fVattNtQCBYInsured DetailsMMCrev gQBxQCae AQugNS gtostrg AQCae CTofmZrtNs ttQT XQCBYm.iV gQouMDBvNW QCrev g MRRRQf%SoQC^LQVCmL cch_l\MhVMclhlPremium DetailsJreQostrg APTDT -g eNrePTDTI_]hhhYhhV]I(dYI_Cfu P`T(NCD % may vary depending on NCD record from ISM) (RM)(RM)NCD 55.00 747.66611.72(RM)Basic Net Voluntary Excess0.00 397.65Extra Coverage(RM)(RM)All Claims Excess (RM)Stamp Duty (RM)(RM)Payable Premium(RM)Act Premium (RM)(%)SSTSSTPAC0.00251.75 0.0010.00 60.561,079.93Voluntary Excess(RM)0.006.00Add-onsExtra BenefitExtra Sum Ins. (RM)Extra Premium (RM)AUTHORISED DRIVER 0.0020.00LEGAL LIABILITY TO PASSENGERS 0.0030.15STRIKE, RIOT AND CIVIL COMMOTION 0.00114.00INCLUSION OF SPECIAL PERILS 0.0076.00LEGAL LIABILITY OF PASSENGERS FOR NEGLIGENT ACTS 0.007.50BREAKAGE OF GLASS IN WINDSCREEN, WINDOW OR SUNROOF - ZDRIVER 1,000.00150.00NCD TablePayable Premium (RM)NCD % 0.00 1872.45 25.00 1512.22 30.00 1440.17 38.33 1320.14 45.00 1224.03 55.00 1079.93D13607-001 TWO DEGREES SDN BHDAgentTel No :: 016-3315088Page 1 of 1This quote is for information purpose only. This is not an insurance contract. Prices shown above are effective as of the date of this quotation and are subject to changes. To obtain insurance cover, you must submit an application to Zurich.

**Comment by mano077** [comment]
I have tried in demo page also same 
https://www.pdfparser.org/demo

**Comment by k00ni** [comment]
Thank you for the bug report.

* Which PHP version do you run?
* Which PDFParser version do you run?
* Please paste the code you use to access the PDF file.

**Comment by mano077** [comment]
Php version :  7.2.34
"license": "LGPL-3.0"

include 'vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('ALE9613-ZURICH.pdf');
 
// Retrieve all pages from the pdf file.
$pages  = $pdf->getPages();
 
// Loop over each page to extract text.
foreach ($pages as $page) {
    echo $page->getText();
}

 $textarray = explode(":",$text);
for($i=0;$i<count($textarray);$i++){
echo $i.") ".$textarray[$i]." : ".$textarray[$i+1];
echo "<br/><br/>";
$i++;
}
--

**Comment by k00ni** [comment]
Thank you.

Just a remark: `$i` is getting incremented two times in your for loop. Is that intentional?

**Comment by mano077** [comment]
if you have noticed i am printing echo $i.") ".$textarray[$i]." : ".$textarray[$i+1];

so increamented twice

**Comment by mano077** [comment]
My concern is with the text

**Comment by mano077** [comment]
Hello sir
Sir is there any update  on above issue ?

Thanks

**Comment by k00ni** [comment]
@mano077 As far as I am concerned, no.

I gathered all required information for now, so that we have a sufficient bug report. You will get notified if someone posts any updates here.

**Comment by mano077** [comment]
Hello Sir
any solution to the issue ?

**Comment by k00ni** [comment]
Hello @mano077, from my side still no.

I am not sure, if you are familiar with Open Source projects, but usually their people work on things they need themselves, except if they get paid. PDFParser is an Open Source project and we have a few people who contribute from time to time. As far as I can see, no one is working on this issue.

If you wanna get this issue solved faster, you could offer a bounty (e.g. in EUR).

**Comment by smalot** [comment]
Hi @mano077 
Can you check using the `issue-387` branch ?
