### ISSUE TITLE
Fatal error: Uncaught Exception: Object list not found. Possible secured file. in

### ISSUE THREAD

**Issue by BeycanDeveloper** [smalot/pdfparser#392]
https://prnt.sc/10477by

I am getting this error when I try to read a pdf file.

**Comment by k00ni** [comment]
Could you please give us feedback if #400 solves this problem?

**Comment by BeycanDeveloper** [comment]
Hello then, I could not solve my problem, I wrote here but I did not get an early return, so I took care of my work with apache tika and I deleted all the files, so the file that does not work in the pdf parser is not available now, so I cannot test it.

So I'd like to help but I guess I won't be. I also don't know how to use github, sorry I'm just learning.
