### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Object list not found. Possible secured file.'

### ISSUE THREAD

**Issue by sergey833** [smalot/pdfparser#397]
```
Fatal error: Uncaught exception 'Exception' with message 'Object list not found. Possible secured file.' in ...\src\Smalot\PdfParser\Parser.php:118 Stack trace: 
#0 ...\src\Smalot\PdfParser\Parser.php(97): Smalot\PdfParser\Parser->parseContent('%PDF-1.5\n%\xE2\xE3\xCF\xD3\n...') 
#1 ...\index.php(770): Smalot\PdfParser\Parser->parseFile('......') 
#2 {main} thrown in ...\src\Smalot\PdfParser\Parser.php on line 118
```

PDF loaded from https://elib.vsmu.by/bitstream/123/2275/1/Kabanova-SA_Osnovy%20cheliustno-litsevoj%20khirurgii_T-1_2011.pdf

**Comment by ppritcha** [comment]
We are experiencing this problem also.  It appears to be the same as #392, #373, #356, and #330.  #330 was reported on August 30 of last year.

@k00ni, Is there anything we can do to help get this resolved?

**Comment by k00ni** [comment]
Unfortunately I don't have the time to dive into that, but I will assist any pull request which aims to solve this issue. For what I saw until now, I assume that this library is not able (yet) to parse this kind of files.

**Comment by ppritcha** [comment]
I see now that this issue was first reported in 2014, in the earliest issue that is still open: #30   Also, #209, #192, #185 .  It's been reported about 9 times over the course of 7 years.   It appears to be a problem with the library not handling PDFs that are have a version > 1.4.

**Comment by k00ni** [comment]
Could you please give us feedback if #400 solves this problem?

**Comment by ppritcha** [comment]
That solves the problem for us.

**Comment by k00ni** [comment]
Thank you for your quick response.
