### ISSUE TITLE
Hebrew text displayed in reverse

### ISSUE THREAD

**Issue by bredisvictor** [smalot/pdfparser#398]
Hello, for first thank you for the great parser.
The issue that when i parsing documents in Hebrew, all the text displayed reverse.

Thank you.

**Comment by k00ni** [comment]
Can you provide a PDF (for our test suite) which causes this error? It must be free of charge and without any obligations.

**Comment by bredisvictor** [comment]
Hello Konrad,

Yes, sure, file attached.
[test_hebrew.pdf](https://github.com/smalot/pdfparser/files/6101117/test_hebrew.pdf)

It will help me very much, because my solution that fix it, not so good.

Thank you.

**Comment by k00ni** [comment]
Thank you for the PDF.

> It will help me very much, because my solution that fix it, not so good.

We had similar issues in the past. Can you post your solution here please? It might help to create a fix.

**Comment by bredisvictor** [comment]
My fix is very simple and not so good (need to think over all cases), I didn't have for this issue so much time (did it in an hour). I'm just filter output text and make reverse for every word, except for the text in english and numbers. The problem in this solution that some words stick together after pursing, and it not easy to separate it correctly.


```
class MyParser
{
    public static function parseToText($file)
    {
            $fileContent = (new \Smalot\PdfParser\Parser())->parseFile($file)->getText();
            if ((new self)->isHebrew($fileContent)) {
                $fileContent = (new self)->reverseHebrew($fileContent);
            }

        return $fileContent;
    }

    public function reverseHebrew($text)
    {
        $words = explode(' ', $text);
        foreach ($words as $index => $word) {
            if ($this->isHebrew($word)) {
                $words[$index] = $this->strReverse($word);
            } else {
                $words[$index] = $word;
            }
        }
        return join(' ', $words);
    }

    public function isHebrew($text)
    {
        for ($i = 0, $cnt = strlen($text); $i < $cnt; ++$i) {
            if (ord($text[$i]) > 127) {
                return true;
            }
        }
        return false;
    }

    public function strReverse($string, $encoding = null)
    {
        $charactersArr = preg_split('/(?<!^)(?!$)/u', $string);
        $lastCharacter = '';
        $result = [];
        $hebrewWord = [];
        foreach ($charactersArr as $character) {
            if ($this->isHebrew($character)
                || ($character == '.' && $this->isHebrew($lastCharacter))
                || ($character == ';' && $this->isHebrew($lastCharacter))
                || ($character == ',' && $this->isHebrew($lastCharacter))
                || ($character == ':' && $this->isHebrew($lastCharacter))) {
                $hebrewWord[] = $character;
            } elseif (empty(trim($character)) && $this->isHebrew($lastCharacter)
            || is_numeric(trim($character)) && $this->isHebrew($lastCharacter)
            || !$this->isHebrew(trim($character)) && $this->isHebrew($lastCharacter)) {
                $hebrewWord = array_reverse($hebrewWord);
                $result = array_merge($result, $hebrewWord);
                $result[] = ' ';
                if (!empty(trim($character)) || trim($character) == '0') {
                    $result[] = $character;
                }
                $hebrewWord = [];
            } else {
                $result[] = $character;
            }

            $lastCharacter = $character;
        }

        if (!empty($hebrewWord)) {
            $hebrewWord = array_reverse($hebrewWord);
            $result = array_merge($result, $hebrewWord);
        }

        return implode('', $result);
    }
}
```

**Comment by bredisvictor** [comment]
> @bredisvictor can you please test again with #402?
> 
> > I don't think that it will help you.
> 
> In my opinion it is better to have a half solution than nothing. Your code showed a way to deal with the problem. I am not sure but it might helped @smalot to create a patch faster.

I tested it and received the same result.
After debugging i found the reason. It never pass this case and condition.
![Screen Shot 2021-03-10 at 12 11 24 PM](https://user-images.githubusercontent.com/24625107/110614007-8fa78800-819a-11eb-95f4-5871a49e845f.png)

As a result, it is not enters to the part of the code that does reverse.
![Screen Shot 2021-03-10 at 12 12 21 PM](https://user-images.githubusercontent.com/24625107/110614592-2aa06200-819b-11eb-853b-b1a93fe9621b.png)

And i did some temporary solution that work
![Screen Shot 2021-03-10 at 12 14 37 PM](https://user-images.githubusercontent.com/24625107/110614771-59b6d380-819b-11eb-8f63-9033502aef97.png)

This condition checks the hebrew characters in the string
`mb_ereg('[\x{0590}-\x{05FF}]', $text)`

**Comment by bredisvictor** [comment]
> Hi @bredisvictor
> Did you try using the `test_hebrew.pdf` you provided ?
> If so, can you provide screenshots about what you expect to obtain and what you really obtain using the `issue-398` branch ?
> Many thanks

Hello Sebastien,

Yes, you are right, i am test it with other file, it turned out that `test_hebrew.pdf` parsed fine. But other file is not parsed. 
Also please look on numbers, looks like they are randomly scattered.
Try this file: 
[resumes_sample_Servicerepresentative.pdf](https://github.com/smalot/pdfparser/files/6117804/resumes_sample_Servicerepresentative.pdf)

In additional, i add one more example. In this case reverse is works, but words break into several parts.
[hebrew_test_2.pdf](https://github.com/smalot/pdfparser/files/6117865/hebrew_test_2.pdf)

Thank you

**Comment by k00ni** [comment]
Can we use these PDFs in our test environment? They must be free of charge and without any obligations.

**Comment by bredisvictor** [comment]
These are resume examples in hebrew downloaded from free, open source.

**Comment by smalot** [comment]
Adding support for right to left language makes me crazy.
When I handle parts of text, they seems to be good, but when I'm echoing on terminal.
And the mix of hebrew and ascii chars is really awful

**Comment by bredisvictor** [comment]
> Adding support for right to left language makes me crazy.
> When I handle parts of text, they seems to be good, but when I'm echoing on terminal.
> And the mix of hebrew and ascii chars is really awful

Can i help some how? Your parser very important for my business.

**Comment by GreyWyvern** [comment]
The Hebrew text in the sample documents are displaying in the correct direction. The only remaining issue left here is that they are spaced out unnaturally. This is a result of `decodeText()` not taking into account the scale factor from the text matrix `Tm` when deciding to add whitespace.
