### ISSUE TITLE
demo and multi page pdfs not working

### ISSUE THREAD

**Issue by hpvd** [smalot/pdfparser#416]
Just give the demo https://www.pdfparser.org/demo several tries to extract text from pdf's containing more than one page.
-> I could find no pdf where the pages beginning from page 2 where not empty.

questions:
1. is it (only) problem with the demo?
2. are there any multipage pdf files tested with every release which should always work?

other finding:
- demo shows "build failing",
- not lastest version of pdfparser used in demo

**Comment by hpvd** [comment]
looks like this is a major problem (not only in demo) see https://github.com/smalot/pdfparser/issues/331

**Comment by k00ni** [comment]
Can you provide us a demo PDF which we can include in our test environment. It must be free of charge and without any obligations.

**Comment by hpvd** [comment]
sure.
Article from wikipedia about pdf: https://en.wikipedia.org/wiki/PDF
Exported as pdf directly from wikipedia (left menu:  ->Print/export ->Download as PDF)
[Wikipedia-PDF.pdf](https://github.com/smalot/pdfparser/files/6397355/Wikipedia-PDF.pdf)

**Comment by hpvd** [comment]
Obviously this file shows other problems too, but it can be opend sucessfully with differnt readers....

**Comment by dejab** [comment]
This PDF does not parse any page.

[BulkPropanePriceIndex.pdf](https://github.com/smalot/pdfparser/files/6639577/BulkPropanePriceIndex.pdf)

**Comment by k00ni** [comment]
@dejab can we use your Propane PDF in our test environment? It must be free of charge and without any obligations.

**Comment by dejab** [comment]
Yes you can use the PDF for your test.

On June 13, 2021 11:57:17 PM PDT, Konrad Abicht ***@***.***> wrote:
***@***.*** can we use your Propane PDF in our test environment? It must be
>free of charge and without any obligations. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/smalot/pdfparser/issues/416#issuecomment-860431631

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rubenvanerk** [comment]
The Wikipedia pdf that @hpvd provided parses fine with master branch, I think this was an issue with the demo. It does need a horizontal offset of `''`.

The pdf @dejab provided only has images with text, so it can't be parsed to plain text.

**Comment by k00ni** [comment]
> The pdf @dejab provided only has images with text, so it can't be parsed to plain text.

Does it mean that this issue can't be solved and can be closed?

**Comment by rubenvanerk** [comment]
Yes. This library can't (and won't) extract text from images.
