### ISSUE TITLE
Local Parser behaves different to the online demo; several characters remain encoded

### ISSUE THREAD

**Issue by Externaluse** [smalot/pdfparser#425]
Whilst trying to extract some text from a PDF document, I get a result like this:
`designated point defined b\x0\x0\x3\x0U\x0H\x0I\x0H\x0U\x0H\x0Q\x0F\x0H\x0 \nto navigation aids`, whereas the online demo on pdfparser.org extracts this readable to `designated point defined by reference to navigation aids,`

The document is attached:
[2020Pruefungsfragen_AZF_pdf-1.pdf](https://github.com/smalot/pdfparser/files/6500186/2020Pruefungsfragen_AZF_pdf-1.pdf)

What might be a reason that text is extracted correctly for the most part, but that hundreds of such occasions are left intact? The PHP version is 7.4.16

**Comment by Externaluse** [comment]
Ah, damn, entirely my mistake. My composer.json had reverted to a previous' project parser version of 0.15 - Version 1.0 is working fine. Apologies!

**Comment by k00ni** [comment]
No problem, happens to the best.
