### ISSUE TITLE
How to get the page of an annotation?

### ISSUE THREAD

**Issue by hershkoy** [smalot/pdfparser#428]
I managed to read the annotation itself and it rectangle, but how do I get the page of the annotation?

Code so far:

```
include 'vendor/autoload.php';
 
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('data/file.pdf');
 
$annotations = $pdf->getObjectsByType('Annot');
foreach ($annotations as $obj) {
    if ($obj->has('Contents')) {
        var_dump($obj->get('Contents')->__toString());
        var_dump($obj->get('Rect')->__toString());
    }
}

```

**Comment by isavepak** [comment]
Hi hershkoy, if you find an answer, please do email me at flashpublisher [@] hotmail.com  or i will keep checking this post... thanks

**Comment by isavepak** [comment]
How can we get page annotation with page number??? please help

**Comment by k00ni** [comment]
To my knowledge that is not possible at the moment, because PDFParser doesn't seem to save required references.

**Comment by mikiqex** [comment]
Actually it is possible, the other way around - iterate over pages and getting Annotations:

```
include 'vendor/autoload.php';
 
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('data/file.pdf');

$pages = $pdf->getPages();
foreach ($pages as $i => $page) {
    $details = $page->getDetails();
    if (empty($details["Annots"])) continue;

    echo "\nPAGE ".($i + 1).":\n";
    $annots = $details["Annots"];
    foreach ($annots as $a) {
        if (empty($a["Contents"])) continue;
        echo $a["Contents"])."\n";
    }
}
```

**Comment by k00ni** [comment]
Thanks @mikiqex

**Comment by rdmpage** [comment]
Hi, the code above doesn't work for me. Using this code to iterate page by page returns nothing, even if the PDF has extensive annotations (which can be retrieved by getting objects from $pdf). Is it possible that it is thought that getting annotations for pages works, but it actually doesn't?

```
	$annotations = $pdf->getObjectsByType('Annot');
	foreach ($annotations as $annotation) 
	{
		if ($annotation->has('Subtype')) 
		{
			if ($annotation->get('Subtype')->__toString() == 'Link')
			{
				$details = $annotation->getDetails();
								
				if (isset($details['A']))
				{				
					echo $details['A']['URI']; // the URL
				}
			}
		}
	}
```

[CJSTOC.PDF](https://github.com/user-attachments/files/16824496/CJSTOC.PDF)
