### ISSUE TITLE
"BaseEncoding" should be optional

### ISSUE THREAD

**Issue by LucianoHanna** [smalot/pdfparser#432]
In `Encoding->getEncodingClass()`, if the field `BaseEncoding` doesn't exist, it throws an Exception but, accordingly PDF 1.5 Reference Table 5.11 (attached), the field `BaseEncoding` is optional, so, if any PDF builder don't put this field, pdfparser will crash.

![image](https://user-images.githubusercontent.com/22209724/121074908-e24d0c00-c7aa-11eb-876c-26731e9cef72.png)

**Comment by k00ni** [comment]
What do you suggest (including code changes)?
