### ISSUE TITLE
Document's object dictionary not used when asking for default font

### ISSUE THREAD

**Issue by jee7** [smalot/pdfparser#434]
From v0.17.0 a `PDFObject::getDefaultFont()` was asked in the beginning of `PDFObject::getText()` method. The `getDefaultFont()` asks for all the fonts inside a document and the first one is picked. The `Document::getFonts()` method uses `Document::getObjectsByType()`, which is uncached. Meaning it does not use the dictionary built inside the `Document` class, but rather loops through *all* the objects again, checking their type to find the fonts.

For PDF files with a lot of objects, this causes *significant* overhead. For example with the [PDF file from this page](https://comserv.cs.ut.ee/ati_thesis/datasheet.php?id=70198&year=2020&language=en). I apologize for not having a custom-made PDF here. With that PDF there is a drastic difference when parsing pages 77 and 78. With the v0.16.2 version both pages take < 0.1 seconds to parse. With versions starting from 0.17.0 (including the current latest version) they take ~300 seconds together.

![image](https://user-images.githubusercontent.com/3455815/121791624-a7a50280-cbf4-11eb-8b29-9d9ea7ccf639.png)

Test code:
```
<?php

include('vendor/autoload.php');

set_time_limit(720);

$parser = new \Smalot\PdfParser\Parser();

// load PDF file content
$data = file_get_contents('https://comserv.cs.ut.ee/home/files/Shoush_ComputerScience_2020.pdf?study=ATILoputoo&reference=76F6FAFD4C9E6981D9A434D32D2E7EE2AE9C49E7');


// give PDF content to function and parse it
$pdf = $parser->parseContent($data); 

$pages = $pdf->getPages();

foreach ($pages as $i => $page) { /** @var $page Page */
	if ($i < 77) continue;
	if ($i > 78) continue;

	$startTime = microtime(true);
	$pageText = $page->getText();
	$endTime = microtime(true);
	
	echo '<b>Page ' . $i . ' (took ' . ($endTime - $startTime) . ' seconds, ' . round(memory_get_usage() / (1000 * 1000), 2) . ' MB RAM)</b><br>';
	var_dump($pageText);
	echo '<br><br>';
}

?>
```

When getting the text for all the pages (not just 77, 78), then the script doesn't seem to complete (Apache crashed at one point). The main issues here seems to be that the dictionary cache is not used and thus this huge number of calls to the `Header::get()` and other functions create an overhead. This is even more unnecessary as only the first font is actually required.

PR coming up.

**Comment by k00ni** [comment]
Whats the status of this issue after the PR was merged?

**Comment by jee7** [comment]
Yes, tested it and v1.1 now runs in comparable time performance with v0.16.2 for me.
