### ISSUE TITLE
Getting '??' characters from getText() out of swiss german doc

### ISSUE THREAD

**Issue by redskate** [smalot/pdfparser#44]
Hi Sébastien 
first of all my compliments for your pdf2text library - very useful!

I am getting strange characters '??' in words like 'S??henkungen' - in thi case the '??' stands for 'c' - for german documents like the one I attach here with a (false) image extension in order to upload it (please download the file and change the ext to .pdf).

Do you know where and why this happens and what I could do to avoid getting this effect?
Thank you so much in advance
Regards
Fabio

![dp_erbschaftssteuer_20140526 pdf](https://cloud.githubusercontent.com/assets/977837/3840919/c3296d00-1e24-11e4-8fbf-da58ca170bb8.png)

**Comment by davispuh** [comment]
Try #257 PR it should be fixed there.

**Comment by Connum** [comment]
I can confirm that this was fixed with 4f4fd108270c32c0e81ea3dceaac2249162f27dc. Several instances of the word "Schenkungen" are now intact and I can see no other decoding issues.

**Comment by k00ni** [comment]
@Connum: Thank you for checking it.
