### ISSUE TITLE
Huge time parsering a signed PDF

### ISSUE THREAD

**Issue by klode82** [smalot/pdfparser#444]
I'm working on a platform using signed PDF. The parsering of these files require about 30 seconds when they has one or more signatures; the unsigned version require more less than 1 second.

I'm working on PHP 5.3

This is a demo code:
`$parser = new Smalot\PdfParser\Parser();`
`$pdf = $parser->parseFile($file);`
`$content = $pdf->getText();`

**Comment by k00ni** [comment]
Which version of PDFParser do you use?

Be aware that we currently **only** support PHP 7.1 or newer. Please test again with the latest version (1.0.2 or `master` branch) and get back to me, if problem persists. Closed in the meantime, because of unsupported PHP version.
