### ISSUE TITLE
Parsing PDF and generating HTML

### ISSUE THREAD

**Issue by qwertynik** [smalot/pdfparser#446]
Hello,

Fairly new to this library, wanted to know if any of you guys managed to generate HTML with the parsed data from this library.

Would be great if you guys could share some sample code doing the same.

Thanks!

**Comment by izabala** [comment]
I am answering some of this stuff in the Issue #449, on how to use getTextXY and getDataTm methods. 
The other thing you can do is getting all the text with the getText methods and use Regex or other way to get the text you need.
I believe we can close this one.

**Comment by k00ni** [comment]
> I believe we can close this one.

OK. @qwertynik please reopen, if your issue still stands.
