### ISSUE TITLE
ISSUE in pdf Parser 

### ISSUE THREAD

**Issue by sonias-redian** [smalot/pdfparser#447]
I am using PDF Parser in my scrapping from a long time. Now All of sudden it is not working. On file upload, I am getting error "Page is not working " .
My Server configurations are:
PHP 5.3

Also, I have downloaded the code in my local server and i am getting error "Missing Catalog" error.
My Server configurations are
PHP 5.6

Please help me to rectify this issue

**Comment by k00ni** [comment]
Which version of PDFParser do you use?

Be aware that we currently **only** support PHP 7.1 or newer. Please test again with the latest version (1.0.2 or `master` branch) and post your results here, if problem persists. Closed in the meantime, because of unsupported PHP version.
