### ISSUE TITLE
PDF Parser can't correctly read DynaPDF created files

### ISSUE THREAD

**Issue by BPMB** [smalot/pdfparser#45]
First off, great library - awesome work! :)
I have tested with several PDFs made by different enginee, for the most part this works flawlessly.
However, any PDF made by DyanPDF causes the read text to be garbled - maybe encoded?
I am happy to provide several examples.

**Comment by k00ni** [comment]
Hey, if you are still using this library it would be great if you could try again with our latest release and get back to us. Thank you.
