### ISSUE TITLE
csv file is coming empty on server while using pdf parser

### ISSUE THREAD

**Issue by sonias-redian** [smalot/pdfparser#451]
I have uploaded all the content on ubuntu server and it converts the pdf into csv but the csv is coming empty . Can you please help

**Comment by k00ni** [comment]
Its not really clear if that is a PDFParser issue. Please provide your code which converts the PDF into CSV.

**Comment by sonias-redian** [comment]
Hi Actually it is working fine in our local environment . It successfully showing csv with records. Issue is coming on live server that is ubuntu

**Comment by k00ni** [comment]
We can't help you without any further information. I will close this for now, until further information is provided.
