### ISSUE TITLE
getText() returns empty string

### ISSUE THREAD

**Issue by Rain-YuXia** [smalot/pdfparser#456]
Hi, I'm working with Laravel, and just installed the package with composer.

Getting metadata from pdf is working fine, count of pages array is correct, but getText() always return an empty string.

I digged into this function and found `getText()` in PDFObject file. In this function, `$sections = $this->getSectionsText($this->content);` sections are empty for me. I guess that's the issue but I don't know why

Here is my codes in controller. Please help

```
  $parser = new Parser();
  $pdf = $parser->parseFile(resource_path('test.pdf'));

  $pages  = $pdf->getPages();
  foreach ($pages as $page) {
      $text = $page->getText();
      dd($text);
  }
```

**Comment by Rain-YuXia** [comment]
@k00ni Hi the pdf is just a sample downloaded from Adobe, it's working fine in the official website demo page. So there must be something wrong in my local. 
But this package doesn't require any config, right? What else could cause the issue:(

**Comment by k00ni** [comment]
> it's working fine in the official website demo page. So there must be something wrong in my local.

PDFParser running on demo page may be outdated and not the same you run locally. Which version do you use? What PHP version do you run?

> But this package doesn't require any config, right? What else could cause the issue:(

Config is optional, default should work out of the box.

**Comment by Rain-YuXia** [comment]
@k00ni Hi, thank you for reply. The package version is v1.1.0 and I'm using PHP 7.4.12.

Adobe sample pdf is working on my local today all of sudden... but still return empty string with my real pdf.

I know it's hard for you to debug without that pdf, unfortunately I can't share it with you bc it's confidential :(

**Comment by k00ni** [comment]
You could try to replicate your web hosting using Docker/container, maybe it shows the difference. Maybe its a PHP setting, maybe RAM.

**Comment by k00ni** [comment]
Closed for now, please reopen if you have further information.
