### ISSUE TITLE
Library crash when I tried to parse an 1.3 PDF file

### ISSUE THREAD

**Issue by andres28ramirez** [smalot/pdfparser#458]
I'm trying different methods but it gaves me this result as error:
count(): Parameter must be an array or an object that implements Countable 
This happend in the line (261) of the Parser:

\vendor\\smalot\\pdfparser\\src\\Smalot\\PdfParser\\Parser.php(261)

[12249.pdf](https://github.com/smalot/pdfparser/files/7108200/12249.pdf)

**Comment by GreyWyvern** [comment]
The sample file [12249.pdf](https://github.com/smalot/pdfparser/files/7108200/12249.pdf) extracts without error in the latest v2.7.0 release.
