### ISSUE TITLE
Word-Generated PDFs Parsed Strangely

### ISSUE THREAD

**Issue by msypes** [smalot/pdfparser#47]
I know Microsoft Word is always a a PITA, but it is commonly used. When a PDF generated from a Word document is parsed and the text extracted, I get back a string with percent signs instead of spaces and no new lines. You can test this even on your demo page (http://www.pdfparser.org/demo):
1) Create a document in Word, and generate a PDF from it. (I've tried both Word's "Save As ..." and Mac's "Print As ...")
2) Upload the file on the demo page.
3) Look at the parsed text: (There is a new line between PDF & This.)
![screen shot 2014-09-24 at 10 30 29 am](https://cloud.githubusercontent.com/assets/4096443/4392630/883e35ba-4410-11e4-8169-c760dcca2227.png)

**Comment by darrencraig** [comment]
+1 on this. Thanks.

**Comment by andrewhancox** [comment]
I have also had this issue.
I have traced the issue through to the \Smalot\PdfParser\Font::translateChar function where it seems to return the character if it cannot decode it using the translation table.
I spent some time looking at the \Smalot\PdfParser\Font::loadTranslateTable function but do not know enough about the PDF standard to fix it. My work around is to change the \Smalot\PdfParser\Font::translateChar function:

    public function translateChar($char, $use_default = true)
    {
        $dec = hexdec(bin2hex($char));

        if (array_key_exists($dec, $this->table)) {
            $char = $this->table[$dec];
        } else {
            $char = ($use_default ? self::MISSING : $char);
        }

        return $char;
    }

to

    public function translateChar($char, $use_default = true)
    {
        $dec = hexdec(bin2hex($char));

        if (array_key_exists($dec, $this->table)) {
            $char = $this->table[$dec];
        } else {
            $char = ' ';
        }

        return $char;
    } 

Which is obviously far from ideal but good enough for my purposes.

**Comment by k00ni** [comment]
Hey, if you are still using this library it would be great if you could try again with our latest release and get back to us. Thank you.
