### ISSUE TITLE
Encoding issues with backslashes

### ISSUE THREAD

**Issue by nativemad** [smalot/pdfparser#470]
Hi

I have a pdf (or better a lot of pdfs from the same source) that I'd like to parse, but the output is somehow wrong encoded with backslashes between chars.
I can't figure out why or how I could decode it again.
I tried with v1.2.0-RC2 and master.
[womopepper.pdf](https://github.com/smalot/pdfparser/files/7364917/womopepper.pdf)
I would be glad if someone could have a look.
Thanks in advance!

**Comment by GreyWyvern** [comment]
This issue can be fixed by loosening the regexp in `decodeOctal()` in **Font.php**. It currently only looks for three digit octal codes such as `\035`, but the example PDF contains mostly single or double digit octal codes like: `\3\4\52`. Change the regexp to look for one, two and three digit escaped octals.

**Current:**
``php
    /**
     * Decode string with octal-decoded chunks.
     */
    public static function decodeOctal(string $text): string
    {
        $parts = preg_split('/(\\\\[0-7]{3})/s', $text, -1, \PREG_SPLIT_NO_EMPTY | \PREG_SPLIT_DELIM_CAPTURE);
        $text = '';

        foreach ($parts as $part) {
            if (preg_match('/^\\\\[0-7]{3}$/', $part)) {
                $text .= \chr(octdec(trim($part, '\\')));
            } else {
                $text .= $part;
            }
        }

        return $text;
    }
```

**Fixed:**
```php
    /**
     * Decode string with octal-decoded chunks.
     */
    public static function decodeOctal(string $text): string
    {
        $parts = preg_split('/(\\\\[0-7]{1,3})/s', $text, -1, \PREG_SPLIT_NO_EMPTY | \PREG_SPLIT_DELIM_CAPTURE);
        $text = '';

        foreach ($parts as $part) {
            if (preg_match('/^\\\\[0-7]{1,3}$/', $part)) {
                $text .= \chr(octdec(trim($part, '\\')));
            } else {
                $text .= $part;
            }
        }

        return $text;
    }
```

**Comment by k00ni** [comment]
@GreyWyvern does it make sense to do a PR with your changes?

**Comment by GreyWyvern** [comment]
> @GreyWyvern does it make sense to do a PR with your changes?

I have it changed in my test env and I'm checking to see if it breaks anything.

It fails one of the unit tests in `testDecodeOctal()`. Previously it would ignore the \\199 in the third test, but now it translates the \\1 as an octal and the result is 'AB <0x01>99'.

I think this is probably the correct behavior? I will look into it more.
