### ISSUE TITLE
PDF only being partly read.

### ISSUE THREAD

**Issue by bclarkson72** [smalot/pdfparser#474]
Have many PDF invoices that are able to be read fine by the library.  But the odd one just does not return the full document

[Reads Fine.pdf](https://github.com/smalot/pdfparser/files/7425973/Reads.Fine.pdf)
[Bad Read.pdf](https://github.com/smalot/pdfparser/files/7425974/Bad.Read.pdf)

I cannot see any difference in the files at all.

**Comment by k00ni** [comment]
@bclarkson72 can you please test if #533 fixes your problem?
