### ISSUE TITLE
PDF Version 

### ISSUE THREAD

**Issue by redskate** [smalot/pdfparser#48]
Hi Sebastien

Your lib pdfparser is doing pretty well.

I'm having problems with a specific PDF - maybe too old?? V 1.3.
Instead of extracting the german words it returns texts like below (text tokenized by blanks & newlines)

"30 07 12NHXH ZXHUFKHU ZHLWXQJ YRP 28 07 2012 1/2 WIRTSCHAFTSPOLITISCHE GRAFIK IQGXVWULHPDFKW SFKZHLz DHU MyWKRV GHU DH-IQGXVWULDOLVLHUXQJ G S · DLH KODJH KDW GHQ AXWRU GLHVHU ZHLOHQ IDVW VHLQ JDQzHV EUZDFKVHQHQOHEHQ ODQJ EHJOHLWHW DLH SFKZHLz GHLQGXVWULDOLVLHUH VLFK LPPHU PHKU LKU WRKOVWDQG ZHUGH IDVW QXUPHKU XQG YLHO zX YLHO YRQ BDQNHQ VHUVLFKHUXQJHQ XQG GHP TRXULVPXV JHWUDJHQ GHU WHUNSODWz VHL GDJHJHQ DP VHUVFKZLQGHQ ZXUzHLW KDW GLH KODJH DQJHVLFKWV GHU FUDQNHQVWlUNH JHUDGHzX HRFKNRQMXQNWXU UQG zXP HUVWHQ MDO VHLW JDKUzHKQWHQ VFKHLQW VLH "

I could close an eye on that (PDF version too old) if I could read the PDF Version information from that PDF (whose version is 1.3) and issue a warning.

Could you give me please some hints? If the PDF is too old to be extracted with pdfparser, could you give me please a hint how to extract per program the version of that PDF ?

Thank you very much in advance
Regards
Fabio

**Comment by k00ni** [comment]
Hey, if you are still using this library it would be great if you could try again with our latest release and get back to us. Thank you.
