### ISSUE TITLE
Undefined array key when calling getDataTm()

### ISSUE THREAD

**Issue by ngekoding** [smalot/pdfparser#482]
I have a simple code like this:

```php
require_once 'vendor/autoload.php';

$file = 'path/to/file.pdf';

$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile($file);
$pages = $pdf->getPages();

$firstPage = $pages[0];

// Get data matrix
$firstPageDm = $firstPage->getDataTm();

echo '<pre>';
var_dump($firstPageDm);
```

And got this error message:

<img width="643" alt="Error" src="https://user-images.githubusercontent.com/11625690/142115234-71a9b5fb-8ced-43dd-bec9-df6df4328caa.png">

Is this caused by wrong array access?
From what I found in the code, is that mean want to get the last array element?

I use version ^2.0, the code in line 675.

https://github.com/smalot/pdfparser/blob/ce6aa779dd67fadf3887dace6f31ea70882dba73/src/Smalot/PdfParser/Page.php#L584

Any solution?

Btw thanks for this awesome library.

**Comment by k00ni** [comment]
Can you provide us the PDF you are using? It must be free of charge, without any obligations and may be added to our test environment.

**Comment by ngekoding** [comment]
Sorry for the late reply.

Unfortunately this is a private PDF document, I was try to split the document to test again (after removing some sensitive data), but the error only comes when I use the original document.

I will try to find any document which have same problem soon.

**Comment by ngekoding** [comment]
But, I found different error for a different document, error code line is different, here I attach the error message and document.

<img width="1053" alt="Error" src="https://user-images.githubusercontent.com/11625690/142340572-b7b7ee83-6720-4479-8fa8-ee960c279f43.png">

[file-example.pdf](https://github.com/smalot/pdfparser/files/7559366/file-example.pdf)

The code:

```php
require_once 'vendor/autoload.php';

$file = 'file-example.pdf';

$parser = new Smalot\PdfParser\Parser();
$pdf = $parser->parseFile($file);
$pages = $pdf->getPages();

$pageTm = $pages[0]->getDataTm();
```

**Comment by k00ni** [comment]
Thank you for your detailed bug report and the example PDF.

**Comment by izabala** [comment]
I got it. The command 'Td' has a "\n" between the two numbers (that were not expected), when it make the split, it just get one.  I will work on a fix for that.

**Comment by izabala** [comment]
Create the pull#485 with a fix over this.

**Comment by ngekoding** [comment]
Sorry guys, after trying some PDF documents I can't get the same error (about line 675 

> Sorry for the late reply.
> 
> Unfortunately this is a private PDF document, I was try to split the document to test again (after removing some sensitive data), but the error only comes when I use the original document.
> 
> I will try to find any document which have same problem soon.

Sorry guys, after trying some PDF documents I can't get the same error for this. But, after read @izabala comment on https://github.com/smalot/pdfparser/pull/485#discussion_r753401829 (wrong PDF formatted file), I try to compress the file with an online tool (I use smallpdf.com) and with the compressed file **the error is gone**!

I don't know why, because that PDF is generated from the application provided by the university, and from the file properties it looks it generated with mPDF as shown below.

<img width="265" alt="File Info" src="https://user-images.githubusercontent.com/11625690/142742718-3c0ffa4f-0494-48f1-96ad-d461e2170f20.png">

**Comment by izabala** [comment]
@ngekoding Thanks for this update.  @k00ni I let you decide if we need to close this issue and if we need to close the pull request, because if this is a wrong formatted pdf, no changes to the code should be done.

Thanks.

**Comment by k00ni** [comment]
See my feedback in #485. Closed for now.

**Comment by ngekoding** [comment]
FYI for who are have the same problem with me, for the unsupported PDF file.
I try to use Ghosh Script to convert the file, and PdfParser can processed it normally.

For my case, the PDF version is 1.4 (generated by mPDF), and I use this command to convert it (still on version 1.4).

```sh
gs sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=fixed-file.pdf original-file.pdf
```

Without `-dPDFSETTINGS=/printer` is still worked.

Hope this can help.
