### ISSUE TITLE
PHP 8 seems to be required for v2.0.0

### ISSUE THREAD

**Issue by dpanzer** [smalot/pdfparser#483]
Rather than just supported, it seems PHP 8 is a _requirement_ for v2.0.0 (and for 1.2.0-RC2) based on the usage of `str_starts_with()` here: https://github.com/smalot/pdfparser/blob/f5fa4d3e6415cbf558d1e9c46804ab79ebe2574f/src/Smalot/PdfParser/Page.php#L239

As per PHP docs, that function has only existed since PHP 8 (https://www.php.net/manual/en/function.str-starts-with.php)

So I believe the PHP version requirement in `composer.json` needs to be upped to 8.0 rather than 7.1

**Comment by k00ni** [comment]
Good catch! I replaced `str_starts_with` to avoid that problem. Can you check #486 please?

**Comment by dpanzer** [comment]
@k00ni Looks good!
