### ISSUE TITLE
Getting false "Secured pdf file are currently not supported."

### ISSUE THREAD

**Issue by parijke** [smalot/pdfparser#488]
I have a PDF that, when trying to parse the parser says
Secured pdf file are currently not supported.

![image](https://user-images.githubusercontent.com/7671998/142625431-6cb7e113-5f3b-4fae-9957-78f9580d6dbe.png)

Sounds like a false positive to me?

**Comment by k00ni** [comment]
Can you provide us the PDF? We would like to include it in our test environment, therefore it must be free of charge and without any obligations.

**Comment by parijke** [comment]
I've looked into it. If I comment out line 102 - 104 in the Parser, the file get parsed. The problem is, that the trailer HAS a reference to /Encrypt:

here's the trailer:
```
trailer

<<
/Encrypt 17 0 R
/Info 18 0 R
/Root 16 0 R
/Size 19
/ID [<8f6e73e43f6fc457c6d42783e4005ec4><624b2ff302bbf94e2e0f53c90933b5c1>]
>>
startxref
28499
%%EOF
```

/Encrypt [dictionary]: Specifies the document’s encryption dictionary.

But is does not use it. The file is not encrypted. 

So testing a pdf on the value encrypt is not fail safe to really test for secured files.

**Comment by parijke** [comment]
[test.pdf](https://github.com/smalot/pdfparser/files/7576214/test.pdf)

Here's an example file. I created it using LibreOffice. While exporting to PDF, I set the WRITE password, but not the READ password.

So it is not encrypted for reading, which is the case in the file I encountered this at first as well.

Now you have a test file

**Comment by k00ni** [comment]
Thank you for your detailed feedback. I hope someone can pick up the ball and writes a fix.

**Comment by parijke** [comment]
I am looking into it. Looks like the answer could be found here:
https://github.com/empira/PDFsharp/blob/3205bd933b464d150c0f42e8bcdff3314b6c6164/src/PdfSharp/Pdf.Security/enums/PdfUserAccessPermission.cs

**Comment by parijke** [comment]
Additional explanation
https://www.cs.cmu.edu/~dst/Adobe/Gallery/anon21jul01-pdf-encryption.txt

**Comment by EthosLuke** [comment]
Any progress on this?

**Comment by k00ni** [comment]
Not to my knowledge, sorry.

**Comment by k00ni** [comment]
#653 should provide a valid work around until there is a better solution/fix.
