### ISSUE TITLE
Using PHP 7.4 get error!

### ISSUE THREAD

**Issue by ngekoding** [smalot/pdfparser#489]
As in documentation says, it requires PHP 5.3

> This library requires PHP 5.3.

<img width="599" alt="Docs" src="https://user-images.githubusercontent.com/11625690/142742132-2b77f3eb-eb80-475c-9029-10ddad34dc70.png">

And I try to use PHP 7.4, installing with Composer with got version `^2.0`
But when trying run a code, it give an error which I khow a function from PHP 8

Here is my code and the error.

```php
use Smalot\PdfParser;

require 'vendor/autoload.php';

$file = '../files/file-example.pdf';

$parser = new PdfParser\Parser();
$pdf = $parser->parseFile($file);
$details = $pdf->getDetails();
$pages = $pdf->getPages();

$pageTm = $pages[0]->getDataTm();
```

The error:

<img width="874" alt="Error" src="https://user-images.githubusercontent.com/11625690/142742122-e6f325a5-9f55-4e60-961f-fbdc42b584e8.png">

**Comment by k00ni** [comment]
Unfortunately, pdfparser.org is outdated. Current version of PDFParser is 2.0.0 and it requires at least PHP 7.1.

We know about the problem with `str_starts_with` and a patch is on the way: #486.

**Comment by ngekoding** [comment]
So if I manually change that code it will working with PHP 7.4?

**Comment by k00ni** [comment]
Based on our CI, yes.

**Comment by ngekoding** [comment]
Thank you, I will try it now and give a result.

**Comment by ngekoding** [comment]
Thank you @k00ni, the code running well on PHP 7.4. 

I just add str_starts_with function:

```php
if ( ! function_exists('str_starts_with'))
{
    function str_starts_with($string, $query) {
        return substr($string, 0, strlen($query)) === $query;
    }
}
```
