### ISSUE TITLE
Is it possible to "re-encode" a pdf before parsing it

### ISSUE THREAD

**Issue by noshaf** [smalot/pdfparser#49]
Right now I am parsing pdf event tickets for people, however the problem I am encountering is that if someone changes the pdf either by combining multiple files into one file or omitting certain text, the format immediately changes greatly depending on own operating system. 

For example, I get a ticket from Stubhub and the PDF "Producer" or "Encoder" is itext-paulo-155 and then I save it on my computer and it turns into Mac OS X 10.7.5 Quartz PDFContext. The formats between the two are no where near the same, and if I have to account for every type of PDF encoder out there it will be a lot of work to write that many scripts.

Is there any possible way that a script could "re-encode" or "re-produce the pdf using some sort of script so that the Producer is always the same and that way the format will always be consistent? If so I think this could be a great addition.

**Comment by k00ni** [comment]
Sorry for the late reply. Its out of scope.
