### ISSUE TITLE
The ö, ü and ç characters sometimes appear as �

### ISSUE THREAD

**Issue by Reqrefusion** [smalot/pdfparser#495]
These two characters are Turkish characters. However, they sometimes appear neatly in the text, and sometimes they appear as �.

```
Teklif Usul�� ile,
İhale Tarihi ve Saati 14.12.2021 Salı Saat 11.00
Şartname ve Ekleri
Ergene Belediyesi Emlak ve İstimlak Müdürlüğünde bedelsiz
olarak g�r�lebilir. Ancak ihaleye teklif verecek isteklilerin ihale
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-3-3.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-3-3.pdf)

```
ilişkin olarak, “Yükseköğretim Kurumlarında Yabancı Dil Öğretimi ve Yabancı Dille Öğretim
Yapılmasında Uyulacak Esaslara İlişkin Yönetmelik”in 8. maddesinin 7. fıkrasında belirtilen
şartlardan en az birinin sağlandığına dair belge ibraz edilmesi gerekmektedir.)
Birimi Bölümü Anabilim Dalı Dr. Öğr. Üyesi Aranan Nitelikler
Fen - Edebiyat Fak�ltesi Fizik Genel Fizik 1 (a), (b)
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-8.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-8.pdf)

```
Fakültesi
Maliye ve
Ekonomi Ekonomi Doktor Öğretim
�yesi (12)* 1 1
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-9.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-9.pdf)

```
2021/25 Tıp Fakültesi Dekanlığı Dahili Tıp Bilimleri Kardiyoloji Profes�r N N İlgili alanda doçentlik unvanına sahip olmak.
2021/2S Tıp Fakültesi Dekanlığı Cerrahi Tıp Bilimleri Patoloji Profes�r N N İlgili alanda doçentlik unvanına sahip olmak.
2021/2T Tıp Fakültesi Dekanlığı Cerrahi Tıp Bilimleri Genel Cerrahi Profes�r N N İlgili alanda doçentlik unvanına sahip olmak.
2021/2U Tıp Fakültesi Dekanlığı Cerrahi Tıp Bilimleri Kalp ve Damar Cerrahisi Dr.Öğretim �yesi 2 N Kalp ve Damar Cerrahisi alanında uzmanlığını almış olmak.
2021/29 Tıp Fakültesi Dekanlığı Cerrahi Tıp Bilimleri Kadın Doğum ve Hastalıkları Dr.Öğretim �yesi 2 N Kadın Doğum ve Hastalıkları alanında uzmanlığını almış olmak.
2021/30 Tıp Fakültesi Dekanlığı Dahili Tıp Bilimleri Kardiyoloji Dr.Öğretim �yesi 2 N Kardiyoloji alanında uzmanlığını almış olmak.
2021/3N Tıp Fakültesi Dekanlığı Dahili Tıp Bilimleri Acil Tıp Dr.Öğretim �yesi 3 N Acil Tıp alanında uzmanlığını almış olmak.
2021/32 Tıp Fakültesi Dekanlığı Dahili Tıp Bilimleri Çocuk Sağlığı ve Haslıkları Dr.Öğretim �yesi 4 N Çocuk Sağlığı ve Hastalıkları alanında uzmanlığını almış olmak.
2021/33 Tıp Fakültesi Dekanlığı Dahili Tıp Bilimleri İç Hastalıkları Dr.Öğretim �yesi 4 N İç Hastalıkları alanında uzmanlığını almış olmak.
```

Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-15.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-15.pdf)
```
Kariyer Uygulama ve Araştırma Merkezinde g�revlendirilmek �zere; Fakültelerin Psikoloji Bölümü, Eğitim Fakültelerinin Rehberlik ve Psikolojik Danışmanlık Bölümü, İktisadi ve İdari Bilimler Fakültelerinin ve İktisadi ve İdari Bilimler Fakültesine eşdeğer fakültelerin tüm bölümlerinin birinden lisans mezunu olmak ve bu bölümlerle ilgili alanlardan birinden tezli yüksek lisans mezunu olmak. Belgelendirmek şartıyla lisans mezuniyeti sonrası; aşağıdaki alanların herhangi birinde kurgulama- geliştirme-yazım-yürütme süreçlerinde en az 2 yıl tecrübe sahibi olmak: • Proje döngüsü, • Ulusal ve uluslararası destek programları (TÜBİTAK, KOSGEB, Bakanlıklar, Kalkınma Ajansı, AB projeleri), • Girişimcilik - İnovasyon (Yenilikçilik).
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-17.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-17.pdf)

```
Fen Fak�ltesi Bartın Üniversitesi Kutlubey Yerleşkesi Fen Fakültesi Dekanlığı Merkez/Bartın 0378 501 10 00 (2270)
0378 501 10 00 (2271) fen@bartin.edu.tr
Sağlık Bilimleri Fakültesi Bartın Üniversitesi Ağdacı Yerleşkesi Sağlık Bilimleri Fakültesi Merkez/Bartın 0378 223 52 36
0378 223 53 84 sbf@bartin.edu.tr
Spor Bilimleri Fak�ltesi Bartın Üniversitesi Kutlubey Yerleşkesi Spor Bilimleri Fakültesi Dekanlığı
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-20.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-20.pdf)

```
G�r. S�z. Edebiyat veya Fen -Edebiyat Fakültelerinin İngiliz Dili ve Edebiyatı Bölümü
mezunu olup bu alanda yüksek lisans yapıyor olmak.
T�rk Di li ve Edebi yatı Eski Türk Di li 1 7 Arş.
G�r. S�z. Edebiyat veya Fen -Edebiyat Fakültelerinin Türk Dili ve Edebiyatı Bölümü
mezunu olup Eski Türk Dili alanında yüksek lisans yapıyor olmak.
TariÜ Orta Çağ 1 6 Arş.
G�r. S�z. Edebiyat veya Fen -Edebiyat Fak�ltelerinin Tarih B�l�m� mezunu olup Orta
Çağ Tarihi alanında yüksek lisans yapıyor olmak.
```
Related file:[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-22.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/11/20211130-4-22.pdf)

**Comment by Reqrefusion** [comment]
Other files with this error:
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-1.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-1.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-11.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-11.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-12.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-12.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-13.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-13.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-14.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-14.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-15.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-15.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-16.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-16.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-18.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-18.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-19.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-19.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-20.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-20.pdf) (There is a problem with the letter "ç" here)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-21.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211201-4-21.pdf)

**Comment by Reqrefusion** [comment]
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-3-6.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-3-6.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-3-7.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-3-7.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-8.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-8.pdf)
```
Felsefe ve Din Bilimleri
B�l�m� Din Felsefesi
Anabilim Dalı
Do�ent N N
Doçentlik unvanını Felsefe ve Din Bilimleri Bilim alanında
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-9.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-9.pdf)

[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-12.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-12.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-13.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-13.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-14.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211202-4-14.pdf)

**Comment by Reqrefusion** [comment]
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-12.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-12.pdf)

```
1 MARDİN ARTUKLU ACAR 123 1 6357,23 m² E=0.70 H=15.50 m 2.542.892,00 TL 76.286,76 TL 14.12.2021 09:00
2 MARDİN ARTUKLr ACAR 124 N 7536,91 m� E=0.70 H=15.50 m 3.014.764,00 Ti 90.442,92 TL 14.12.2021 09:4R
3 MARDİN ARTUKLU ACAR 125 1 5470,91 m² E=0.70 H=15.50 m 2.188.360,00 TL 65.650,80 TL 14.12.2021 10:30
4 MARDİN ARTUKLr ACAR 12S N 8690,90 m� E=0.70 H=15.50 m 3.476.392,00 Ti 104.291,76 Ti 14.12.2021 11:1R
R MARDİN ARTUKLU ACAR 131 1 10779,35 m² E=1.00 H=15.50 m 4.850.707,50 TL 145.521,23 TL 14.12.2021 12:00
6 MARDİN ARTUKLr ACAR 13O N 12189,71 m� E=1.00 H=15.50 m 5.485.369,50 Ti 164.561,09 Ti 15.12.2021 09:0M
T MARDİN ARTUKLU ACAR 133 1 14627,36 m² E=1.00 H=15.50 m 6.582.312,00 TL 197.469,36 TL 15.12.2021 09:45
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-17.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-17.pdf)

```
N Dilek�e N Dilek�e
O Noter tasdikli imza beyannamesi veya imza sirk�leri O N�fus C�zdan Sureti
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-18.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-3-18.pdf)

[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-8.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-8.pdf)

```
M�hendislik
ve Mimarlık
Fak�ltesi
End�stri
Mühendisliği Bölümü
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-11.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-11.pdf)

[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-13.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-13.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-15.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-15.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-17.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-17.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-18.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-18.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-19.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-19.pdf)
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-20.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211203-4-20.pdf)

**Comment by Reqrefusion** [comment]
```
Fen -Edb . Fakült esi Psikoloji Klinik Psikolo ji Dr. Öğr. Üyesi 3 1 Psikoloji mezunu olup, ilÖ ili alanda doktora yapmış o lmak.
Fen -Edb. Fak�lt esi Psikoloji Sosyal Psikoloji Dr. Öğr. Üyesi 3 1 Sosyal Psikoloji alan ında doktora yapmış o lmak.
Hukuk Fak�ltesi Kamu Hukuku İdare Hukuku Do�ent 1 1 Hukuk Fak�ltesi mezunu o lup, alanında doçent liğini al mış olmak.
Hukuk Fak�ltesi Kamu Hukuku Anayasa Hukuku Dr. Öğr. Üyesi 3 1 Hukuk Fak�ltesi mezunu o lup, An ayasa Hukuku alanında doktora yap mış olmak.
Hukuk Fak�ltesi Kamu Hukuku Genel Kamu Hukuku Dr. Öğr. Üyesi 3 1 Hukuk Fakültesi mezunu ol up, Genel Kamu Hukuku alan ında doktora yap m ış
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211204-4-7.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211204-4-7.pdf)

**Comment by Reqrefusion** [comment]
```
Ge�ici
Kaks:1,50 (~1.691,88 m�F %18 13.000.000,00 390.000,00 14.02
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211205-3-5.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211205-3-5.pdf)

`Finansal Y�netim, Muhasebe ve Finans Y�netimi, Maliye,`
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211205-4-5.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211205-4-5.pdf)

**Comment by Reqrefusion** [comment]
`UNVANI SAYI PUAN T�R� ÖĞRENİM DURUMU VE ARANAN NİTELİKLER`
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-3-6.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-3-6.pdf)

`DALI UNVAk DERECE ADET A�IKLAMALAR`
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-8.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-8.pdf)

`B İR İM B�L�j ANABİLİM DALI UNVAk DERECE ADET *ADAYLARDA ARANAN ŞARTLAR`
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-10.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-10.pdf)

```
�nasya Arkeolojisi
Anabilim Dalı
Arkeoloji programında doktora yapmış olmak, Önasya ve Mezopotamya
```

[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-13.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-13.pdf)

`12 Do�ent P N Fen Edebiyat Fak�ltesi Psikoloji B�l�m� Klinik Psikoloji Anabilim Dalı Pozitif psikoloji ve klinik psikoloji çalışmaları ile bilişsel davranışçı terapi, şema terapi ve EMDR eğitimlerine sahip olmak.`
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-15.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-15.pdf)

```
g�venlik ve halkla ilişkiler konularında çalışmaları olmak.
2021.01.45 Fen Edebiyat Fak�ltesi TariÜ Genel T�rk Tarihi Do�ent N N Doçentlik unvanını Genel Türk Tarihi bilim alanında almış
olmak. Doğu Türkistan Tarihi alanında çalışmaları olmak.
2021.01.46 M�hendislik
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-17.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-17.pdf)

```
KADRO BİLGİLERİ ALES
T�R�
/PUAk
YDp ŞARTLAR
UNVANI ADET DERECE İLAN ÖZEL ŞARTI
64T REKT�RL�h ÖĞRETİM
GÖREVLİSİ
```
[https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-18.pdf](https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2021/12/20211206-4-18.pdf)

**Comment by likemusic** [comment]
@k00ni It is encoding related issue.

It contains 2 issues inside.

## First
First one related to encoding chars which is not exists in ToUnicode CMap for Identity-H fonts. Seems that those chars must be splitted to 1-byte chars and used as unicode entity codes.
```
[<54>9<DC52>-1.7<DC20>]TJ
```
![image](https://user-images.githubusercontent.com/603401/148167843-5f1bae88-7e40-4102-a917-4cda02d4c255.png)

## Second

Second is related to TrueType fonts and I don't understan how to decoding must be implemented in right way.
```
0.002 Tc -0.002 Tw 9 -0 0 9 657 315.84 Tm
[(\000D)6(\000])6(\000\003)-214.7(\000\201)-4.6(\000o)5.9(\000\003)-214.6(\000\\)22(\000\325\000O\000\003)-214.7(\000h)4(\000Q)-4.6(\000L\000Y)8.6(\000H)6(\000U)1.7(\000V)4.3(\000L\000W\000H)6(\000O\000H)6(\000U)1.7(\000L\000Q)-4.7(\000\003)-214.7(\000')4(\000\325\000\372)4.4(\000\003)-214.7(\000\370)1.7(\000O\000L\000\372)4.3(\000N)8.7(\000L\000O\000H)6(\000U)-11.7(\000\003)]TJ
```
![image](https://user-images.githubusercontent.com/603401/148167969-c01f892d-d16b-4b7c-9bea-31f672c97d0a.png)
