### ISSUE TITLE
Unable to read Type H: illegal hex digit from the Adobe XML Form Module

### ISSUE THREAD

**Issue by Naman0406** [smalot/pdfparser#499]
While i am read the pdf file content and controller value at that time i am getting following error. 
![124](https://user-images.githubusercontent.com/46198591/147136614-881acdfa-7166-4bb7-9020-df0423e9b68f.JPG)

**Comment by k00ni** [comment]
Can you provide the PDF which causes this? If it is free of charge and without any obligations, we may use it in our test environment.

**Comment by Naman0406** [comment]
[sample_ab_error.pdf](https://github.com/smalot/pdfparser/files/7770839/sample_ab_error.pdf)

**Comment by GreyWyvern** [comment]
I think this can be fixed by using `bin2hex($part)` instead of `pack('H*', $part)`. I believe the functions are equivalent, and `bin2hex()` will not throw the E_WARNING on an illegal hex digit. `hex2bin()` is in PHP > 5.4.0.
