### ISSUE TITLE
Fatal error undefined method

### ISSUE THREAD

**Issue by josmanperez** [smalot/pdfparser#51]
I had a web application in which I save lots of curriculums in pdf, I have a form where you can filter your search by keywords. You also have the option of searh in pdf, when this option is enabled I use the pdfparser for convert all the pdf files in txt and then search for that word..

The fact is..when I search using a keyword with the pdf option enabled I get this error:

Fatal error: Call to undefined method Smalot\PdfParser\Element\ElementMissing::has() in C:\Users\jpe\Desktop\SVN\desarrollo-ader\trunk\ader\ader-administration\vendor\smalot\pdfparser\src\Smalot\PdfParser\Page.php on line 87

I don't know why and also how to handle..

Thanks

**Comment by k00ni** [comment]
Error solved a long time ago by checking if an instance has the `has` method implemented.
