### ISSUE TITLE
images in pdfs

### ISSUE THREAD

**Issue by euneuber** [smalot/pdfparser#52]
Hi, I'd like to keep some hints about images in the output text, e.g. an image name or a hash of the binary content.

I have two images, a checkbox uncheced and  the same checkbox checked, several times in the pdf document. I would like to see where which checkbox is/was...

How can I insert such an info into the output text?

**Comment by k00ni** [comment]
Because of the long time span since you opened the issue its probably not of interest to you anymore.

But if it is, please get back to us. Closing for now.
