### ISSUE TITLE
Unwanted spaces in Content

### ISSUE THREAD

**Issue by halbano** [smalot/pdfparser#528]
- PHP Version: 7.2
 - PDFParser Version: ~~2.1~~ 2.2.0

### Description:
Hey guys, thanks for the hard work to keep this great library up to date. 
Unfortunately, we are having one strange issue parsing a file, we tried adjusting the config like this as @rubenvanerk mentioned in a few issues (in fact the FontSpaceLimit variable solves multiple issues with the char separation). 

```
$config = new \Smalot\PdfParser\Config();
$config->setHorizontalOffset('');
$config->setFontSpaceLimit(-136);

$parser = new \Smalot\PdfParser\Parser([], $config);
$pdf = $parser->parseFile("../storage/app/IL-Field-Guide-final-online.pdf");
```

### Expected output & actual output
But we cannot get rid of some unwanted empty spaces for example with: 

> "as opposed to persons i n vehicles" should be "as opposed to persons in vehicles" 

And more importantly in the PDF section titles we have: 

> "Consensual Encounters - Tier 1 in Seizure M odel" should be "Consensual Encounters - Tier 1 in Seizure Model"

Additionally, this one is not the expected output too: 

> "Your Powers and the Suspe ct's R ights during a TERRY Stop" needs to be "Your Powers and the Suspect's Rights during a TERRY Stop"

### PDF input
[IL-Field-Guide-final-online.pdf](https://github.com/smalot/pdfparser/files/8514566/IL-Field-Guide-final-online.pdf)

This may be not necessarily an issue, but we are suspecting that for some reason the PDF has a space within the conflicting phrases/sentences. 
In any case, we are starting to use the library, we modified a few things on the vendors folder trying to fix the issue, but we are going out of ideas now.

**Comment by k00ni** [comment]
Hey. Just to be sure, can you try again with PDFParser v2.2.0?

**Comment by halbano** [comment]
Hey @k00ni, same happen with the newest version.

**Comment by halbano** [comment]
@rubenvanerk maybe you have any thought?

**Comment by rubenvanerk** [comment]
Sorry, can't help you here.

**Comment by halbano** [comment]
@k00ni I know you may be slow responding, but please let us know if you have any ideas or suggestions we could try. I appreciate your help in advance.

**Comment by k00ni** [comment]
Sorry, I can't help you here, I would have written you already. The only idea I have is to check the code part which uses the `FontSpaceLimit` config and try to debug it. Good luck.
