### ISSUE TITLE
Can't get title and subject from metadata

### ISSUE THREAD

**Issue by borgir** [smalot/pdfparser#529]
- PHP Version: 7.3.21
 - PDFParser Version: 2.2.0

### Description:
When trying to get this specific PDF metadata, I only get the author. Also need the title and subject which are there as you can see on the screenshot below:
https://prnt.sc/aOy-Sl6sSIUW

### PDF input

https://www.alliancehealthplan.org/document-library/67033/

### Expected output & actual output

Expected output:
```
Array
(
    [Author] => Tasha Jennings
    [Company] => Alliance Health
    [CreationDate] => 2022-04-21T11:25:35-04:00
    [Creator] => Acrobat PDFMaker 22 for PowerPoint
    [Pages] => 3
    [Title] => Enrollment and Client Update Overview
    [Subject] => Enrollment and Client Update Overview
)
```

Actual output:
```
Array
(
    [Author] => Tasha Jennings
    [Company] => Alliance Health
    [CreationDate] => 2022-04-21T11:25:35-04:00
    [Creator] => Acrobat PDFMaker 22 for PowerPoint
    [Pages] => 3
)
```

### Code

```
    try {
        $parser = new \Smalot\PdfParser\Parser();
        $pdf = $parser->parseFile($file_path);
        $meta_data = $pdf->getDetails();
    } catch (Exception $e) {
        $field['value'] = 'Error: ' . $e->getMessage();
    }
```

Note: It works as expected, for example, with this file:
https://www.alliancehealthplan.org/document-library/70434/

Output:
```
Array
(
    [Author] => Hewett-RobinsonL
    [Company] => SRAHEC
    [CreationDate] => 2022-04-19T10:36:25-04:00
    [Creator] => Acrobat PDFMaker 22 for Word
    [Keywords] => 
    [ModDate] => 2022-04-19T10:36:26-04:00
    [Producer] => Adobe PDF Library 22.1.149
    [SourceModified] => 2022-04-19T14:36:12+00:00
    [Subject] => Social Determinants of Health: Now is the Time
    [Title] => Social Determinants of Health: Now is the Time
    [Pages] => 2
)
```

**Comment by k00ni** [comment]
Did this work before? If not, its a feature request, isn't it?

**Comment by borgir** [comment]
Hi @k00ni ! Thank you for the reply.
It works with some PDF files. With this in particular, it doesn't work.
I've update the question with and example that works correctly.
Thks.

**Comment by borgir** [comment]
Hi!
Any clue on what might be the problem?
Thks

**Comment by k00ni** [comment]
No sorry.

**Comment by GreyWyvern** [comment]
This is happening because there is a 'name' in the metadata that includes a hexadecimal-encoded space: "Document#20Type". The fix proposed by @philippze adds a position increment that loops and eventually bypasses the offending metadata name instead of parsing it.

The correct fix is to allow the '#' character in property names, and then convert them to the correct characters.

From Element.php
```php
            ...
            if (!$only_values) {
                if (!preg_match('/\G\s*(?P<name>\/[A-Z#0-9\._]+)(?P<value>.*)/si', $content, $match, 0, $position)) {
                    break;
                } else {
                    $name = preg_replace_callback(
                        '/#(\d\d)/',
                        function($m) {
                            return \chr(base_convert($m[1], 16, 10));
                        },
                        ltrim($match['name'], '/')
                    );
                    $value = $match['value'];
                    $position = strpos($content, $value, $position + \strlen($match['name']));
                }
            } else {
            ...
```
