### ISSUE TITLE
Parsing Consors Bank PDF documents result in nunreadable mess

### ISSUE THREAD

**Issue by nicoflemming** [smalot/pdfparser#530]
- PHP Version: 8.1.3
 - PDFParser Version: 2.2.0 

### Description:
When parsing Consors Bank transactions PDF documents the result looks like Grütze.
The words are unpredictable interrupted by one or more spaces or new lines. This makes it nearly impossible to parse it via regular expressions. Any workarounds/hints?

### PDF input

It contains sensitive data. I can send it to you by email.

### Expected output & actual output
Actual output:
RD ER A BREC H NUNG K
A U F AM 12.0 8.2 021 UM 16:0 0:1 8 TR A D EG ATE EX C H AN GE NR.2 07320809.0 01 D
epo tn um m er: 0
908 499 665
1 116975918/0 0 V
erm erk der B an k: 1
000
2 D
atu m : 1
2.0 8.2 021 S
eit e : 1
vo n 1 O
rd ern um mer 2
07320809.0 01 O
rd erd atu m 1
2.0 8.2 021 H
in w eis fü rO rd era b re ch n un gen un d Dep otb uch ung sa nze ig en: E
in w end ung en weg en Unric h tig ke it od er U nvo lls tä n dig ke it d ie se rM it t e ilu ng müsse n unve rz ü glic h erh o ben werd en,v g l. N um m er B .Z if fe r I. 1 1 (4 )u nd (5 )d e r
A llg em ein en Gesch äfts b e din g ung en (A G B Ban ke n).
M ach e n Sie Ih re Ein w end ung en in Textfo rm gelt e nd ,g e nüg tdie Abse ndung in ne rh alb der S ech s-W och en-F ris t an die Conso rs b ank ode rper Fax oder M ail a n die
u nte n an g eg eb en en Adre sse n.D as Unte rla ss e n re ch tz e it ig e rEin w end unge n gilt als Gene hm ig u ng. B
eze ic h nung W
KN IS IN I
S .S .G L.S E.D .1 00 U.E TF A. A0F5 U H DE0 00A 0F5 U H1 E
in he it Um sa tz S
T 396,0 0000 P
re is pro Ante il 29,6 50000 EU R F
R A N CO CO URTA G E K
urs w ert 1
1.7 41,4 0 EU R P
ro vis io n 2
9,3 5 EU R G
ru nd geb ühr 4
,9 5 EU R z
u la ste n Konto -N r. 0 9004345399663 1
1.7 75,7 0 EU R V
alu ta 16.0 8.2 021 B
esta n d zu g unste n Gir o sa m melv e rw ah ru ng C
BF 2126 L
[...]

### Code
```php
$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile('tests/assets/broker/documents/pdf/consors/KAUF_908499665_ord207320809_001_wknA0F5UH_dat20210812_id1020605033.pdf');
echo $pdf->getText();
```

**Comment by rubenvanerk** [comment]
Have you experimented with the `fontSpaceLimit` and `horizontalOffset` like so:
```php
$config = new \Smalot\PdfParser\Config();
$config->setFontSpaceLimit(-50);
$config->setHorizontalOffset(" ");

$parser = new \Smalot\PdfParser\Parser([], $config);
$pdf = $parser->parseFile('path/to/file');
$text = $pdf->getText();
```

Using an empty string for `horizontalOffset` and a higher or lower value for `fontSpaceLimit` might help.

**Comment by nicoflemming** [comment]
I tried values from -2000 to 2000 for FontSpaceLimit but without visible effect. The result still looks the same.

**Comment by nicoflemming** [comment]
any idea how to solve this?

**Comment by k00ni** [comment]
No, sorry.

**Comment by TheGrezuPl** [comment]
Hey, And how did you solve the problem?

**Comment by nicoflemming** [comment]
Unfortunately not. There was no feedback from neither from the maintainer nor from the community. Currently we're looking for a different solution.
