### ISSUE TITLE
Error in Y coordinate

### ISSUE THREAD

**Issue by ericksho** [smalot/pdfparser#532]
There are pages/documents where I don't get the correct Y coordinate.
I believe that using tables (I convert html to PDF) messes with the coordinate.
An example: Im searching for the tag {f{Docente}f} in this [document](https://drive.google.com/file/d/1FFenCAVkAdy7VU16bXJL6M11jBIkLa1Q/view?usp=sharing) in white font at the bottom (next to `Firma:` and under `Juan Carlos de la Lera` just not visible) but coordinates given are x: 251.367 - y: 109.779 instead

**Comment by oliver681** [comment]
I think I found the solution to this. I will edit this comment later with the details.
