### ISSUE TITLE
Infite loop in parseFile()

### ISSUE THREAD

**Issue by FabianRahm** [smalot/pdfparser#535]
- PHP Version: 8.1.5
 - PDFParser Version: 2.2.1

### PDF input

https://www.bfu-web.de/DE/Publikationen/Untersuchungsberichte/1999/Bericht_3X116-0.99.pdf;jsessionid=1B0F9060138F391CBCB696A896222B6E.live21324?__blob=publicationFile

### Expected output & actual output

Expected: Exception due to secure PDF.
Actual: Infinite loop within parseFile().

### Code

        try {
            $pdf = $this->pdfParser->parseFile($filePath);
            $this->mode = self::MODE_PHP_PARSER;
            return $pdf->getText();
        } catch (Exception) {
        }

**Comment by GreyWyvern** [comment]
The sample PDF given now returns a "Secured PDF" exception instead of falling into an infinite loop. That probably resolves this issue.

**Comment by k00ni** [comment]
@FabianRahm please try again with the latest state of the master branch and get back to us.
