### ISSUE TITLE
getText() returns only line breakes

### ISSUE THREAD

**Issue by f-wehrhausen** [smalot/pdfparser#537]
- PHP Version:  1.4
 - PDFParser Version:  2.1

### Description:
If I use the getText() function of the parsed pdf file, the content is not empty, but it haves no text, only line breaks (\n, \t) inside.

### Expected output & actual output
"""
\n
\t\n
\t\n
\t\n
\t\n
\t\t\n
\n
\n
\t\n
\n
\n
\n
\t\n
\t\n
\t\n
\t\n
 
"""

**Comment by k00ni** [comment]
Hey, please check your PHP- and PDF versions you provided, because you propably not running PHP 1.4.

Can you provide the PDF you are using via link?

Did you check https://github.com/smalot/pdfparser/blob/master/doc/CustomConfig.md? It might contain something helpful.

**Comment by PauArjona** [comment]
Hi,

Having the same problem with this PDF, `getText` function just returning blank spaces.

[gcontract_iiiiiiiiiiiiiiii_JSAECSNA1AAJBW88.pdf](https://github.com/smalot/pdfparser/files/9676285/gcontract_iiiiiiiiiiiiiiii_JSAECSNA1AAJBW88.pdf)

If you export it as PDF/A or Linearised (through MacOs Preview) it works.

`getDataTm`output:

```
array(0) {
}
```

`getDetails` output:

```
array(6) {
  ["Type"]=>
  string(4) "Page"
  ["Parent"]=>
  array(2) {
    ["Type"]=>
    string(5) "Pages"
    ["Count"]=>
    string(1) "1"
  }
  ["MediaBox"]=>
  array(4) {
    [0]=>
    float(0)
    [1]=>
    float(0)
    [2]=>
    float(595)
    [3]=>
    float(842)
  }
  ["Contents"]=>
  array(5) {
    [0]=>
    array(2) {
      ["Filter"]=>
      string(11) "FlateDecode"
      ["Length"]=>
      string(2) "11"
    }
    [1]=>
    array(2) {
      ["Filter"]=>
      string(11) "FlateDecode"
      ["Length"]=>
      string(2) "11"
    }
    [2]=>
    array(1) {
      ["Filter"]=>
      string(11) "FlateDecode"
    }
    [3]=>
    array(2) {
      ["Filter"]=>
      string(11) "FlateDecode"
      ["Length"]=>
      string(2) "77"
    }
    [4]=>
    array(2) {
      ["Filter"]=>
      string(11) "FlateDecode"
      ["Length"]=>
      string(3) "153"
    }
  }
  ["Group"]=>
  array(4) {
    ["Type"]=>
    string(5) "Group"
    ["S"]=>
    string(12) "Transparency"
    ["I"]=>
    string(4) "true"
    ["CS"]=>
    string(9) "DeviceRGB"
  }
  ["Resources"]=>
  array(0) {
  }
}
```

**Comment by GreyWyvern** [comment]
> I use the [Win2PDF](https://www.win2pdf.com/download/download-win2pdf-for-desktops.html)-Tool to create the pdf´s automatically.
> But if I print the same pdf in a pdf-reader with the nativ windows pdf-printer it works an the text from pdf can be extrated.

I downloaded and tried out Win2PDF but could not reproduce the issue, even with and without the "font IDs with hyphens" fix in my most recent PR which I initially thought this might be. I think it might be a problem specific to one of your PDFs? Or perhaps my copy of Win2PDF just doesn't want to use hyphens in font IDs but yours does?

Can you please try to create a test PDF that displays the issue, @f-wehrhausen, that isn't private? That would help very much.

> Having the same problem with this PDF, getText function just returning blank spaces.

I tried your example file and it's extracting text just fine for me.
