### ISSUE TITLE
Getting No output from PDF file produced from Microsoft Print To PDF, PDF Version 1.7

### ISSUE THREAD

**Issue by genepilot1** [smalot/pdfparser#540]
- PHP Version: 7.1.2 (Windows)
 - PDFParser Version: v2.2.1

### Description:
I'm getting back zero text length.
This PDF does have image(s).

### PDF input

PDF Producer: Microsoft Print To PDF
PDF Version: 1.7 (Acrobat 8.x)
File at: https://coachoregistration.com/track/info/oh_blackjack/2022/colpanschi2202/results.pdf

### Code

	$lConfig = new \Smalot\PdfParser\Config();
	$lConfig->setHorizontalOffset("\t");
	$lConfig->setDecodeMemoryLimit(0);
	$lParser = new \Smalot\PdfParser\Parser([], $lConfig);
	$lPDF = $lParser->parseFile($lInput);
	$lFileText = $lPDF->getText();

**Comment by EthosLuke** [comment]
Your PDF files need to be searchable / OCR'd. As it stands the content of your PDF doesn't contain any text, it is just images (you can verify this by trying to CTRL+F and search the PDF contents) and thus as far as this package is concerned there is nothing to read.

You would need to either save your PDF files with a different method that produces a searchable PDF or run them through an OCR tool before using this package.

**Comment by GreyWyvern** [comment]
Confirmed that the sample PDF contains no editable nor extractable text. PdfParser behaving as expected.

**Comment by k00ni** [comment]
Thank you for looking into it @EthosLuke @GreyWyvern.
