### ISSUE TITLE
Out of memory when parse the PDF file.

### ISSUE THREAD

**Issue by tannguyen04** [smalot/pdfparser#541]
- PHP Version: 7.4.29
 - PHP memory limit: 128MB
 - PDFParser Version: v2.2.1

### Description:

Get memory limit issue when parse the pdf file.

### PDF input

[mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf](https://github.com/smalot/pdfparser/files/8795150/mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf)

### Expected output & actual output

NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2456280 bytes) in /data/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php on line 761

### Code

`$file_path = '/data/app/sites/default/files/mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf';`
`$pdf_parser = new Parser();`
`$pdf = $pdf_parser->parseFile($file_path);`

**Comment by k00ni** [comment]
Please check if one of these Config options help here: https://github.com/smalot/pdfparser/blob/master/doc/CustomConfig.md#option-setdecodememorylimit--setretainimagecontent-manage-memory-usage

**Comment by tannguyen04** [comment]
Hi @k00ni 
PHP memory limit: 128MB.
I tried both `RetainImageContent` and `DecodeMemoryLimit` but out of memory issue still show up.

`$config = new \Smalot\PdfParser\Config();
$config->setRetainImageContent(false);
$config->setDecodeMemoryLimit(1000000);
$pdf_parser = new \Smalot\PdfParser\Parser([], $config);
$file_path = '/data/app/sites/default/files/mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf
error_log(memory_get_usage());
$pdf = $pdf_parser->parseFile($file_path);`
error_log(memory_get_usage());

Then I got

`NOTICE: PHP message: 34147728
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /data/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php on line 778`

**Comment by k00ni** [comment]
Thanks for checking. That is unfortunate, might be a bug then.

**Comment by GreyWyvern** [comment]
The test file [mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf](https://github.com/smalot/pdfparser/files/8795150/mccrindle-consumer-confidence-towards-purchasing-class-2-residential.pdf) extracts without memory errors on my machine. I haven't even set `setRetainImageContent(false)` nor set any `setDecodeMemoryLimit()`.

Others to verify. I am on Windows.

**Comment by k00ni** [comment]
That is enough for me.
