### ISSUE TITLE
Cannot parse read correctly with getTextArray() method

### ISSUE THREAD

**Issue by Arnaldo66** [smalot/pdfparser#542]
- PHP Version: 7.4
 - PDFParser Version: 2.2.1

### Description:
The parser cannot read information on this PDF. It's postal stamp fedited by french post office.
It contains img and text.

### PDF input

[https://github.com/Arnaldo66/tools_file/blob/main/1653988714_import_stamp.pdf](https://github.com/Arnaldo66/tools_file/blob/main/1653988714_import_stamp.pdf)

### Expected output & actual output

Expected output on the first page for example:
FRANCE
Timbre imprimé sur laposte.fr
Lettre verte
Max 50g
FRANCE
SD:87000639942948A

Actual output on the first page
b"Timbre imprimÃ© sur laposte.fr\x00y\x01\x04\x00\x04\x00Ç\x00:\x00K\x00²\x00( \x06( \x05È\x05Ç\x05À\x05À\x05À\x05Æ\x05Ã\x05É\x05É\x05Ä\x05Â\x05É\x05Ä\x05È\x00\x04\n\x00¸\x01ÉÌ‡Ì‡\x02h\x01É \x02¤\x01É\x02hÌ‡\x01É \n\n\x00Ta\x01X \x01ä\x01ß\x00æ\n\x009\x00t\x00\x04\x00U\x00\x1D\x00'    "

for information, I tried to read why online parser and the result is good:
[https://pdftotext.com/fr/](https://pdftotext.com/fr/)

### Code

$pdf    = $parser->parseFile($filePath);
$pages  = $pdf->getPages();
dump($pages[0]->getTextArray());

**Comment by GreyWyvern** [comment]
`getTextArray()` is returning properly parsed output in the latest release v2.7.0

```
Timbre imprimé sur laposte.frFRANCESD : 87000639942948A
Lettre verte 

Max 50g
FRANCE    
```
