### ISSUE TITLE
Notice: iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by LucianoHanna** [smalot/pdfparser#549]
- PHP Version: 7.4.18
 - PDFParser Version: 2.2.1

### Description:
I am getting this warning on `$pdf->getPages()[0]->getDataTm()`:
`Notice: iconv(): Detected an illegal character in input string`

### Stack Trace:

ErrorException: Notice: iconv(): Detected an illegal character in input string
#8 vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(604): Smalot\PdfParser\Font::decodeContentByEncodingElement
#7 vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(553): Smalot\PdfParser\Font::decodeContentByEncoding
#6 vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(467): Smalot\PdfParser\Font::decodeContent
#5 vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php(467): Smalot\PdfParser\Page::extractDecodedRawData
#4 vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php(502): Smalot\PdfParser\Page::getDataCommands
#3 vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php(655): Smalot\PdfParser\Page::getDataTm

**Comment by k00ni** [comment]
Can you provide a PDF or example input which raises this error?

**Comment by LucianoHanna** [comment]
I will try to reproduce this bug with a PDF without sensitive information.

**Comment by samvidhik** [comment]
Facing the same issue with Laravel 10.0 and smalot/pdfparser 2.3.0

Getting following exception:
 iconv(): Detected an illegal character in input string

  at C:\xampp\htdocs\desmis\vendor\smalot\pdfparser\src\Smalot\PdfParser\Font.php:606
    602▕         // mb_convert_encoding does not support MacRoman/macintosh,
    603▕         // so we use iconv() here
    604▕         $iconvEncodingName = $this->getIconvEncodingNameOrNullByPdfEncodingName($pdfEncodingName);
    605▕
  ➜ 606▕         return $iconvEncodingName ? iconv($iconvEncodingName, 'UTF-8', $text) : null;
    607▕     }
    608▕
    609▕     /**
    610▕      * Convert PDF encoding name to iconv-known encoding name.

Attaching pdf file being parsed.
[tsclist.pdf](https://github.com/smalot/pdfparser/files/10880811/tsclist.pdf)

**Comment by k00ni** [comment]
@samvidhik Please test if #580 fixes your problem. A note in the pull request would be appreciated.

**Comment by eapacheco** [comment]
# Issue
Hi @k00ni, I'm having the same issue here.
And I managed to find a public PDF that reproduces the issue: [ufsc.pdf](https://github.com/smalot/pdfparser/files/11226230/ufsc.pdf)

- Php 8.2.4
- laravel/framework 9.51.0
- smalot/PdfParser 2.4.0

⚠️ Stack trace below is from a test I created to reproduce the issue, thus it starts with PHPUnit
- PHPUnit 9.6.3

```
ErrorException {#3804 // tests/sandbox.php:24
  #message: "iconv(): Detected an illegal character in input string"
  #code: 0
  #file: "./vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php"
  #line: 606
  #severity: E_NOTICE
  trace: {
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:606 { …}
    ./vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:266 { …}
    Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}() {}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:606 { …}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:555 { …}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:469 { …}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:450 { …}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:506 { …}
    ./vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:657 { …}
    ./tests/sandbox.php:22 {
      Tests\sandbox->test(): void^
      › try {
      ›     $pdf->getPages()[0]->getDataTm();
      › } catch (Exception $e) {
    }
    ./vendor/phpunit/phpunit/src/Framework/TestCase.php:1608 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestCase.php:1214 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestResult.php:728 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestCase.php:964 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestSuite.php:684 { …}
    ./vendor/phpunit/phpunit/src/TextUI/TestRunner.php:653 { …}
    ./vendor/phpunit/phpunit/src/TextUI/Command.php:144 { …}
    ./vendor/phpunit/phpunit/src/TextUI/Command.php:97 { …}
    ./vendor/phpunit/phpunit/phpunit:98 { …}
  }
}
```

# Fixes

The solution proposed at #580 does solve my issue. Before that, I had tried working with `mb_convert_encoding`, given that I do not need MACINTOSH support:

```
if ($iconvEncodingName === 'MACINTOSH') {
    return $iconvEncodingName ? iconv($iconvEncodingName, 'UTF-8', $text) : null;
}

return $iconvEncodingName ? mb_convert_encoding($text, 'UTF-8', $iconvEncodingName) : null;
```

**Comment by fbett** [comment]
> @samvidhik Please test if #580 fixes your problem. A note in the pull request would be appreciated.

I also had this error. #580 solved it completely.
