### ISSUE TITLE
Only get limited number of pages from PDF

### ISSUE THREAD

**Issue by alesrebec** [smalot/pdfparser#561]
In Document.php we have this:

```
    public function getText(): string
    {
        $texts = [];
        $pages = $this->getPages();

        foreach ($pages as $index => $page) {
```

Can we change getText() to accept a numeric value and limit the returned string to get only the first X pages (or less if the document has less than X pages).
It's quite a useful feature, especially when you try to detect the language of the document and use this library. The documents can be hundreds of pages long but you only need the first page or first 5 to determine the language.

I can write a PR if this would be something that can be accepted by the maintainers.

**Comment by k00ni** [comment]
Hello @alesrebec, one of the maintainers here. The feature you are describing sounds quite useful indeed.

> I can write a PR if this would be something that can be accepted by the maintainers.

I suggest you do that and we discuss details there. IMHO there is nothing which speaks against this, but I wanna make sure it fits in our current code base.
