### ISSUE TITLE
ErrorException     Undefined array key 1

### ISSUE THREAD

**Issue by DAM3423** [smalot/pdfparser#575]
- PHP Version: 8.1
 - PDFParser Version:  "smalot/pdfparser": "^2.3"

I'm getting an error when trying to run getDataTm() on a pdf. I have tried this on a native LEMP stack and inside a Laravel Sail Docker Container. Both the same error message. Any advice would be greatly appreciated. The code is copied from the docs. The getText() function works as expected, but this one doesn't seem to.

### Description:
   ErrorException 

  Undefined array key 1

  at vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:852
    848▕                      *
    849▕                      * Source: https://ia902503.us.archive.org/10/items/pdfy-0vt8s-egqFwDl7L2/PDF%20Reference%201.0.pdf
    850▕                      * Introduced with https://github.com/smalot/pdfparser/pull/516
    851▕                      */
   852▕                     list($fontId, $fontSize) = explode(' ', $command['c'], 2);
    853▕                     break;
    854▕ 
    855▕                     /*
    856▕                      * array TJ

### Code
$data = $pdf->getPages()[0]->getDataTm();

**Comment by k00ni** [comment]
Can you provide the PDF you are using?

**Comment by DAM3423** [comment]
[Kappos L et al. EXPAND. Lancet 2018.391.1263-73.pdf](https://github.com/smalot/pdfparser/files/10734974/Kappos.L.et.al.EXPAND.Lancet.2018.391.1263-73.pdf)
[N-MOmentum_Lancet.pdf](https://github.com/smalot/pdfparser/files/10734975/N-MOmentum_Lancet.pdf)

**Comment by BenLumenDigital** [comment]
I'm also seeing this issue, oddly - in a vanilla PHP file it works, but in my Laravel project I see the error.

Not sure if that's a clue... seems like it might be.  I'm trying to find the problem!

**Comment by BenLumenDigital** [comment]
Seems to be line 85 in page.php

`list($fontId, $fontSize) = explode(' ', $command['c'], 2);`

Commented this out, and no error anymore... I'll dig further into this and see why

**Comment by coffeeyoghurt** [comment]
This error pops up if `$command['c']` does not contain any space. 

This code has the same behavior: 

```
list($a, $b) = explode(' ', 'FOOBAR', 2);
```

In my test the $command['c'] has a new line instead of a space which results in the same problem error 

```
list($a, $b) = explode(' ', "FOO\nBAR", 2);
```
