### ISSUE TITLE
Does not extract text from pdf 1.5?

### ISSUE THREAD

**Issue by robosobo** [smalot/pdfparser#578]
Hi, i have many files that were generated by Abbyy FineReader 15. Pdfparser not extract text from this. I've no problem with other files. Can someone help with this? Sample file - https://we.tl/t-R08tOuJWCz, PHP 8.1.

**Comment by k00ni** [comment]
Any errors or warnings? 
You are using our latest version? 
Can you also try to generate a PDF 1.4 and try again? Maybe PDF 1.5 specification is badly supported.

**Comment by robosobo** [comment]
No, it looks like it's working fine, but output text is almost empty (random characters or/and very small pieces of text - please try sample file).

Yes, i'm using the last version.

Not really, because i've got these files from others.

**Comment by sylbru** [comment]
It doesn’t seem to be related to PDF 1.5. I currently have the same issue with a PDF 1.5 file; but I created a simple PDF from LibreOffice Writer and it works well, despite also being in PDF 1.5.

Here is the offending file in my case : [texte.pdf](https://github.com/smalot/pdfparser/files/11271568/texte.pdf)

But to be fair a utility like `pdftotext` does not find any text either, although the file is selectable in a PDF viewer, and copy-pasting the text works well (a website like https://pdftotext.com/ seems to work too).

**Comment by GreyWyvern** [comment]
Text can be extracted from the sample file [texte.pdf](https://github.com/smalot/pdfparser/files/11271568/texte.pdf) without any difficulty in the latest release v2.7.0.
