### ISSUE TITLE
How to convert x, y given by getDataTm to millimeters?

### ISSUE THREAD

**Issue by afanazmy** [smalot/pdfparser#579]
How to convert x, y from `getDataTm` to millimeters? I've tried multiplying it by 0.352778, for x it's okay, but y isn't.

This is my pdf file.
[erkk.pdf](https://github.com/smalot/pdfparser/files/10798966/erkk.pdf)

I've managed to get the x, y of "..............." which is on page 3 and 4, but I want the value of x, y to be converted to millimeters.

**Comment by k00ni** [comment]
Maybe @shtayerc, @oliver681 or @izabala can answer that. Thanks for your time in advance.

**Comment by shtayerc** [comment]
I think y starts at the bottom of the page. You could calculate it from page height, for example:
```php
$page_height = $page->getHeader()->getDetails()['MediaBox'][3];
$y_from_top = $page_height - $y;
```

**Comment by afanazmy** [comment]
> I think y starts at the bottom of the page. You could calculate it from page height, for example:
> 
> ```
> $page_height = $page->getHeader()->getDetails()['MediaBox'][3];
> $y_from_top = $page_height - $y;
> ```

Wow that works great. Thanks for your time in advance.
