### ISSUE TITLE
getText() result contains annacceptable unicode chars

### ISSUE THREAD

**Issue by se-ti** [smalot/pdfparser#585]
- PHP Version: 7.3.33
 - PDFParser Version: 2.3.0

### Description:
text, returned by getText() is contaminated with unicode control characters (0x97 hex, 151 dec -- https://en.wikipedia.org/wiki/C0_and_C1_control_codes#C1_controls )

### PDF input
[page92.pdf](https://github.com/smalot/pdfparser/files/11008038/page92.pdf)

### Expected 
actual: "слева	 по ходу	 � веревка"
expected: "слева по ходу — веревка"

Same text with correct em-dash symbol.

### Code

```php
use Smalot\PdfParser\Parser;
include 'alt_autoload.php-dist';

$path = 'page92.pdf';
$content = file_get_contents($path);

$config = new \Smalot\PdfParser\Config();
$parser = new Parser([], $config);
$pdf = $parser->parseContent($content);
$text = $pdf->getText();
$sub = substr($text, 1658, 43);              // just to extract essential

$json = json_encode($sub);
// json === false, errorcode 5 : Malformed UTF-8 characters, possibly incorrectly encoded
```

**Comment by se-ti** [comment]
You can see this em-dash in the 4-th line of a table.

**Comment by se-ti** [comment]
Thank you, Brian @GreyWyvern, for a tremendous job, You've done!

I have tested changes, You did. You have eliminated not only the problems but my issues, but also removed chaotic extra whitespaces. They weren't critical for my purposes, but now texts look much more eye-friendly.

Thank You!
I'm really impressed!

**Comment by GreyWyvern** [comment]
Thanks @se-ti! While it was very fun and challenging to work on, if I've learned at least two things from this, it is these:

- The PDF format sucks and should be illegal.
- There's always more work to be done!

😆
