### ISSUE TITLE
text encoding breaks in the middle of the line

### ISSUE THREAD

**Issue by se-ti** [smalot/pdfparser#586]
- PHP Version: 7.3.33
 - PDFParser Version: 2.3.0 

### Description:
In the middle of the last line text encoding changes to a wierd one with squares instead of characters.
Acrobat Reader and Chrome pdf-viewer shows this file correct;

### PDF input

[page91.pdf](https://github.com/smalot/pdfparser/files/11008055/page91.pdf)

### Expected output & actual output
actual: "Тем  не  менее,  стаявший  ледник	 \hdjm]� gmgZlZdZ�� km^y� ih� \k_fm�� k^_eZe� i_j_\Ze� keh`g__� b�"
expected: "Тем не менее, стаявший ледник вокруг нунатака, судя по всему, сделал перевал сложнее и"

### Code

```php
use Smalot\PdfParser\Parser;
include 'alt_autoload.php-dist';

$path = 'page91.pdf';
$content = file_get_contents($path);

$config = new \Smalot\PdfParser\Config();
$parser = new Parser([], $config);
$pdf = $parser->parseContent($content);

echo $pdf->getText();
```

**Comment by GreyWyvern** [comment]
This is another example (related to #607 ) of where re-saving the PDF using Adobe Acrobat fixes the encoding issue. The listed "producer" is "3-Heights(TM) PDF Security Shell 4.8.25.2 (http://www.pdf-tools.com)"

Obviously Adobe Acrobat can interpret the mess, but doesn't save it that way.

**Comment by se-ti** [comment]
@GreyWyvern the problem is, i do not want to detect issues, resave any pdfs and hope, that issues would somehow disappear.

I'd prefer to get pdf's url, extract text from pdf, and forever forget the url, pdf -- everything but text.

**Comment by se-ti** [comment]
Probably i got You wrong, and you wanted to say, that my example was also generated by well-known to You faulty producer?
This example is an exerpt of a larger document, which (exerpt) was made by some online tool.
As far as i remember, original faulty pdf was generated by MS-Word, even though i'm not 100% sure.

**Comment by GreyWyvern** [comment]
Oh, I know PdfParser **should** be able to decode it somehow, but it's something to do with the way the application is saving it, rather than PdfParser decoding it incorrectly.

My speculation here is that some error-correction code needs to be *added*, not that PdfParser is doing something wrong.

**Comment by se-ti** [comment]
No. Enjoy this comment for decodeContentByToUnicodeCMapOrDescendantFonts :(
https://github.com/smalot/pdfparser/blob/66ddf4701c6bbd270569b432db24b0a242649147/src/Smalot/PdfParser/Font.php#L486

So, a person required, who would understand current algorithm, pdf spec, and implement spec-compatible algorithm, that woudn't destroy the rest of the lib.

**Comment by GreyWyvern** [comment]
More research. I now believe PdfParser is actually working as intended, and Adobe is doing some convoluted error correction. I think Adobe is somehow detecting that the current line of text cannot be rendered in the specified font, and actually _disobeys_ the PDFs instructions by overriding the requested font.

Here is the last section of the content stream:
```
...
/C2_1 1 Tf
0.005 Tc
-0.005 Tw
0.258 0 Td
[<023A>6.6<0011>-3.1<023C>5.3<0011>7.7<0003>-3<000B>4.7<026E>-3<0268>10.4<026C>1.2<0268>10.4<0003>-3.1<001400160011>7.7<00140018000C>] TJ
/TT1 1 Tf
0 Tc
0 Tw
7.419 0 Td
( ) Tj
/C2_1 1 Tf
-0.003 Tc
0.003 Tw
-41.774 -1.323 Td
[<0262>-5.6<0003>-118.6<0269>-5.7<0268>2.4<0265>1.4<0268>-8.4<02600262>-5.6<0265>1.3<0262>-5.6<0003>-118.6<026B025C>-14.8<0268>-8.4<0278>2<00110003>-118.6<023C>-2.7<0003>-118.6<0270>-5.6<025F>-10.6<0265>-9.4<0268>2.4<0266>-4.4<0003>-118.6<0269>-5.7<025F026A>-8.4<025F025C>-4.1<025A>-10.6<0265>1.3<0003>-118.6<0251>-8.9<025A026C>-6.9<0003>-118.6<0268>2.4<0270>-5.7<025F0267>-5.7<0262>-5.6<025C>-4.1<025A>-10.7<025F0266>-4.5<0003>-118.5<0264>-0.9<025A0264>-0.9<0003>-118.6<0262>-5.6<0267>-5.6<026C>-6.9<025F>-10.6<026A>2.3<025F026B0267>-16.4<026D>2.4<0278>2<0003>-118.6<0016>-8.3<023A>-12.2<000F0003>-129.3<0267>-5.6<025F0003>-118.6<026B0265>1.4<0262>-5.6<0272>-7.2<0264>-11.7<0268>2.4<0266>-4.4<0003>-118.6<026B0265>-9.4<0268>2.4<02600267>-16.3<026D>2.3<0278>-8.7<00110003>] TJ
ET
q
85.101 56.774 469.299 728.499 re
W
n
BT
10.977 0 0 10.977 90.4131 59.7246 Tm
[<024C>-4.9<025F0266>-4.4<0003>-236.9<0267>-5.6<025F0003>-236.9<0266>-4.4<025F0267>-5.7<025F025F>-10.7<000F0003>-236.8<026B026C>-6.9<025A0279>-5.3<025C>-4.1<0272>-7.3<0262>-5.6<0263>-5.6<0003>-236.9<0265>1.4<025F025E>0.6<0267>-5.6<0262>-5.7<0264>] TJ
ET
Q
q
85.101 56.774 469.299 728.499 re
W
n
BT
/TT1 1 Tf
0 Tc
0 Tw
10.977 0 0 10.977 249.167 59.7246 Tm
( ) Tj
ET
Q
q
85.101 56.774 469.299 728.499 re
W
n
BT
10.977 0 0 10.977 254.479 59.7246 Tm
[<025C>-14.9<0268>2.4<0264>-11.6<026A>-8.4<026D>2.3<025D>-1.6<0003>-236.8<0267>-16.4<026D>13.1<0267>-5.6<025A026C>-6.9<025A>-10.6<0264>-11.6<025A000F0003>-236.9<026B>-10.6<026D>2.4<025E>0.6<0279>-5.4<0003>-236.9<0269>-5.6<0268>2.4<0003>-236.9<025C>-14.9<026B025F0266>-15.2<026D>2.4<000F0003>-236.9<026B>-10.6<025E>0.6<025F0265>-9.4<025A>-10.6<0265>1.4<0003>-236.9<0269>-5.6<025F026A>-8.4<025F025C>-4.1<025A>-10.6<0265>1.4<0003>-236.9<026B0265>-9.3<0268>2.3<02600267>-16.3<025F025F0003>-236.9<0262>-5.6<0003>] TJ
ET
EMC
/Figure <</MCID 4 >>BDC
Q
q
315.4 759.359 185.25 -284.97 re
W
n
q
/GS0 gs
185.25 0 0 284.97 315.4 474.389 cm
/Im1 Do
Q
EMC
Q
```

As explanation, every line that ends with " Tf" means a font change for the content following, and there are two fonts defined in the document: **TT1** and **C2_1**. The font with ID **C2_1** is the one that has the correct code page to display Cyrillic characters. **TT1** gets used only for spaces and punctuation like commas and periods.

Lines that end with " Tj" or " TJ" are lines of content (you might have to scroll the code window to the right to see these line endings since they're _long_). You'll notice that for the first three " TJ" lines, the font has been correctly set to **C2_1**. But then, before the last line of " TJ" content (the line that begins `[<025C>-14.9<0268>2.4<0264>-11.6`), you can see the font has been set to **TT1** 13 lines earlier, but does _not_ get set back to **C2_1** in order to display that line properly.

In this case, PdfParser is simply obeying the instructions of the PDF and displaying the last line of content using the incorrectly specified font code page.

So unless you want to add the same kind of error-detection and recovery code that Adobe probably has, I think this Issue can be closed with "working as intended." PdfParser is just doing what it's told.

**Comment by k00ni** [comment]
Thank you for looking into this @GreyWyvern. It would be great if you could add a link to the part of the specification you referring to.

**Comment by k00ni** [comment]
Does it make sense to extend [CustomConfig](https://github.com/smalot/pdfparser/blob/master/doc/CustomConfig.md), so user can activate the "recovery code", if needed?

**Comment by GreyWyvern** [comment]
@se-ti May we use your pdf _page91.pdf_ as part of the PdfParser test suite? A change in PR #614 fixes this issue and it's quite difficult to reproduce the exact bug in a new PDF. :)

**Comment by se-ti** [comment]
Yes, you can use it.

You can also try page92.pdf from 
https://github.com/smalot/pdfparser/issues/585, or i can provide document, they originate from.

**Comment by GreyWyvern** [comment]
> Yes, you can use it.
Thanks!

> You can also try page92.pdf from #585, or i can provide document, they originate from.
Thanks for that too. Unfortunately it looks like #585 is a different issue. Probably a missing single mapping in a CIDMap (character code dictionary) rather than a whole missing CIDMap which #614 addresses.

I'll have to take a look at that later. :)

**Comment by GreyWyvern** [comment]
> Thank you for looking into this @GreyWyvern. It would be great if you could add a link to the part of the specification you referring to.

I believe my PR #614 falls under the Handling Undefined Characters in section 5.6 of the PDF Reference 1.7.  (pages 454-455)
https://ia801001.us.archive.org/1/items/pdf1.7/pdf_reference_1-7.pdf

Specifically the paragraph beginning "If the code is invalid..." and the following two numbered points. The only difference being I'm not doing it in a bytewise fashion, I'm decoding the whole string using a different codespace and then checking for invalid characters again.
