### ISSUE TITLE
parseFile() silently dies - part 2?

### ISSUE THREAD

**Issue by theborland** [smalot/pdfparser#596]
We use pdfparser a lot and it generally works flawlessly. One file has caused it to fail without throwing an exception. (When parsing:

It works fine on our development server, but on production it fails (different memory setup). 
Any idea? I cant include the pdf for privacy reasons... Ill ask for permission.

I threw in a bunch of catches to see -> it prints parse1a, then returns 500:
try {
                    Log::info('about to parse1a');
                    $pdf = $parser->parseFile($path);
                    Log::info('about to parse1b');

                    $text = $pdf->getText();
                    Log::info('about to parse1c');
                } catch (\Exception $e) {
                    Log::info('Couldnt translate file ' . $directory . ' - ' . $code);
                    Log::info(json_encode($e->getTrace()));
                    $text = null;
                } catch (Exception $e) {
                    Log::info('Couldnt trdanslate file ' . $directory . ' - ' . $code);
                    Log::info(json_encode($e->getTrace()));
                    $text = null;
                } catch (\Throwable $e) {
                    Log::info('about to parse3');
                }

**Comment by k00ni** [comment]
Please paste the exact error. A stack trace (of PDFParser files) would also be helpful. 

Other than that, what configuration do you run on dev and prod server? We need PHP version, used PHP extensions would be helpful too.

**Comment by theborland** [comment]
It is weird - there is no stack trace at all. It just fails and stops executing. We use pdfparser a ton and never come across this before. I understand with this little information there is nothing really to go on. I will try to get more info (especially if we see it again and can find some more useful info, but will close it for now. Thank you,.
