### ISSUE TITLE
undefined function Smalot\PdfParser\xml_parser_create()

### ISSUE THREAD

**Issue by Folllast** [smalot/pdfparser#616]
Hello!

i want to use this tool, but i got the following PHP error.

PHP Fatal error:  Uncaught Error: Call to undefined function Smalot\PdfParser\xml_parser_create() in /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Document.php:205
--
  | Stack trace:
  | #0 /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Parser.php(219): Smalot\PdfParser\Document->extractXMPMetadata()
  | #1 /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Parser.php(117): Smalot\PdfParser\Parser->parseObject()
  | #2 /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Parser.php(90): Smalot\PdfParser\Parser->parseContent()
  | #3 /var/www/html/pdf/pdf/funktionen_V2.php(306): Smalot\PdfParser\Parser->parseFile()

what is the Problem?

**Comment by k00ni** [comment]
@Folllast is XML enabled in your installation? Based https://www.php.net/manual/en/xml.installation.php XML is enabled by default, but maybe your systems lacks packages.

CC @GreyWyvern That is the code from #606. Maybe we have to add `ext-xml` and others to composer, because it is not part of the default installation on some systems according to https://www.php.net/manual/en/simplexml.installation.php.

**Comment by Folllast** [comment]
![image](https://github.com/smalot/pdfparser/assets/116271376/8848a72c-b5ca-4195-9eed-31634d2fa4fd)

I think it should be enabled.

**Comment by k00ni** [comment]
Please provide full output of your PHP info.

**Comment by Folllast** [comment]
> Please provide full output of your PHP info.

[PHPINFO.pdf](https://github.com/smalot/pdfparser/files/12122020/PHPINFO.pdf)

**Comment by GreyWyvern** [comment]
It looks like libxml is active in your installation.

If it's looking for `Smalot\PdfParser\xml_parser_create()` within the namespace, maybe just adding the global scope slash to all the xml functions will solve this?

```php
    /**
     * Extract XMP Metadata
     */
    public function extractXMPMetadata(string $content): void
    {
        $xml = \xml_parser_create();
        \xml_parser_set_option($xml, \XML_OPTION_SKIP_WHITE, 1);

        if (1 === \xml_parse_into_struct($xml, $content, $values, $index)) {
            /*
             * short overview about the following code parts:
             *
...
```

```php
...
                // So if there are multiple XMP blocks, just merge the values
                // of each found block over top of the existing values
                $this->metadata = array_merge($this->metadata, $metadata);
            }
        }
        \xml_parser_free($xml);
    }
```

**Comment by k00ni** [comment]
I am wondering why all tests still pass? A broken namespace would have been noticed, wouldn't it?

**Comment by Folllast** [comment]
I changed the Document.php:

`Cannot declare class Smalot\PdfParser\Document, because the name is already in use in /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Document.php on line 49"`

**Comment by Folllast** [comment]
I changed the Document.php:

```php
Cannot declare class Smalot\PdfParser\Document, because the name is already in use in /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Document.php on line 49"
```

**Comment by Folllast** [comment]
First the program ran under XAMPP and now nginx. can it be related to this?

**Comment by k00ni** [comment]
I am confused. You wrote:

> Cannot declare class Smalot\PdfParser\Document, because the name is already in use in /var/www/html/pdf/pdfparser-master/src/Smalot/PdfParser/Document.php on line 49"

It seems you have an autoloading problem, but it is not related to PDFParser. As the error said, there are two classes with the same name in your project.

> First the program ran under XAMPP and now nginx. can it be related to this?

This gets too off topic here, its not about `xml_parse_create` anymore.
