### ISSUE TITLE
\Smalot\PdfParser\Parser() needs method getParsedData() but doesn't find it

### ISSUE THREAD

**Issue by jeffbdn** [smalot/pdfparser#62]
Greetings,
the class \Smalot\PdfParser\Parser() uses the method getParsedData() in the method parseContent() (line 89)
The problem is that there is not method getParsedData() in the class \Smalot\PdfParser\Parser().
This causes the method parseContent() to not work, and therefore the parsing of pdf to be impossible.
Thanks by advance for any advice or information you could provide!
Jeff

**Comment by Connum** [comment]
There is no instance of a call to a method named `getParsedData` to be found anywhere in the code in its current state.
This might have been the case once, but I'd say this issue can be closed!

**Comment by k00ni** [comment]
> There is no instance of a call to a method named getParsedData to be found anywhere in the code in its current state.
This might have been the case once, but I'd say this issue can be closed!

Thank you for checking @Connum!
