### ISSUE TITLE
Ambiguous class resolution, QRcode

### ISSUE THREAD

**Issue by titolendable** [smalot/pdfparser#63]
I just installed this package and I am getting the following warning:

"Warning: Ambiguous class resolution, "QRcode" was found in both "/projects/lendable/vendor/tecnick.com/tcpdf/include/barcodes/qrcode.orig.php" and "/projects/lendable/vendor/tecnick.com/tcpdf/include/barcodes/qrcode.php", the first will be used."

The version installed: "Using version 0.9.* for smalot/pdfparser"

**Comment by aik099** [comment]
Both files come from `tecnick.com/tcpdf` vendor package and you instead should report this to TCPDF bug tracker: https://sourceforge.net/p/tcpdf/bugs/?source=navbar .

**Comment by smalot** [comment]
This issue is not related the current project, but about a dependency.
The TCPDF project is hosted on SourceForge.

But regarding your issue, you should delete the file "qrcode.orig.php".

**Comment by smalot** [comment]
I've created an issue on this project.

**Comment by smalot** [comment]
The issue has been fixed in TCPDF.
http://sourceforge.net/p/tcpdf/bugs/1050/

**Comment by titolendable** [comment]
Thanks guys.. I've updated the tecnick.com/tcpdf package and the warning is gone..
