### ISSUE TITLE
Cannot Extract Bengali text

### ISSUE THREAD

**Issue by sbhshoaib** [smalot/pdfparser#637]
I have a PDF file that contains Bengali text. Texts are not extracted correctly using the getText function.

**Comment by k00ni** [comment]
Can you paste example input or link the PDF itself?

**Comment by sbhshoaib** [comment]
@k00ni Thanks for replying... 

After extracting the pdf attatched I get output like this 
`
3/12/23, 8:46 PM Search https://172.20.20.14/cms-portal/voter/detail/19839314794375102/1983-08-10 1/2 National ID 4189577531 Pin 19839314794375102 Status printed Afis S tatus NO_MA TCH Lock Flag N V oter No 932440375102 Form No 2375102 Sl No 451 Tag old Name(Bangla) আ উ Name(English) AZIM UDDIN Date of Birth 1983-08-10 Birth Place Birth Other Birth R egistration No Father Name জয় আ Mother Name আ Spouse Name Gender male Marital married Occupation Disability Disability Other Present Address Division District RMO প (1) City Corporation Or Municipality Upozila Union/W ard সহ Mouza/Moholla Additional Mouza/Moholla Ward For Union Porishod 7 Village/R oad Additional Village/Road Home/Holding No Post Office Postal Code 1900 R egion ময়মন Permanent Address Division District RMO প (1) City Corporation Or Municipality Upozila Union/W ard Mouza/Moholla Additional Mouza/Moholla Ward For Union Porishod 7 Village/R oad Additional Village/Road Home/Holding No Post Office Postal Code 1900 R egion ময়মন Education উ Education Other Education Sub Identification Smart Card Info Voter Documents No Documents A vailable 3/12/23, 8:46 PM Search https://172.20.20.14/cms-portal/voter/detail/19839314794375102/1983-08-10 2/2 Blood Group B+ TIN Driving Passport B 0899973 NID F ather NID Mother Nid Spouse Voter No F ather Voter No Mother Voter No Spouse Phone 01717 934188 Mobile R eligion muslim Religion Other Death Date Of Father Death Date Of Mother Death Date Of Spouse No Finger 0 No Finger Print 0 V oter Area (932440) Voter At present
`

Most of the bengali text are incorrect and missing.

[azim.pdf](https://github.com/smalot/pdfparser/files/12457720/azim.pdf)


> Can you paste example input or link the PDF itself?

**Comment by GreyWyvern** [comment]
> Most of the bengali text are incorrect and missing.
> 
> [azim.pdf](https://github.com/smalot/pdfparser/files/12457720/azim.pdf)

This seems like confidential personal information. Are you sure you want to share this? Is it yours, @sbhshoaib ?

My pull request #634 seems to parse the Bengali in this file properly.

**Comment by GreyWyvern** [comment]
The PDF the original author posted seemed to be confidential personal information. I believe they deleted their post to unlink it? I have also deleted my own post that referenced it.

My pull request https://github.com/smalot/pdfparser/pull/634 seems to parse the Bengali in the posted example file properly.

**Comment by sbhshoaib** [comment]
> The PDF the original author posted seemed to be confidential personal information. I believe they deleted their post to unlink it? I have also deleted my own post that referenced it.
> 
> My pull request #634 seems to parse the Bengali in the posted example file properly.

Thanks for your concern. Yes, the PDF contains some personal information. But before posting I made some changes to it using PDF Editor. Also, the data is not usable without biometrics. However, I deleted the post as an extra precaution. Thank you @GreyWyvern

**Comment by k00ni** [comment]
@sheldonled is #634 parsing it correctly?

**Comment by sbhshoaib** [comment]
> @sheldonled is #634 parsing it correctly?

Yes. It's working. 
Thanks a lot @GreyWyvern.
