### ISSUE TITLE
Can't extract text from pdf, Returns empty string

### ISSUE THREAD

**Issue by GourangaDas** [smalot/pdfparser#641]
I have some pdf files. When trying to extract the text using the getText() function, the text cannot be extracted from the PDF, it returns the empty string.
Here are three example PDFs: [First PDF](https://www.manipurlotteries.com/Home/Prints?dateTime=10&date=21%2F09%2F2023), [Second PDF](https://www.manipurlotteries.com/Home/Print?dateTime=11&date=21%2F09%2F2023), [Third PDF](https://www.manipurlotteries.com/Home/Print?dateTime=3&date=21%2F09%2F2023). 
Please help me.

**Comment by k00ni** [comment]
Thank you for reporting. Please try out #634 and give us feedback if that helps.

**Comment by GreyWyvern** [comment]
Unfortunately #634 does not fix this issue as there is something deeper going on. A valid document stream is not being delivered to **PDFObject.php** for it even to act upon. Maybe it's not being decoded properly? I'll take a closer look today.

**Comment by GourangaDas** [comment]
[@GreyWyvern](https://github.com/GreyWyvern), with your changes to [PDFParser](https://github.com/smalot/pdfparser/pull/642), it can now extract text from the above PDFs. But there is some text encoding or font mapping problem in the output.

If I try to generate HTML from PDF via https://xodo.com/convert-pdf-to-html, all the text in the HTML that I got from the above website looks almost like the input PDF. But in the output from [SmalotPdfParser](https://github.com/smalot/pdfparser), some problems still remain, such as some text that is not readable or understandable and not quite like the visual text of PDFs.

Is there any solution to this problem?

**Comment by GreyWyvern** [comment]
> Is there any solution to this problem?

I don't know yet. It's some kind of font decoding issue, I'll have to look into it more. Regardless, it should be reported as a new issue since it's (I strongly suspect) unrelated to *this* issue of **no** text being extracted via `getText()`.

**Comment by GreyWyvern** [comment]
@GourangaDas After some research the font-decoding issue appears to be with the use of an **Identity-H** Type0 CID font which has been reported before: #534. The problem is that no toUnicode map is extracted from these fonts, so the hexadecimal bytes have no table to use for translation; they are just passed through unconverted. *Why* there is no toUnicode map will need to be examined.

It is indeed unrelated to `getText()` returning an empty string in this case.
