### ISSUE TITLE
Is there any way to get page number with its content?

### ISSUE THREAD

**Issue by mdoulabi1** [smalot/pdfparser#648]
is there any way to get page number with its contenet?
for example:
page 1 : full content

**Comment by k00ni** [comment]
https://github.com/smalot/pdfparser/blob/master/doc/Usage.md#get-pages-width-and-height

`$pages` contains an ordered list of pages (use your own counter, if needed). Inside the loop use `$page->getText()` to get the text of the current page instance.

**Comment by mdoulabi1** [comment]
oh
thanks for your hand
 does your package supports Arabic and Persian language?
 i test the languages but it show the sentense incorrect
 plz help
 thanks

**Comment by k00ni** [comment]
> does your package supports Arabic and Persian language? i test the languages but it show the sentense incorrect

Please open a new issue, because your initial question is answered. Also, we will release a new release candidate today, so try to test it if you can.
