### ISSUE TITLE
Call for Testers! - v2.8.0

### ISSUE THREAD

**Issue by k00ni** [smalot/pdfparser#650]
This issue combines coordination of the v2.8.0 release as well as collecting related issues/problems.

Ref #634

@j0k3r - OK? 
https://github.com/smalot/pdfparser/releases/edit/untagged-929a6f925a01a30df44d (collaborators only)

---

If someone finds a bug in v2.8.0 RC1 or newer, please post them here or open a new issue.

CC @GreyWyvern

**Comment by j0k3r** [comment]
@k00ni I've just updated the title to find that it was useless at the end 😅 Good to go for me: https://github.com/smalot/pdfparser/releases/tag/untagged-546567f4b175d9d307fc

**Comment by k00ni** [comment]
Thank you.

v2.8.0-RC1 is out: https://github.com/smalot/pdfparser/releases/tag/v2.8.0-RC1

**Comment by GreyWyvern** [comment]
Thanks everyone for all your help with this!

**Comment by k00ni** [comment]
@j0k3r - https://github.com/smalot/pdfparser/releases/edit/untagged-fc55142cea8ee64d34b1 OK?

**Comment by Reqrefusion** [comment]
I've been using it since the day it came out. So far, I have not encountered the problem of corrupted letters in the old versions. I find it more accurate to call this version 3.0.0 instead of 2.8.0. Thanks to everyone who contributed to this version, especially for different languages, we can finally say that we have reached the real version.

**Comment by j0k3r** [comment]
@k00ni good for me!

**Comment by k00ni** [comment]
We receive too many bug reports which are related to 2.7.0, but not 2.8.0-RC2. In each I have to ask people to try again with our latest release. That consumes too much time. Also, there are people reporting, that 2.8.0-RC2 works for them or the reported bug remains after the update.

Because of this I would like to release 2.8.0. Any objections?

CC @GreyWyvern @j0k3r

**Comment by j0k3r** [comment]
I agree with you, go release 2.8.0
