### ISSUE TITLE
Getting error Class 'Smalot\PdfParser\Parser' not found.

### ISSUE THREAD

**Issue by sagarsapariya93** [smalot/pdfparser#656]
Hello
I am trying to use PdfParser in my ERP system which is develop in PHP  CI frame work.
I am getting this issue Class 'Smalot\PdfParser\Parser' not found.
How to solve 
My composer in public_html.
pdfparser-master  folder is under public_html/vendor/pdfparser-master 
How to Solve this?

Thanks

**Comment by k00ni** [comment]
This sounds like an autoloading issue. Please check, that you include the file `[...]/public_html/vendor/autoload.php`, which points to PDFParser classes. Usually Composer handles all that for you. Please make sure you followed all steps how to use Composer: https://getcomposer.org/doc/01-basic-usage.md
