### ISSUE TITLE
Get text from PDF using PdfParser with table format or section wise get data.

### ISSUE THREAD

**Issue by sagarsapariya93** [smalot/pdfparser#660]
Hello
I am using PdfParser in my php (CI) project.
i am trying get text from pdf. I have multiple types of PDF like multiple types invoices with different layout of every PDF. I want some details in all pdf like (invoice number, Date, name,) also i want table of items. It is possible or not. This is urgent so replay me ASAP.
My current Code is below
$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile($file);
$firstpage = $pdf->getPages()[0];
$text = $pdf->getText();
$data = $firstpage->getDataTm();

Thanks

**Comment by k00ni** [comment]
> This is urgent so replay me ASAP.

Slow it down a bit buddy, we are not here to play support for you personally. 

But I have a good day. Can you provide the PDFs which are not working?

**Comment by k00ni** [comment]
Not so urgent apparently.
