### ISSUE TITLE
No output while parsing such files with headers (I suppose)

### ISSUE THREAD

**Issue by tejpsingh9** [smalot/pdfparser#661]
- PHP Version: 7.4
 - PDFParser Version: Latest as on 2023/12/30

### Description:
No output while parsing such files
I tried wihout config first, then tried with config also.

### PDF input

Attached 2 files
### Code

$config = new \Smalot\PdfParser\Config();
		$config->setRetainImageContent(false);
		$config->setDecodeMemoryLimit(1000000);
		$parser = new \Smalot\PdfParser\Parser([], $config);

		$pdf = $parser->parseFile("d:\\wamp\\www\\lampkm\\uploads\\juds\\c1-j1_ivrcl_judgmt.pdf");

[c1-j1_ivrcl_judgmt.pdf](https://github.com/smalot/pdfparser/files/13797571/c1-j1_ivrcl_judgmt.pdf)
[c1-j2_kss_judgmt.pdf](https://github.com/smalot/pdfparser/files/13797572/c1-j2_kss_judgmt.pdf)

[c1-j2_kss_judgmt.pdf](https://github.com/smalot/pdfparser/files/13797567/c1-j2_kss_judgmt.pdf)
[c1-j1_ivrcl_judgmt.pdf](https://github.com/smalot/pdfparser/files/13797568/c1-j1_ivrcl_judgmt.pdf)

**Comment by k00ni** [comment]
> PDFParser Version: Latest as on 2023/12/30

Just to be sure, you tested with 2.8.0-RC2?

**Comment by tejpsingh9** [comment]
How to check the version

**Comment by k00ni** [comment]
In case you use Composer type the following command in the terminal:

```
composer show
```
It will show a list of installed packages, such as:

```
symfony/polyfill-mbstring v1.28.0 Symfony polyfill for the Mbstring extension
                             ^---- version
[...]
```
