### ISSUE TITLE
Attempting to parse a PDF with a form field with two dots in it causes pdfparser to throw an exception

### ISSUE THREAD

**Issue by terrafrost** [smalot/pdfparser#665]
- PHP Version: 8.3.1
 - PDFParser Version: 2.7.0

### Description:
Attempting to parse a PDF with a form field with two dots in it causes pdfparser to throw an exception. Adobe Acrobat reads the PDF just fine as does `qpdf test.pdf --qdf test.qdf`.

### PDF input
[test.pdf](https://github.com/smalot/pdfparser/files/13881204/test.pdf)

### Expected output & actual output
The expected output is for it not to throw an exception. The actual output is an exception:

```
Fatal error: Uncaught Smalot\PdfParser\Exception\EncodingNotFoundException: Missing encoding data for: ""
```

### Code
```
<?php
require __DIR__ . '/vendor/autoload.php';

$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile('test.pdf');

$objects = $pdf->getObjects();
foreach ($objects as $obj) {
	print_r($obj->getDetails());
}
```

**Comment by k00ni** [comment]
Please try again with v2.8.0-RC2 and get back to us. Thanks.

**Comment by terrafrost** [comment]
Still an issue.

**Comment by GreyWyvern** [comment]
OK. This should be a quick fix. The test.pdf document doesn't contain an encoding value, so a default must be assumed.

According to the PDF Reference 1.7, the default encoding should be 'StandardEncoding'. PdfParser currently does not supply any default, so when it queries for the BaseEncoding, it returns an empty string.

Should be as simple as inserting a check in `Encoding->getEncodingClass()`:

```php
    /**
     * @throws EncodingNotFoundException
     */
    protected function getEncodingClass(): string
    {
        // Load reference table charset.
        $baseEncoding = preg_replace('/[^A-Z0-9]/is', '', $this->get('BaseEncoding')->getContent());

        // Check for empty BaseEncoding
        if ('' == $baseEncoding) $baseEncoding = 'StandardEncoding';

        $className = '\\Smalot\\PdfParser\\Encoding\\'.$baseEncoding;

        if (!class_exists($className)) {
            throw new EncodingNotFoundException('Missing encoding data for: "'.$baseEncoding.'".');
        }

        return $className;
    }
```

Are we able to use your document in the PdfParser test suite, @terrafrost ?

**Comment by terrafrost** [comment]
> Are we able to use your document in the PdfParser test suite, @terrafrost ?

Feel free!
