### ISSUE TITLE
(Question) Replace an Image inside a PDF 

### ISSUE THREAD

**Issue by juanborras** [smalot/pdfparser#689]
Hey there!

What I'm trying to achieve is the reduction of the size of the embedded images inside a PDF. Iterate on them and for each, get the image, compress/reduce quality and "put it back". Is this possible?

Thanks!

**Comment by k00ni** [comment]
Not to my knowledge. PDFParser only handles "parsing" jobs, it can't manipulate a PDF.

**Comment by GreyWyvern** [comment]
You can do this online with Adobe's Compress PDF tool: https://www.adobe.com/acrobat/online/compress-pdf.html

**Comment by juanborras** [comment]
> You can do this online with Adobe's Compress PDF tool: https://www.adobe.com/acrobat/online/compress-pdf.html

I would like to do it inside PHP in order to automatice it

**Comment by k00ni** [comment]
This is out of scope of this library. You could try https://github.com/tecnickcom/TCPDF or https://manuals.setasign.com/.
