### ISSUE TITLE
Parser page->getText() returns no content

### ISSUE THREAD

**Issue by alexglue** [smalot/pdfparser#69]
Could not get content of this file (empty content except of image and some strange numbers) http://crowdspace.ru/files/solution/eda/437/0fd/9fb28c56ca76fc43f7d344c.pdf
Maybe some kind of multibyte trouble?

**Comment by smalot** [comment]
The content of this PDF file is an image, and not a text.
The only thing I could be able to extract is the creation date : 

CreationDate (D:20140930141356+00'00')

BR
