### ISSUE TITLE
No spaces between some words

### ISSUE THREAD

**Issue by ghost** [smalot/pdfparser#70]
Hi, I had a problem, that I just solved and I thought it may help some people.

I work with pdf files where I need to detect latitude/longitude position in order to display a marker on a map.
The problem was that there was no spaces between some words in generated text after I converted pdf file e.g.: "F3293·5 - Den Hon Bai132 44·25 N 107 10·75 E". In this case it's impossible to tell if latitude position is "132 44·25 N" or "32 44·25 N" or "2 44·25 N" and I had lots of situations like this one.

FIX: I've just added "$text .= ' ';" right after "// set word spacing
case 'Tw':", line 346 in Object.php.

Now I'm getting correct output like "F3293·5 - Den Hon Bai13 2 44·25 N 107 10·75 E", so it's obvious now that the latitude position is "2 44·25 N".
Anyway, I hope that makes sense and I believe that you may find this useful if you experience problems with spaces between words.
Thanks!

**Comment by k00ni** [comment]
Sorry for the late response.

To reproduce it we need the PDF in question. If this is still a problem you have, please get back to us.
