### ISSUE TITLE
Wrong version tag

### ISSUE THREAD

**Issue by nuernbergerA** [smalot/pdfparser#707]
Hey @k00ni

you tagged the last release with a typo, thats why it does not show up on packagist
`v.2.10.0` but it should be `v2.10.0`
![image](https://github.com/smalot/pdfparser/assets/13331388/352d3841-54a8-41ab-a9c8-260b8ff0049a)

cheers adrian

**Comment by k00ni** [comment]
Ah shit, yeah, ... good catch. Thank you!

**Comment by j0k3r** [comment]
Good catch
