### ISSUE TITLE
pdfparser version 2.10.0 is not updated on packagist

### ISSUE THREAD

**Issue by huihuangjiuai** [smalot/pdfparser#708]
URL：https://packagist.org/packages/smalot/pdfparser

**Comment by k00ni** [comment]
Thank you for the note, I saw this in the past frequently. Sometimes its almost instantaneously or like now, there is nothing. It says its auto-updated, last update was **2024-04-29 14:21:26 UTC** So I guess we just have to wait...?

**Comment by k00ni** [comment]
The problem was a "broken" version tag: `v.2.10.0` as mentioned in #707
