### ISSUE TITLE
Warning: file_get_contents(ficheiros/C:\xampp\tmp\phpA3AF.tmp): Failed to open stream: No such file or directory in C:\xampp\htdocs\teste_php\vendor\smalot\pdfparser\src\Smalot\PdfParser\Parser.php on line 79

### ISSUE THREAD

**Issue by ItsTheChiva** [smalot/pdfparser#713]
- PHP Version: the last
 - PDFParser Version: the last

### Code

function extrairPalavrasChaveDoPDF($caminhoTemporarioPDF)
{
    require 'vendor/autoload.php';

    $parser = new \Smalot\PdfParser\Parser();

    $pdf_path = 'ficheiros/' . $caminhoTemporarioPDF;
    $pdf = $parser->parseFile($pdf_path);

    $text = $pdf->getText();

    return $text;
}

if (isset($_FILES['ficheiro'])) {
    $ficheiros = $_FILES['ficheiro'];
    $tudo_certo = true;
    foreach ($ficheiros['name'] as $index => $nome_ficheiro) {
        $erro = $ficheiros['error'][$index];
        $tamanho = $ficheiros['size'][$index];
        $tmp_name = $ficheiros["tmp_name"][$index];

        $deu_certo = enviarArquivo($erro, $tamanho, $nome_ficheiro, $tmp_name);

        if ($deu_certo) {
   
            $palavras_chave = extrairPalavrasChaveDoPDF($tmp_name); 
    

    
            echo "<div id='caminhoPDF' data-caminho='$tmp_name'></div>";
        } else {
            $tudo_certo = false;
        }
    }
    if ($tudo_certo) {
        echo "<p>Todos os Ficheiros foram enviados</p>";
    } else {
        echo "<p>Falha ao enviar os Ficheiros</p>";
    }
}

**Comment by k00ni** [comment]
The path to your PDF file is broken: `ficheiros/C:\xampp\tmp\phpA3AF.tmp`. Please check `$caminhoTemporarioPDF` and `$pdf_path`. 

Its not a problem with PDFParser.

**Comment by ItsTheChiva** [comment]
ok im gonna try again but if dont work i dont know how im gonna read a pdf file

**Comment by k00ni** [comment]
Please have a look here: https://github.com/smalot/pdfparser/blob/master/doc/Usage.md
