### ISSUE TITLE
- The code disappears.

### ISSUE THREAD

**Issue by jeoungss12** [smalot/pdfparser#724]
- PHP Version:  7.2
 - PDFParser Version:  v2.10.0

### Description:
-  "-" The code disappears.

**Comment by k00ni** [comment]
No offence, but this bug report is almost useless. 

Is there a PDF file we can check for ourselves? What did you do aka your code? Anything done to the content before/after parsing it? What means disappears? So many questions ...

**Comment by jeoungss12** [comment]
Sorry, the issue has been resolved.
It was a problem of invisible letters.
