### ISSUE TITLE
Fatal error: Cannot declare class Smalot\PdfParser\Parser, because the name is already in use in \libs\pdfparser-master\src\Smalot\PdfParser\Parser.php on line 49

### ISSUE THREAD

**Issue by bhaktvanti** [smalot/pdfparser#728]
- PHP Version: 8.2.13
 - PDFParser Version: v2.10.0

### Description:
I included the file alt_autoload.php-dist without composer. It throws below error 

**Fatal error: Cannot declare class Smalot\PdfParser\Parser, because the name is already in use in \libs\pdfparser-master\src\Smalot\PdfParser\Parser.php on line 49**

### Code

```
require dirname(__FILE__).'/libs/pdfparser-master/alt_autoload.php-dist';
require dirname(__FILE__) . "/libs/pdfparser-master/src/Smalot/PdfParser/Parser.php";

$parser = new Parser(); 
// Parse the PDF file
$pdf = $parser->parseFile('PS Spotlight Newsletter Design.pdf');

// Retrieve PDF details
$details = $pdf->getDetails();

// Get the custom properties
$customProperties = [];
foreach ($details as $property => $value) {
    // Custom properties usually start with "Custom"
   // if (strpos($property, 'Searchable') === 0) {
    if (strpos(strtolower($property), 'searchable') !== false) {
        $customProperties[$property] = $value;      
    }
} 
```

**Comment by k00ni** [comment]
When using `alt_autoload.php-dist` there is no need to manually include `Parser.php` too, because the autoload-file already includes all required PDFParser classes. 

Remove the following line in your code and it should work:

```php
require dirname(__FILE__) . "/libs/pdfparser-master/src/Smalot/PdfParser/Parser.php";
```

**Comment by k00ni** [comment]
Reopen if the problem persists.
