### ISSUE TITLE
Problem with multiple authors

### ISSUE THREAD

**Issue by sinnbeck** [smalot/pdfparser#79]
If a document has multiple authors then only the first one i retrieved.
The author field is setup as ; seperated (with a space as well).
Example
Jane Doe; John Doe

This will only retrieve Jane Doe.

I have not been able to find the error myself.

René Sinnbeck

**Comment by Resin01** [comment]
I have done some research and it would seem that PDF Parser checks the /Author() tag in the file, where as my files uses Dublin Core so store the metadata.
http://www.pdfa.org/2011/08/pdfa-metadata-xmp-rdf-dublin-core/

Here is an example.
    <dc:creator>
    <rdf:Seq>
    <rdf:li>Chad Cook</rdf:li>
    <rdf:li>Kenneth Learman</rdf:li>
    <rdf:li>Chris Showalter</rdf:li>
    <rdf:li>Vincent Kabbaz</rdf:li>
    <rdf:li>Bryan O'Halloran</rdf:li>
    </rdf:Seq>
    </dc:creator>

Is there some way to get the DC metadata?

**Comment by k00ni** [comment]
@sinnbeck I know this issue is super old, but can you please test if #611 fixes your problem? That would be helpful.

**Comment by sinnbeck** [comment]
I sadly dont work with the system from back then anymore, so I have no way of testing sadly. But I will close this thread as I am sure it is solved :)
