### ISSUE TITLE
empty page

### ISSUE THREAD

**Issue by aghict** [smalot/pdfparser#84]
Hello
This is my code:
include ("Smalot/PdfParser/Parser.php");

$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile("Document1_pdfxchange.pdf");
 
$text = $pdf->getText();
echo $text;

Now I get empty page how can I fix this issue?

**Comment by smalot** [comment]
Hi,
You need to use "composer" to autoload all necessary classes.
https://getcomposer.org/

**Comment by aghict** [comment]
Hello
I can't install composer.
