### ISSUE TITLE
Problem in PDF with columns layout

### ISSUE THREAD

**Issue by oliveiraxavier** [smalot/pdfparser#89]
I have a pdf with four columns on each page. When generating the text, the text display order is different from the PDF file.

Are columns from pdf file:
Example:

page 1
yyyy dddd ASDF eeeaaa
bbbb eeee FDSA aaaaa
cccc ffffff FAAS iiiiiiiiii

page 2
1111 4444 1122 4455
2222 5555 2233 5566
3333 6666 3344 6677

The txt file returns:

page 1
yyyy
bbbb
cccc
dddd
eeee
eeeaaa
aaaaa
iiiiiiiiii
ASDF
FDSA
FAAS

page 2
1111
2222
3333
4444
5555
6666
4455
5566
6677
1122
2233
3344

---

The correct way to view it:

page 1
yyyy
bbbb
cccc
dddd
eeee
ffffff
ASDF
FDSA
FAAS
eeeaaa
aaaaa
iiiiiiiiii

page 2
1111
2222
3333
4444
5555
6666
1122
2233
3344
4455
5566
6677

How to solve this?

**Comment by jinraynor1** [comment]
It seems you have to use getDataTm method to check for x,y coordinates and sort according to that.
