### ISSUE TITLE
Silent Fatal Error when running on Cygwin Windows at 'TJ' case in Object.php

### ISSUE THREAD

**Issue by CMCDragonkai** [smalot/pdfparser#91]
When running on Cygwin Windows, after running `$pdf->getText()` function, I ended up with a silent fatal error even with error reporting switched to the highest.

I dug into it, and found that the rabbit hole leads to the `TJ` case in Object.php which leads to this statement `$sub_text = $current_font->decodeText($command[self::COMMAND]);`. It appears that on Cygwin Windows, there's some problem with decoding the fonts?

Moved all of the code to OSX, ran it, and it succeeded.

Strange to have a fatal error though, is there anything suppressing errors?

**Comment by LeonMelis** [comment]
I encountered the same issue. The problem actually starts in the 'Tf' case, which does `$current_font = $page->getFont($id)` without checking if `$page` does exist. If $page is not set, `$current_font` becomes null and the 'TJ' case to fail.

Interestingly, the 'Do' case seems to do it right, it first checks if `$page` is not null.

Anyway, I'll submit a PR to fix this.
