### ISSUE TITLE
How can I read line from pdf file

### ISSUE THREAD

**Issue by bircastri** [smalot/pdfparser#93]
I all, I want to parse some PDF file. So I have used PDFParser library and I have build this code:

````php
<?php
    // Include Composer autoloader if not already done.
    include 'vendor/autoload.php';
    // Parse pdf file and build necessary objects.
    $parser = new \Smalot\PdfParser\Parser();
    $pdf    = $parser->parseFile('XA035 - Luis gui Lopes esteves.pdf');
    $pages  = $pdf->getPages(); 
	// Loop over each page to extract text.
	foreach ($pages as $page) {
		echo $page->getText();
	}
?> 
````

This code works, but I'm not able to read line for line. If in my pdf there are this line

    PERSONAL INFORMATION Marco Mengoni
    Italia
    Via della giustizia

when I call my page the echo $text; print this on the page:

    PERSONAL INFORMATION Marco Mengoni Italia Via Della Giustizia.

Now is there a mode to parse single line????

regards

**Comment by Cyrille37** [comment]
"line" concept does not exists in PDF file.

**Comment by smalot** [comment]
Hi all,
Unfortunatelly Cyrille is right.
In PDF there is only positions so text is placed under the previous "line". No "new line" or "feed line" exists.
BR

**Comment by alonemayank** [comment]
I am able to put line breaks in extracted text with help of 

```
//Get the text
$text=$pdf->getText();

echo nl2br($text);

$pdfText= nl2br($text);
```

The issue here is sometimes there are no breaks in extracted text but in PDF there are lines breaks.

This is quite specific with tabular structures in PDF I think.

**Comment by SteveThePest** [comment]
Hi Sebastien,

in the demo section your parser parses PDF text and groups it into meaningful and consistent packages of information, while the getText() method is just streaming all the text with no text organisation whatsoever.

Is there a method to replicate that using your APIs?

Thanks a lot.

Kind regards

**Comment by dmcchanaka** [comment]
![Screenshot 2022-10-27 at 11 52 21](https://user-images.githubusercontent.com/38916928/198215538-7db10631-4493-4960-854e-c42ba324d7fc.png)

I tried to read this as a one line. but it is always showing as a two lines. i used like this. if you can please help me

$text=$pdf->getText();

echo nl2br($text);

**Comment by k00ni** [comment]
> I tried to read this as a one line. but it is always showing as a two lines.

nl2br inserts line breaks, https://www.php.net/manual/en/function.nl2br.php, so don't use it. Try str_replace and remove newlines (like `\n`).

**Comment by moidcr** [comment]
Hello friends, I have done something that has worked for me, maybe it can help, first apply a line break replacement to the extracted text and then explode for the replacement character or string

`
$parser = new \Smalot\PdfParser\Parser();
$document = $parser->parseFile($file_path);
$text = $document->getText();
text2  = str_replace(array("\n", "\r"), '==BR==', $text);
$parts = explode('==BR==', $text2);`
